// Attached tree blossoms: drawn or preset petal heads anchored to the
// canopy's real leaf cards. Standalone flowers belong to Flower Lab and are
// generated by the shared plant engine, not by this tree-only adornment.
// Placements are deterministic per tree seed; heads are canvas textures built
// from the same traceLeafShapePath silhouettes as leaves.

import * as THREE from 'three';
import { createFlowerHeadTexture, FLOWER_SPECIES } from '../../../src/vegetation/index.js';
import { createFlowerHeadNodeMaterial } from '../../../src/shaders-tsl/flower.js';

// Sakura/magnolia-style blossoms attach to canopy cards. Density is the only
// placement decision here; ground patches are authored as flower assets.
export const FLOWER_PLACEMENTS = Object.freeze([
  { fraction: 0.12, id: 'sparse', label: 'Sparse' },
  { fraction: 0.32, id: 'dense', label: 'Dense' },
]);

// Old Tree Lab documents could store ground-patch ids. Keep them readable by
// migrating their intent to attached canopy density; they are deliberately
// absent from the authoring UI so no new ground patches are created here.
const LEGACY_PLACEMENT_FRACTIONS = Object.freeze({ cluster: 0.12, meadow: 0.32, ring: 0.2 });

// Species catalog + head sprites are shared with the StylizedFlower plant —
// see src/vegetation/flowerSpecies.js. Re-exported for the Flowers panel.
export { FLOWER_SPECIES };
// Back-compat alias: the catalog superseded the original three-entry list.
export const PETAL_PRESETS = FLOWER_SPECIES;

// Deterministic placement rng (mulberry32-alike, tiny).
function rng(seed) {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function createFlowerPatch({ engine, store }) {
  const { scene } = engine;
  let group = null;
  let lastKey = '';

  function dispose() {
    if (!group) return;
    scene.remove(group);
    group.traverse((child) => {
      child.geometry?.dispose();
      const map = child.material?.map ?? child.material?.uniforms?.uMap?.value;
      map?.dispose?.();
      child.material?.dispose?.();
    });
    group = null;
  }

  // Real canopy card centers (every 4th position vertex — billboards share
  // their center across 4 corners), world-transformed: the blossom anchors.
  function canopyCardCenters() {
    const plant = engine.getPlant();
    const positionAttr = plant?.canopyMesh?.geometry.getAttribute('position');
    if (!positionAttr) return [];
    plant.canopyMesh.updateWorldMatrix(true, false);
    const centers = [];
    const point = new THREE.Vector3();
    for (let v = 0; v < positionAttr.count; v += 4) {
      point.fromBufferAttribute(positionAttr, v);
      plant.canopyMesh.localToWorld(point);
      centers.push(point.clone());
    }
    return centers;
  }

  function rebuild() {
    dispose();
    const { flowers, settings } = store.getState();
    if (!flowers || flowers.preset === 'none') return;
    const placement = FLOWER_PLACEMENTS.find((entry) => entry.id === flowers.preset)
      ?? (LEGACY_PLACEMENT_FRACTIONS[flowers.preset]
        ? { fraction: LEGACY_PLACEMENT_FRACTIONS[flowers.preset] }
        : null);
    if (!placement) return;

    const size = settings.plant.size;

    const centers = canopyCardCenters();
    if (!centers.length) return;
    const random = rng((settings.plant.seed + 91) >>> 0);
    const picked = centers.filter(() => random() < placement.fraction);
    if (!picked.length) return;
    group = new THREE.Group();
    group.name = 'Tree blossoms';
    const blossomSize = size * 0.16 * (flowers.scale ?? 1);
    const headGeometry = new THREE.PlaneGeometry(blossomSize, blossomSize);
    const headMaterial = createFlowerHeadNodeMaterial({
      map: createFlowerHeadTexture(flowers),
      windSpeed: 1.1,
      windStrength: blossomSize * 0.1,
    });
    const heads = new THREE.InstancedMesh(headGeometry, headMaterial, picked.length);
    const matrix = new THREE.Matrix4();
    const quaternion = new THREE.Quaternion();
    const one = new THREE.Vector3(1, 1, 1);
    picked.forEach((center, index) => {
      quaternion.setFromEuler(new THREE.Euler(
        (random() - 0.5) * 1.2, random() * Math.PI * 2, (random() - 0.5) * 1.2));
      matrix.compose(center, quaternion, one);
      heads.setMatrixAt(index, matrix);
    });
    group.add(heads);
    scene.add(group);
  }

  // Blossoms anchor to canopy cards: re-place after every plant rebuild.
  engine.onRebuilt(() => rebuild());

  store.subscribe(() => {
    const { flowers, settings } = store.getState();
    const key = JSON.stringify([flowers, settings.plant.seed, settings.plant.size]);
    if (key !== lastKey) {
      lastKey = key;
      rebuild();
    }
  });

  return { rebuild };
}
