export function createSkyAtmosphereSettings(input?: {}): {
    mieCoefficient: number;
    mieDirectionalG: number;
    rayleigh: number;
    turbidity: number;
};
export function createSkyTimeKeyframes(input?: readonly (Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.05;
    exposure: 0.48;
    horizonGlow: 0.04;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 0;
    id: "night";
    label: "Night";
    saturation: 0.9;
    zenithTint: readonly number[];
}> | Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.04;
    exposure: 0.88;
    horizonGlow: 0.72;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 6;
    id: "dawn";
    label: "Dawn";
    saturation: 1.12;
    zenithTint: readonly number[];
}> | Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.08;
    exposure: 1.06;
    horizonGlow: 0.16;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 13;
    id: "day";
    label: "Day";
    saturation: 1.18;
    zenithTint: readonly number[];
}> | Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.1;
    exposure: 0.82;
    horizonGlow: 0.9;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 18;
    id: "sunset";
    label: "Sunset";
    saturation: 1.2;
    zenithTint: readonly number[];
}> | Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.07;
    exposure: 0.56;
    horizonGlow: 0.16;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 22;
    id: "late-night";
    label: "Late Night";
    saturation: 0.94;
    zenithTint: readonly number[];
}>)[]): any[];
export function sampleSkyTimeKeyframes(input: any, hourInput: any): {
    belowHorizonTint: number[];
    contrast: any;
    exposure: any;
    from: any;
    horizonGlow: any;
    horizonGlowColor: number[];
    horizonTint: number[];
    hour: number;
    saturation: any;
    to: any;
    amount: number;
    zenithTint: number[];
};
export function celestialDirectionForHour(hourInput: any, { moon }?: {
    moon?: boolean;
}): number[];
export const DEFAULT_SKY_ATMOSPHERE: Readonly<{
    mieCoefficient: 0.005;
    mieDirectionalG: 0.8;
    rayleigh: 1.35;
    turbidity: 4.2;
}>;
export const DEFAULT_SKY_TIME_KEYFRAMES: readonly (Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.05;
    exposure: 0.48;
    horizonGlow: 0.04;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 0;
    id: "night";
    label: "Night";
    saturation: 0.9;
    zenithTint: readonly number[];
}> | Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.04;
    exposure: 0.88;
    horizonGlow: 0.72;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 6;
    id: "dawn";
    label: "Dawn";
    saturation: 1.12;
    zenithTint: readonly number[];
}> | Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.08;
    exposure: 1.06;
    horizonGlow: 0.16;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 13;
    id: "day";
    label: "Day";
    saturation: 1.18;
    zenithTint: readonly number[];
}> | Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.1;
    exposure: 0.82;
    horizonGlow: 0.9;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 18;
    id: "sunset";
    label: "Sunset";
    saturation: 1.2;
    zenithTint: readonly number[];
}> | Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.07;
    exposure: 0.56;
    horizonGlow: 0.16;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 22;
    id: "late-night";
    label: "Late Night";
    saturation: 0.94;
    zenithTint: readonly number[];
}>)[];
export const CALL_ME_SENSEI_SKY_ATMOSPHERE: Readonly<{
    mieCoefficient: 0.004;
    mieDirectionalG: 0.78;
    rayleigh: 1.72;
    turbidity: 3.1;
}>;
export const CALL_ME_SENSEI_SKY_TIME_KEYFRAMES: readonly (Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.02;
    exposure: 0.42;
    horizonGlow: 0.06;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 0;
    id: "sensei-night";
    label: "Sensei Night";
    saturation: 1.02;
    zenithTint: readonly number[];
}> | Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.02;
    exposure: 0.82;
    horizonGlow: 0.82;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 6;
    id: "sensei-dawn";
    label: "Sensei Dawn";
    saturation: 1.16;
    zenithTint: readonly number[];
}> | Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.035;
    exposure: 0.9;
    horizonGlow: 0.24;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 10;
    id: "sensei-morning";
    label: "Sensei Morning";
    saturation: 1.2;
    zenithTint: readonly number[];
}> | Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.04;
    exposure: 0.9;
    horizonGlow: 0.18;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 13;
    id: "sensei-day";
    label: "Sensei Day";
    saturation: 1.22;
    zenithTint: readonly number[];
}> | Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.07;
    exposure: 0.8;
    horizonGlow: 0.96;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 18;
    id: "sensei-sunset";
    label: "Sensei Sunset";
    saturation: 1.24;
    zenithTint: readonly number[];
}> | Readonly<{
    belowHorizonTint: readonly number[];
    contrast: 1.04;
    exposure: 0.5;
    horizonGlow: 0.18;
    horizonGlowColor: readonly number[];
    horizonTint: readonly number[];
    hour: 22;
    id: "sensei-late-night";
    label: "Sensei Late Night";
    saturation: 1.06;
    zenithTint: readonly number[];
}>)[];
