export function normalizeEnvironmentDebugMode(mode: any): any;
export function createEnvironmentSettings(options?: {}): {
    features: any;
    parameters: any;
};
export function applyEnvironmentSettingsToMaterial(material: any, settingsInput?: {}): any;
export function updateEnvironmentBoundsUniforms(material: any, environmentBox: any): any;
export const DEFAULT_ENVIRONMENT_FEATURES: Readonly<{
    alphaCutout: true;
    alphaMap: true;
    ambientLight: true;
    ambientProbe: true;
    aoMap: true;
    aoOverlay: true;
    directionalLights: true;
    emissive: true;
    emissiveMap: true;
    foliageCutout: true;
    heightFog: true;
    interiorOcclusion: true;
    leftSideShadow: true;
    lightMap: true;
    normalMap: true;
    packedMap: true;
    planarReflection: true;
    pointLights: true;
    shadowMask: true;
    shadowMesh: true;
    skyTint: true;
    specular: true;
    spotLights: true;
    sunBoost: true;
    untexturedGradient: true;
    vertexAo: true;
    windowCutout: true;
}>;
export const ENVIRONMENT_DEBUG_MODES: Readonly<{
    off: 0;
    albedo: 1;
    lit: 2;
    ambient: 3;
    direct: 4;
    shadowMask: 5;
    pointLight: 6;
    spotLight: 7;
    occlusion: 8;
    bakedGi: 9;
    normal: 10;
    vertexAo: 11;
    specular: 12;
    emissive: 13;
    windowMask: 14;
    roomOcclusion: 15;
    alpha: 16;
}>;
export const ENVIRONMENT_SHARED_UNIFORM_NAMES: readonly string[];
export const DEFAULT_ENVIRONMENT_PARAMETERS: Readonly<{
    ambientProbeBlend: any;
    ambientStrength: any;
    ambientLightInfluence: any;
    aoMapStrength: any;
    aoWarmth: any;
    bakedGlowStrength: any;
    cloudShadowCoverage: any;
    cloudShadowScale: any;
    cloudShadowStrength: any;
    directLightStrength: any;
    emissiveMapStrength: any;
    emissiveStrength: any;
    exposure: any;
    heightFogColor: any;
    heightFogDensity: any;
    heightFogFalloff: any;
    interiorOcclusionColor: any;
    interiorOcclusionStrength: any;
    leftSideShadow: any;
    leftSideShadowColor: any;
    lightMapLift: any;
    lightMapStrength: any;
    lightingInfluence: any;
    normalMapStrength: any;
    packedOcclusionStrength: any;
    planarReflectionFresnel: any;
    planarReflectionStrength: any;
    pointLightStrength: any;
    saturation: any;
    shadeSoftness: any;
    shadeStrength: any;
    shadowLift: any;
    sunShadowStrength: any;
    shadowTintColor: any;
    skyGroundTint: any;
    skyTintStrength: any;
    skyTopTint: any;
    specularColor: any;
    specularShininess: any;
    specularSoftness: any;
    specularStrength: any;
    spotLightStrength: any;
    sunBoost: any;
    sunBoostColor: any;
    cliffFade: any;
    cliffNoiseScale: any;
    cliffNoiseStrength: any;
    cliffStart: any;
    colormapDecode: any;
    colormapMode: any;
    colormapStrength: any;
    dualDetailMix: any;
    dualDetailScale: any;
    triplanarDetail: any;
    triplanarDetailScale: any;
    triplanarEdgeHighlight: any;
    untexturedGradientStrength: any;
    vtBlendHeight: any;
    vtBlendStrength: any;
    vertexAoStrength: any;
}>;
export const ENVIRONMENT_SETTING_GROUPS: readonly (Readonly<{
    description: "Enables or disables individual environment shader feature paths.";
    id: "features";
    label: "Features";
}> | Readonly<{
    description: "Overrides numeric environment shader uniforms. Auto values preserve material defaults.";
    id: "parameters";
    label: "Shader Parameters";
}>)[];
export const ENVIRONMENT_SETTING_FIELD_SCHEMA: Readonly<{
    features: Readonly<{
        [k: string]: Readonly<{
            defaultValue: any;
            description: string;
            group: any;
            id: `${any}.${any}`;
            key: any;
            label: any;
            range: {
                max: number;
                min: number;
                step: number;
            };
            type: "number" | "boolean" | "color";
        }>;
    }>;
    parameters: Readonly<{
        [k: string]: Readonly<{
            defaultValue: any;
            description: string;
            group: any;
            id: `${any}.${any}`;
            key: any;
            label: any;
            range: {
                max: number;
                min: number;
                step: number;
            };
            type: "number" | "boolean" | "color";
        }>;
    }>;
}>;
