export function applyEnvironmentShader(root: any, { assetId, bakeVertexAo, debugOutputMode, environmentBox, features, hasSun, materialLook, materialManifest, objectClass, parameters, preset, roleOverrides, scanStylize, scanStylizeParams, scenario, settings, shaderMode, openWindows, vertexAoOptions, }?: {
    assetId?: string;
    bakeVertexAo?: string;
    debugOutputMode?: string;
    environmentBox?: any;
    features?: {};
    hasSun?: boolean;
    materialLook?: any;
    materialManifest?: any;
    objectClass?: string;
    parameters?: {};
    preset?: any;
    roleOverrides?: any;
    scanStylize?: string;
    scanStylizeParams?: {};
    scenario?: any;
    settings?: {};
    shaderMode?: string;
    openWindows?: boolean;
    vertexAoOptions?: {};
}): Promise<{
    aoOverlayMeshCount: number;
    classification: any[];
    convertedMeshCount: number;
    manifestWarnings: any[];
    manufacturedAssetId: string;
    manufacturedObjectClass: any;
    preset: string;
    scanStylizedMaterialCount: number;
    scenario: string;
    shaderMode: string;
    shadowMeshCount: number;
    vertexAoMeshCount: number;
    windowCutoutMaterialCount: number;
}>;
export { bakeEnvironmentVertexAo } from "./environmentVertexAo.js";
export { DEFAULT_SCAN_STYLIZE_PARAMS, applyScanStylizeToMaterial, isScanAssetMaterial, stylizeScanBaseMap } from "./scanAssetStylize.js";
export { ENVIRONMENT_MATERIAL_ROLES, alphaCutoffForMaterial, classifyEnvironmentMaterialRole, isAoOverlayMaterial, isEmissiveEnvironmentMaterial, isEnvironmentAoOverlay, isEnvironmentShadowMesh, isFoliageMaterial, isUtilityTextureLabel, isWindowCutoutMaterial, materialBaseColor, materialText, objectMaterialText, sourceOpacity, textureLabel, textureSourceUrl, toMaterialArray, usesAlphaCutout } from "./environmentMaterialClassifier.js";
export { MANUFACTURED_CONTENT_FLAGS, MANUFACTURED_MATERIAL_BASES, MANUFACTURED_MATERIAL_FINISHES, MANUFACTURED_MATERIAL_LOOK_VERSION, MANUFACTURED_MATERIAL_MANIFEST_TYPE, MANUFACTURED_MATERIAL_MANIFEST_VERSION, MANUFACTURED_OBJECT_CLASSES, MANUFACTURED_RENDER_MODES, MANUFACTURED_STRUCTURAL_ROLES, analyzeManufacturedAsset, applyManufacturedMaterialManifest, classifyManufacturedMaterial, createManufacturedMaterialClassification, createManufacturedMaterialLook, inferManufacturedObjectClass, resolveManufacturedMaterialLook, validateManufacturedMaterialLook, validateManufacturedMaterialManifest } from "./manufacturedMaterialContract.js";
export { DEFAULT_ENVIRONMENT_FEATURES, DEFAULT_ENVIRONMENT_PARAMETERS, ENVIRONMENT_DEBUG_MODES, ENVIRONMENT_SETTING_FIELD_SCHEMA, ENVIRONMENT_SETTING_GROUPS, applyEnvironmentSettingsToMaterial, createEnvironmentSettings, normalizeEnvironmentDebugMode, updateEnvironmentBoundsUniforms } from "./environmentSettings.js";
export { advanceEnvironmentShaderTime, createDebugEnvironmentMaterial, createEnvironmentAoMaterial, createEnvironmentMaterial, createEnvironmentShadowMaterial, createEnvironmentWindowOpeningMaterial, resetEnvironmentShaderTime, setEnvironmentAmbientProbeColors, setEnvironmentCloudShadow, setEnvironmentDebugOutput, setEnvironmentOpenings, setEnvironmentPlanarReflection } from "./environmentShaderMaterials.js";
export { copyTextureTransform, fallbackEnvironmentBlackTexture, fallbackEnvironmentNormalTexture, fallbackEnvironmentWhiteTexture, loadEnvironmentTexture, resolveEnvironmentTextureSet, textureKindCandidateUrl, textureUrlExists } from "./environmentTextureResolver.js";
