export function createMaterialMapSettings(options?: any): {
    aoMap: any;
    aoStrength: any;
    detailMap: any;
    detailRepeat: any;
    detailStrength: any;
    emissiveColor: any;
    emissiveMap: any;
    emissiveStrength: any;
    enabled: boolean;
    matcapMap: any;
    matcapStrength: any;
    metalnessMap: any;
    metalnessStrength: any;
    normalMap: any;
    normalScale: any;
    normalStrength: any;
    rampMap: any;
    rampStrength: any;
    roughnessMap: any;
    roughnessStrength: any;
    sourceMode: "off" | "source";
    specularColorMap: any;
    specularColorStrength: any;
};
export function collectMaterialMapTextures(mat: any): ({
    texture: any;
    colorSpace: "srgb";
} | {
    texture: any;
    colorSpace: "";
})[];
export function resolveMaterialMapsForMaterial(settings: any, mat: any): {
    aoMap: any;
    aoStrength: any;
    detailMap: any;
    detailRepeat: any;
    detailStrength: any;
    emissiveColor: any;
    emissiveMap: any;
    emissiveStrength: number;
    hasAoMap: boolean;
    hasDetailMap: boolean;
    hasEmissiveMap: boolean;
    hasMatcapMap: boolean;
    hasMetalnessMap: boolean;
    hasNormalMap: boolean;
    hasRampMap: boolean;
    hasRoughnessMap: boolean;
    hasSpecularColorMap: boolean;
    matcapMap: any;
    matcapStrength: any;
    metalness: any;
    metalnessMap: any;
    metalnessStrength: any;
    normalMap: any;
    normalScale: any;
    normalStrength: any;
    rampMap: any;
    rampStrength: any;
    roughness: any;
    roughnessMap: any;
    roughnessStrength: any;
    specularColorMap: any;
    specularColorStrength: any;
};
export const MATERIAL_MAP_SOURCE_MODES: Readonly<{
    off: "off";
    source: "source";
}>;
export const DEFAULT_MATERIAL_MAP_SETTINGS: Readonly<{
    aoStrength: 0;
    detailRepeat: number[];
    detailStrength: 0;
    emissiveColor: number[];
    emissiveStrength: 0;
    enabled: true;
    matcapStrength: 0;
    metalnessStrength: 0;
    normalScale: number[];
    normalStrength: 0;
    rampStrength: 0;
    roughnessStrength: 0;
    sourceMode: "source";
    specularColorStrength: 0;
}>;
