export function createRimLightSettings(options?: any): {
    blockByShadow: any;
    defaultIntensity: any;
    defaultTintColor: any;
    depthCloseWidthReduce: any;
    depthDottedLineFix: boolean;
    depthFadeEndDistance: any;
    depthFadeRange: any;
    depthFadeStartDistance: any;
    depthMask3D: boolean;
    depthSafeDistance: any;
    depthThresholdOffset: any;
    depthWidth: any;
    enabled: boolean;
    eyeIntensity: any;
    faceIntensity: any;
    hairIntensity: any;
    midPoint: any;
    mixWithBaseMapColor: any;
    mode: any;
    skinIntensity: any;
    softness: any;
};
export function resolveRimLightForMaterial(settings: any, { isEye, isFace, isHair, isOutline, isSkin, }?: {
    isEye?: boolean;
    isFace?: boolean;
    isHair?: boolean;
    isOutline?: boolean;
    isSkin?: boolean;
}): {
    blockByShadow: any;
    depthCloseWidthReduce: any;
    depthDottedLineFix: any;
    depthFadeEndDistance: any;
    depthFadeRange: any;
    depthFadeStartDistance: any;
    depthMask3D: any;
    depthSafeDistance: any;
    depthThresholdOffset: any;
    depthWidth: any;
    enabled: boolean;
    intensity: any;
    midPoint: any;
    mixWithBaseMapColor: any;
    modeValue: any;
    softness: any;
    tintColor: any;
};
export const RIM_LIGHT_MODES: Readonly<{
    fresnel: "fresnel";
    depthTexture: "depthTexture";
}>;
export const RIM_LIGHT_MODE_VALUES: Readonly<{
    fresnel: 0;
    depthTexture: 1;
}>;
export const DEFAULT_RIM_LIGHT_SETTINGS: Readonly<{
    blockByShadow: 0.65;
    defaultIntensity: 0.13;
    defaultTintColor: number[];
    depthCloseWidthReduce: 1;
    depthDottedLineFix: true;
    depthFadeEndDistance: 30;
    depthFadeRange: 1;
    depthFadeStartDistance: 20;
    depthMask3D: false;
    depthSafeDistance: 1;
    depthThresholdOffset: 0;
    depthWidth: 1;
    enabled: true;
    eyeIntensity: 0.04;
    faceIntensity: 0.13;
    hairIntensity: 0.23;
    midPoint: 0.48;
    mixWithBaseMapColor: 0.35;
    mode: "depthTexture";
    skinIntensity: 0.13;
    softness: 0.1;
}>;
