// The built-in catalog: every shipped preset/recipe of every cluster as a
// manifest entry. Generated by WALKING the preset modules — content added to
// any cluster accretes here without catalog changes (the roadmap's "manifest
// frozen during 02" promise, paying off).

import { createCatalogEntry } from './manifest.js';
import { BUILT_IN_PROP_PRESETS } from '../propgen/propPresets.js';
import { BUILT_IN_PATH_PRESETS } from '../pathgen/pathPresets.js';
import { BUILT_IN_DEBRIS_PRESETS } from '../debrisgen/debrisPresets.js';
import { getRockgenPresetOptions } from '../rockgen/rockgenPresets.js';
import { getWaterPresetOptions } from '../water/waterSettings.js';
import { getSkyPresetOptions } from '../sky/stylizedSky.js';
import { getLightingPresetOptions } from '../lighting/lightingPresets.js';
import { POST_PROCESSING_PRESETS } from '../post/postProcessing.js';
import { getToonPresetOptions } from '../toon/toonSettings.js';

const slug = (value) => String(value)
  .replace(/[^a-zA-Z0-9]+/g, '-')
  .replace(/^-+|-+$/g, '')
  .toLowerCase();

const thumbFor = (id) => `thumbs/${id.replaceAll('/', '-')}.webp`;

// Curated tree recipes — the vegetation cluster's presets live in tree-lab
// documents rather than a module registry, so the catalog carries a small
// signature set inline (same recipe schema tree-lab exports).
const CURATED_TREES = [
  {
    description: 'Mid-size broadleaf with the studio green canopy.',
    id: 'tree/broadleaf/sensei',
    label: 'Sensei broadleaf',
    recipe: {
      options: { seed: 3, size: 3.2 },
      schema: 'treeRecipe',
      type: 'tree',
      version: 1,
    },
    tags: ['tree', 'vegetation', 'call-me-sensei'],
  },
  {
    description: 'Golden accent tree — one per grove, per the canopy rules.',
    id: 'tree/broadleaf/gold-accent',
    label: 'Gold accent tree',
    recipe: {
      options: { canopyColor: [0.91, 0.73, 0.31], seed: 11, size: 3 },
      schema: 'treeRecipe',
      type: 'tree',
      version: 1,
    },
    tags: ['tree', 'vegetation', 'accent'],
  },
  {
    description: 'Ground-hugging foliage mass for yards and path edges.',
    id: 'tree/bush/hedge',
    label: 'Hedge bush',
    recipe: {
      options: { seed: 5, size: 1.2 },
      schema: 'treeRecipe',
      type: 'bush',
      version: 1,
    },
    tags: ['bush', 'vegetation', 'garden'],
  },
  {
    description: 'Flowering plant with daisy heads.',
    id: 'tree/flower/daisy',
    label: 'Daisy flower',
    recipe: {
      options: { seed: 9, size: 0.5, species: 'daisy' },
      schema: 'treeRecipe',
      type: 'flower',
      version: 1,
    },
    tags: ['flower', 'vegetation', 'meadow'],
  },
];

let cached = null;

/** Assembles (and caches) the full built-in entry list. */
export function builtinCatalogEntries() {
  if (cached) return cached;
  const entries = [];

  for (const preset of BUILT_IN_PROP_PRESETS) {
    entries.push(createCatalogEntry({
      cluster: 'propgen',
      description: preset.description,
      id: preset.id,
      kind: 'recipe',
      label: preset.label,
      recipe: preset.recipe,
      spawn: 'createPropAssetFromRecipe(entry.recipe)',
      tags: preset.tags,
      thumbnail: thumbFor(preset.id),
    }));
  }

  for (const tree of CURATED_TREES) {
    entries.push(createCatalogEntry({
      cluster: 'vegetation',
      description: tree.description,
      id: tree.id,
      kind: 'recipe',
      label: tree.label,
      recipe: tree.recipe,
      spawn: 'propAssetFromObject(createPlantFromRecipe(entry.recipe))',
      tags: tree.tags,
      thumbnail: thumbFor(tree.id),
    }));
  }

  for (const option of getRockgenPresetOptions()) {
    const id = `rock/${slug(option.value)}`;
    entries.push(createCatalogEntry({
      cluster: 'rockgen',
      id,
      kind: 'preset',
      label: option.label,
      recipe: { preset: option.value, schema: 'rockgenPresetRef', version: 1 },
      spawn: "propAssetFromObject(new THREE.Mesh(meshDocument(createRockDocument({ preset: entry.recipe.preset, seed })), new THREE.MeshStandardMaterial({ vertexColors: true })))",
      tags: ['rock', 'nature', 'stone'],
      thumbnail: thumbFor(id),
    }));
  }

  for (const preset of BUILT_IN_DEBRIS_PRESETS) {
    const id = `debris/${slug(preset.id)}`;
    entries.push(createCatalogEntry({
      cluster: 'debrisgen',
      description: preset.description,
      id,
      kind: 'recipe',
      label: preset.label,
      recipe: { schema: 'debrisSettings', settings: preset.settings, version: 1 },
      spawn: 'propAssetFromObject(createDebrisAsset(entry.recipe.settings))',
      tags: ['debris', preset.type, slug(preset.variant)],
      thumbnail: thumbFor(id),
    }));
  }

  for (const preset of BUILT_IN_PATH_PRESETS) {
    entries.push(createCatalogEntry({
      cluster: 'pathgen',
      description: preset.description,
      id: `path/${slug(preset.id)}`,
      kind: 'preset',
      label: preset.label,
      recipe: preset.recipe,
      spawn: 'createStylizedPathsFromRecipe(entry.recipe, { heightAt, waterLevel, size })',
      tags: ['path', 'network', slug(preset.id) === 'call-me-sensei' ? 'call-me-sensei' : 'roads'],
    }));
  }

  // Settings presets: browsable + copy-paste, not spawnable objects.
  for (const option of getWaterPresetOptions()) {
    entries.push(createCatalogEntry({
      cluster: 'water',
      description: option.description,
      id: `water/${slug(option.id)}`,
      kind: 'preset',
      label: option.label,
      recipe: { preset: option.id, schema: 'waterPresetRef', version: 1 },
      spawn: `new WaterSurface({ preset: '${option.id}', width, depth, bedHeight: heightAt })`,
      tags: ['water', 'settings'],
    }));
  }
  for (const option of getSkyPresetOptions()) {
    entries.push(createCatalogEntry({
      cluster: 'sky',
      description: option.description,
      id: `sky/${slug(option.id)}`,
      kind: 'preset',
      label: option.label,
      recipe: { preset: option.id, schema: 'skyPresetRef', version: 1 },
      spawn: `new StylizedSky({ preset: '${option.id}' })`,
      tags: ['sky', 'settings'],
    }));
  }
  for (const option of getLightingPresetOptions()) {
    const resolverByKind = {
      look: 'resolveLightingLookPreset',
      luminaire: 'resolveLuminairePreset',
      quality: 'resolveLightingQualityPreset',
      rig: 'resolveLightingRigPreset',
    };
    const resolver = resolverByKind[option.kind];
    entries.push(createCatalogEntry({
      cluster: 'lighting',
      description: option.description,
      id: `lighting/${option.kind}/${slug(option.id)}`,
      kind: 'preset',
      label: option.label,
      recipe: {
        kind: option.kind,
        preset: option.id,
        schema: 'lightingPresetRef',
        version: 1,
      },
      spawn: `${resolver}('${option.id}')`,
      tags: ['lighting', option.kind, 'settings'],
    }));
  }
  for (const id of Object.keys(POST_PROCESSING_PRESETS)) {
    entries.push(createCatalogEntry({
      cluster: 'post',
      id: `post/${slug(id)}`,
      kind: 'preset',
      label: id,
      recipe: { preset: id, schema: 'postPresetRef', version: 1 },
      spawn: `createPostProcessingPipeline({ renderer, scene, camera, preset: '${id}' })`,
      tags: ['post', 'settings'],
    }));
  }
  for (const option of getToonPresetOptions()) {
    entries.push(createCatalogEntry({
      cluster: 'toon',
      description: option.description,
      id: `toon/${slug(option.id)}`,
      kind: 'preset',
      label: option.label,
      recipe: { preset: option.id, schema: 'toonPresetRef', version: 1 },
      spawn: `applyToonShader(characterRoot, { settings: createToonSettings({ preset: '${option.id}' }) })`,
      tags: ['toon', 'character', 'settings'],
    }));
  }

  cached = entries;
  return entries;
}
