// Canonical ToonLab product inventory.
//
// This is deliberately derived from the artifacts required to make and ship a
// complete stylized real-time scene, not from the editors that happen to exist
// today. Existing implementations are mapped onto this inventory only after
// the product boundary is defined.

export const LAB_EDITOR_STATUS = Object.freeze({
  beta: Object.freeze({
    description: 'The editor is technically complete and available for beta use while production feedback and final approval are collected.',
    label: 'Beta',
  }),
  inProgress: Object.freeze({
    description: 'The editor is actively being implemented or migrated against the finalized workflow and public schema.',
    label: 'In progress',
  }),
  migrationRequired: Object.freeze({
    description: 'An editor exists, but it has not been migrated to and accepted against the finalized workflow and public schema.',
    label: 'Migration required',
  }),
  notStarted: Object.freeze({
    description: 'The required dedicated editor does not exist yet.',
    label: 'Not started',
  }),
  validation: Object.freeze({
    description: 'Integration scene only; it validates production artifacts but does not own a portable npm artifact.',
    label: 'Validation only',
  }),
});

export const LIBRARY_STATUS = Object.freeze({
  beta: Object.freeze({
    description: 'The portable runtime contract is exported, verified, and available for beta use while compatibility feedback is collected.',
    label: 'Beta',
  }),
  inProgress: Object.freeze({
    description: 'The portable runtime or schema is actively being completed for the approved npm contract.',
    label: 'In progress',
  }),
  migrationRequired: Object.freeze({
    description: 'Some runtime or schema exists, but the portable API, documents, migrations, verification, or package boundary are not approved for npm.',
    label: 'Migration required',
  }),
  notApplicable: Object.freeze({
    description: 'This validation surface does not own a separately published library artifact.',
    label: 'Not applicable',
  }),
  notStarted: Object.freeze({
    description: 'No accepted portable runtime and document contract exists for this npm target.',
    label: 'Not started',
  }),
});

// Backwards compatibility for code that only knew the old single editor
// status. New UI and verification must use both axes.
export const LAB_STATUS = LAB_EDITOR_STATUS;

function entry(definition) {
  if (!LAB_EDITOR_STATUS[definition.labStatus]) {
    throw new Error(`Unknown editor status "${definition.labStatus}" for ${definition.id}.`);
  }
  if (!LIBRARY_STATUS[definition.libraryStatus]) {
    throw new Error(`Unknown library status "${definition.libraryStatus}" for ${definition.id}.`);
  }
  for (const field of ['artifact', 'desc', 'group', 'i', 'id', 'jp', 'npm', 'title']) {
    if (!definition[field]) throw new Error(`Lab "${definition.id}" is missing ${field}.`);
  }
  return Object.freeze({
    ...definition,
    previewContract: 'toonlab/lab-preview-environment@1',
  });
}

// LOOK DEVELOPMENT
// These are all canonical style-bundle owners. Some save material profiles;
// others save integrated rendering-system styles because their shader controls
// cannot be separated usefully from animation, simulation, or composition.
export const LOOK_DEVELOPMENT_LABS_SHOWCASE = Object.freeze([
  entry({
    artifact: 'Material profile',
    desc: 'Cel bands, skin, eyes, hair, cloth, creature surfaces, face shadows, highlights, semantic roles, and character-bound equipment',
    group: 'look',
    href: '/shader-lab/',
    i: 'L01',
    id: 'shader',
    jp: '人物',
    npm: '@call-me-sensei/toonlab/toon',
    labStatus: 'beta',
    libraryStatus: 'beta',
    title: 'Character & Creature Shader Lab',
  }),
  entry({
    artifact: 'Material profile',
    desc: 'Tree canopies, foliage cards, needles, bark, trunks, branches, translucency, wind response, seasonal inputs, and woody-surface lighting',
    family: 'Vegetation',
    group: 'look',
    href: '/tree-shader-lab/',
    i: 'L02a',
    id: 'tree-shader',
    jp: '樹影',
    npm: '@call-me-sensei/toonlab/vegetation-shaders',
    labStatus: 'beta',
    libraryStatus: 'beta',
    title: 'Tree Shader Lab',
  }),
  entry({
    artifact: 'Material profile',
    desc: 'Grass blades, groundcover thin surfaces, root-to-tip gradients, dense-field shading, gust sheen, bend, interaction, translucency, and weather response',
    family: 'Vegetation',
    group: 'look',
    href: '/grass-shader-lab/',
    i: 'L02b',
    id: 'grass-shader',
    jp: '草影',
    npm: '@call-me-sensei/toonlab/vegetation-shaders',
    labStatus: 'beta',
    libraryStatus: 'beta',
    title: 'Grass Shader Lab',
  }),
  entry({
    artifact: 'Material profile',
    desc: 'Flower petals, centers, leaves, herbaceous stems, cup shading, transmission, thin-surface lighting, wind response, and weather response',
    family: 'Vegetation',
    group: 'look',
    href: '/flower-shader-lab/',
    i: 'L02c',
    id: 'flower-shader',
    jp: '花影',
    npm: '@call-me-sensei/toonlab/vegetation-shaders',
    labStatus: 'beta',
    libraryStatus: 'beta',
    title: 'Flower Shader Lab',
  }),
  entry({
    artifact: 'Material profile',
    desc: 'Projection, distance tint, normals, striping, moss, top layers, source-albedo policy, and stable asset-channel response',
    group: 'look',
    href: '/rock-shader-lab/',
    i: 'L03',
    id: 'rock-shader',
    jp: '岩肌',
    npm: '@call-me-sensei/toonlab/rock-shader',
    labStatus: 'beta',
    libraryStatus: 'beta',
    title: 'Rock & Geology Shader Lab',
  }),
  entry({
    artifact: 'Material profile',
    desc: 'Terrain splats, macro/micro variation, slope and height layers, paths, wetness, snow, ground-field output, and distance treatment',
    family: 'Ground & terrain',
    group: 'look',
    href: '/ground-shader-lab/',
    i: 'L04',
    id: 'terrain-shader',
    jp: '地表',
    npm: '@call-me-sensei/toonlab/ground-shader',
    labStatus: 'beta',
    libraryStatus: 'beta',
    title: 'Terrain & Ground Shader Lab',
  }),
  entry({
    artifact: 'Material profile',
    desc: 'Wood, painted metal, bare metal, plastic, ceramic, masonry, fabric, vehicles, architecture, props, emissive parts, and surface wear',
    group: 'look',
    href: '/manufactured-material-lab/',
    i: 'L05',
    id: 'manufactured-material',
    jp: '人工',
    npm: '@call-me-sensei/toonlab/environment',
    labStatus: 'beta',
    libraryStatus: 'beta',
    title: 'Manufactured Surface Shader Lab',
  }),
  entry({
    artifact: 'Material profile',
    desc: 'Glass, translucent plastic, crystals, ice, thin transparency, refraction, absorption, sorting policy, and graceful fallbacks',
    group: 'look',
    i: 'L06',
    id: 'transparent-shader',
    jp: '透過',
    npm: '@call-me-sensei/toonlab/transparent',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Glass & Transparent Shader Lab',
  }),
  entry({
    artifact: 'Material profile',
    desc: 'Projected and mesh decals for markings, signage, grime, damage, footprints, puddles, graffiti, and terrain/building overlays',
    group: 'look',
    i: 'L07',
    id: 'decal-shader',
    jp: '貼付',
    npm: '@call-me-sensei/toonlab/decals',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Decal & Projected Surface Shader Lab',
  }),
  entry({
    artifact: 'Renderer profile',
    desc: 'Shared sprite, mesh-particle, ribbon, beam, trail, distortion, dissolve, soft-particle, emissive, and blend-mode treatment',
    group: 'look',
    href: '/vfx-lab/?workspace=renderers',
    i: 'L08',
    id: 'vfx-shader',
    jp: '特効',
    npm: '@call-me-sensei/toonlab/vfx',
    labStatus: 'inProgress',
    libraryStatus: 'migrationRequired',
    title: 'VFX Shader Lab',
  }),
  entry({
    artifact: 'Shader/style profile',
    desc: 'Water and liquid surface response, wave rendering, foam, reflection/refraction, absorption, caustics, underwater optics, shore presentation, and renderer quality independent of waterbody layout',
    group: 'look',
    href: '/water-lab/',
    i: 'L09',
    id: 'water',
    jp: '水面',
    npm: '@call-me-sensei/toonlab/water',
    labStatus: 'migrationRequired',
    libraryStatus: 'migrationRequired',
    title: 'Water & Liquid Shader Lab',
  }),
  entry({
    artifact: 'Shader/style profile',
    desc: 'Sky gradients, horizon, sun and moon discs, stars, scattering treatment, runtime visual layers, and renderer quality independent of current time, clouds, and atmospheric condition',
    group: 'look',
    href: '/sky-lab/',
    i: 'L10a',
    id: 'sky',
    jp: '天空',
    npm: '@call-me-sensei/toonlab/sky',
    labStatus: 'inProgress',
    libraryStatus: 'migrationRequired',
    title: 'Sky Shader Lab',
  }),
  entry({
    artifact: 'Shader/style profile',
    desc: 'Cloud layer composition, shape breakup, density, edge and underside treatment, lighting, motion response, shadows, quality tiers, and backend degradation independent of generated masks and current atmospheric condition',
    group: 'look',
    href: '/cloud-shader-lab/',
    i: 'L10b',
    id: 'cloud-shader',
    jp: '雲影',
    npm: '@call-me-sensei/toonlab/cloud',
    labStatus: 'inProgress',
    libraryStatus: 'migrationRequired',
    title: 'Cloud Shader Lab',
  }),
  entry({
    artifact: 'Shader/style profile',
    desc: 'Height and distance fog, aerial perspective, local fog volumes, god rays, haze, smoke volumes, and backend degradation',
    group: 'look',
    href: '/atmospheric-condition-lab/?workspace=atmosphere',
    i: 'L11',
    id: 'atmosphere',
    jp: '大気',
    npm: '@call-me-sensei/toonlab/atmosphere',
    labStatus: 'inProgress',
    libraryStatus: 'migrationRequired',
    title: 'Atmosphere, Fog & Volumetrics Lab',
  }),
  entry({
    artifact: 'Shader/style profile',
    desc: 'Rain, snow, hail and dust rendering plus shared wetness, puddle, snow, ice and dust surface-layer profiles; Snow Surface is consumed across Ground, Rock, Vegetation and Manufactured Surface while current accumulation remains in Weather System',
    group: 'look',
    href: '/weather-lab/',
    i: 'L12',
    id: 'weather',
    jp: '天候',
    npm: '@call-me-sensei/toonlab/weather',
    labStatus: 'inProgress',
    libraryStatus: 'inProgress',
    title: 'Weather Rendering & Surface Shader Lab',
  }),
  entry({
    artifact: 'Rendering style profile',
    desc: 'Sun, ambient, local rigs, light color and intensity, stylized shadows, cookies, many-light intent, day-cycle looks, and budgets',
    group: 'look',
    i: 'L13',
    id: 'lighting',
    jp: '照明',
    npm: '@call-me-sensei/toonlab/lighting',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Lighting & Shadow Lab',
  }),
  entry({
    artifact: 'Rendering style profile',
    desc: 'Color grade, tone mapping, exposure, bloom, depth cue, vignette, grain, palette control, LUTs, debug views, and quality tiers',
    group: 'look',
    i: 'L14',
    id: 'post',
    jp: '画調',
    npm: '@call-me-sensei/toonlab/post',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Post-processing & Color Lab',
  }),
  entry({
    artifact: 'Cross-domain rendering profile',
    desc: 'Object, material, inverted-hull, screen-space, crease, contact, and selective linework with distance and quality policy',
    group: 'look',
    i: 'L15',
    id: 'linework',
    jp: '線画',
    npm: '@call-me-sensei/toonlab/linework',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Linework & Outline Lab',
  }),
  entry({
    artifact: 'UI style profile',
    desc: 'Typography, panels, icons, HUD components, transitions, focus/readability, screen-space effects, accessibility states, and responsive scale',
    group: 'look',
    i: 'L16',
    id: 'ui-style',
    jp: '画面',
    npm: '@call-me-sensei/toonlab/ui',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'UI & HUD Style Lab',
  }),
]);

// ASSET CREATION & ASSEMBLY
// A noun does not automatically earn a procedural generator. Manufactured,
// architectural, character, and creature content starts from accepted
// high-quality base assets or modules and is assembled/adapted. Dedicated
// procedural generators remain only where the method can plausibly deliver
// production quality and useful controlled variation.
export const ASSET_CREATION_LABS_SHOWCASE = Object.freeze([
  entry({
    artifact: 'Assembly recipe',
    desc: 'Assemble accepted humanoid and creature bases with faces, hair/fur, wardrobe, accessories and variants; validate topology, semantic regions, fit, rig compatibility, LOD, collision, provenance, and export',
    group: 'asset',
    i: 'A01',
    id: 'character-assembly',
    jp: '人物',
    npm: '@call-me-sensei/toonlab/character-assets',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Character & Creature Assembly Lab',
  }),
  entry({
    artifact: 'Assembly recipe',
    desc: 'Build props, furniture, weapons, tools, vehicles and clutter from accepted high-quality modules using sockets, fit rules, semantic parts/materials, controlled variation, LOD, collision, provenance, and export',
    group: 'asset',
    i: 'A02',
    id: 'manufactured-assembly',
    jp: '組物',
    npm: '@call-me-sensei/toonlab/asset-assembly',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Manufactured Asset Assembly Lab',
  }),
  entry({
    artifact: 'Kit and assembly recipe',
    desc: 'Assemble accepted modular walls, floors, roofs, openings, stairs, facades, rooms and interiors using dimensional standards, snap rules, semantic surfaces, variants, collision, provenance, and export',
    group: 'asset',
    i: 'A03',
    id: 'architecture-kit',
    jp: '建築',
    npm: '@call-me-sensei/toonlab/architecture-kit',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Architecture & Interior Kit Assembly Lab',
  }),
  entry({
    artifact: 'Asset recipe',
    desc: 'Boulders, cliffs, outcrops, arches, caves, erosion, sculpt edits, neutral color/AO channels, LOD, collision, and export',
    group: 'asset',
    href: '/rock-lab/',
    i: 'A04',
    id: 'rock',
    jp: '岩石',
    npm: '@call-me-sensei/toonlab/rockgen',
    labStatus: 'migrationRequired',
    libraryStatus: 'migrationRequired',
    title: 'Rock & Cliff Generation Lab',
  }),
  entry({
    artifact: 'Asset recipe',
    desc: 'Trees, shrubs and hedges with trunks, branching, canopies, seasonal variants, semantic roles, wind data, LOD, and export',
    group: 'asset',
    href: '/tree-lab/',
    i: 'A05',
    id: 'tree',
    jp: '樹木',
    npm: '@call-me-sensei/toonlab/vegetation',
    labStatus: 'migrationRequired',
    libraryStatus: 'migrationRequired',
    title: 'Tree & Shrub Generation Lab',
  }),
  entry({
    artifact: 'Asset recipe',
    desc: 'Flowers, crops, reeds, vines and small plants with species recipes, stems, leaves, blooms, wind data, LOD, and export',
    group: 'asset',
    href: '/flower-lab/',
    i: 'A06',
    id: 'flower',
    jp: '草花',
    npm: '@call-me-sensei/toonlab/vegetation',
    labStatus: 'migrationRequired',
    libraryStatus: 'migrationRequired',
    title: 'Flower & Plant Generation Lab',
  }),
  entry({
    artifact: 'Asset recipe',
    desc: 'Grass and groundcover blade geometry, clumps, planting data, bend/motion data, gameplay interaction, LOD, and export',
    group: 'asset',
    href: '/grass-lab/',
    i: 'A07',
    id: 'grass',
    jp: '下草',
    npm: '@call-me-sensei/toonlab/vegetation',
    labStatus: 'migrationRequired',
    libraryStatus: 'migrationRequired',
    title: 'Grass & Groundcover Generation Lab',
  }),
  entry({
    artifact: 'Asset recipe',
    desc: 'Roads, trails, rails, sidewalks, stairs, tunnels, bridges, intersections, markings, splines, collision, and terrain interfaces',
    group: 'asset',
    i: 'A08',
    id: 'path',
    jp: '道路',
    npm: '@call-me-sensei/toonlab/pathgen',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Road, Path & Bridge Generation Lab',
  }),
  entry({
    artifact: 'Asset recipe',
    desc: 'Deterministic seamless color, normal, roughness, metalness, emission, height, mask and noise maps with portable recipes and export',
    group: 'asset',
    href: '/texture-lab/',
    i: 'A09',
    id: 'texture',
    jp: '質感',
    npm: '@call-me-sensei/toonlab/texgen',
    labStatus: 'migrationRequired',
    libraryStatus: 'migrationRequired',
    title: 'Texture & Material Map Generation Lab',
  }),
  entry({
    artifact: 'Source-asset recipe',
    desc: 'Generate and curate sky-gradient and scattering LUTs, cloud masks, layer maps, noises, volume tiles, fog fields, and god-ray inputs independently of the shaders and atmospheric conditions that consume them',
    group: 'asset',
    i: 'A09b',
    id: 'sky-atmosphere-source',
    jp: '空素材',
    npm: '@call-me-sensei/toonlab/atmosphere-assets',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Sky, Cloud & Atmosphere Source Asset Lab',
  }),
  entry({
    artifact: 'Asset recipe',
    desc: 'Signs, labels, posters, markings, graffiti, damage, grime, footprints, sprites, icons and atlases with masks and license metadata',
    group: 'asset',
    i: 'A10',
    id: 'graphic-generation',
    jp: '図案',
    npm: '@call-me-sensei/toonlab/graphicgen',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Decal, Signage & Graphic Generation Lab',
  }),
  entry({
    artifact: 'Asset recipe',
    desc: 'Flipbooks, sprites, signed-distance fields, vector fields, procedural noises, trail profiles and effect meshes independent of effect timing',
    group: 'asset',
    i: 'A11',
    id: 'vfx-source-generation',
    jp: '素効',
    npm: '@call-me-sensei/toonlab/vfx-assets',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'VFX Source Asset Generation Lab',
  }),
  entry({
    artifact: 'Audio source asset',
    desc: 'Record, import, synthesize, generate and edit reusable one-shots, loops, impulses and stems with clean loop points, loudness, metadata, provenance, and export independent of gameplay cue logic',
    group: 'asset',
    i: 'A12',
    id: 'audio-source',
    jp: '音源',
    npm: '@call-me-sensei/toonlab/audio-assets',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Audio Source Asset Lab',
  }),
]);

// MOTION & PERFORMANCE
export const MOTION_PERFORMANCE_LABS_SHOWCASE = Object.freeze([
  entry({
    artifact: 'Rig document',
    desc: 'Skeleton creation, control rig, skin weights, IK chains, sockets, constraints, twist handling, deformation tests, and export',
    group: 'motion',
    i: 'M01',
    id: 'rigging',
    jp: '骨組',
    npm: '@call-me-sensei/toonlab/rigging',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Rigging & Skinning Lab',
  }),
  entry({
    artifact: 'Retarget profile',
    desc: 'Skeleton mapping, proportions, root motion, contact preservation, foot locking, cleanup, compression, and compatibility audit',
    group: 'motion',
    i: 'M02',
    id: 'retargeting',
    jp: '転写',
    npm: '@call-me-sensei/toonlab/retargeting',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Animation Retargeting & Cleanup Lab',
  }),
  entry({
    artifact: 'Animation clip',
    desc: 'Author, generate, edit and validate reusable clips, poses, contacts, root motion, curves, events, looping, compression, style cadence, and export independent of runtime state logic',
    group: 'motion',
    i: 'M03',
    id: 'animation-clips',
    jp: '動作',
    npm: '@call-me-sensei/toonlab/motion',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Animation Clip Authoring & Generation Lab',
  }),
  entry({
    artifact: 'Motion-system recipe',
    desc: 'Blend spaces, state graphs, layers, masks, procedural operators, locomotion, action slots, root-motion policy, events, stepped cadence, and runtime style variants',
    group: 'motion',
    i: 'M04',
    id: 'motion',
    jp: '運動',
    npm: '@call-me-sensei/toonlab/motion',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Motion System Lab',
  }),
  entry({
    artifact: 'Performance profile',
    desc: 'Expressions, facial poses, look-at, blink, visemes, lip-sync timing, emotion layers, dialogue tracks, and cross-character mapping',
    group: 'motion',
    i: 'M05',
    id: 'facial-performance',
    jp: '表情',
    npm: '@call-me-sensei/toonlab/performance',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Facial Performance & Lip-sync Lab',
  }),
  entry({
    artifact: 'Simulation profile',
    desc: 'Hair, cloth, capes, tails, ears, accessories, springs, constraints, wind response, collision, deterministic playback, and quality tiers',
    group: 'motion',
    i: 'M06',
    id: 'secondary-motion',
    jp: '揺物',
    npm: '@call-me-sensei/toonlab/secondary-motion',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Secondary Motion Lab',
  }),
  entry({
    artifact: 'Camera recipe',
    desc: 'Framing, follow/orbit, lenses, collision, damping, procedural motion, impulses, blends, rails, shot presets, and director behavior',
    group: 'motion',
    i: 'M07',
    id: 'camera',
    jp: '撮影',
    npm: '@call-me-sensei/toonlab/camera',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Camera & Shot Lab',
  }),
  entry({
    artifact: 'Timeline document',
    desc: 'Cutscene tracks for cameras, actors, animation, facial performance, VFX, SFX, music, dialogue, lighting, weather, subtitles, and events',
    group: 'motion',
    i: 'M08',
    id: 'sequencer',
    jp: '演出',
    npm: '@call-me-sensei/toonlab/sequencer',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Cinematic Sequencer Lab',
  }),
]);

// EFFECTS & AUDIO
export const EFFECTS_AUDIO_LABS_SHOWCASE = Object.freeze([
  entry({
    artifact: 'Effect graph',
    desc: 'Emitter graphs, particles, ribbons, trails, beams, decals, meshes, forces, collisions, events, timing, pooling, quality, and gameplay preview',
    group: 'effectsAudio',
    href: '/vfx-lab/',
    i: 'E01',
    id: 'vfx',
    jp: '視効',
    npm: '@call-me-sensei/toonlab/vfxgen',
    labStatus: 'inProgress',
    libraryStatus: 'migrationRequired',
    title: 'VFX Effect Lab',
  }),
  entry({
    artifact: 'World-effect recipe',
    desc: 'Leaves, petals, fireflies, pollen, motes, mist, local volumes, world-following regions, time/weather gates, wind, pooling, and budgets',
    group: 'effectsAudio',
    i: 'E02',
    id: 'ambient-system',
    jp: '気配',
    npm: '@call-me-sensei/toonlab/ambientfx',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Ambient VFX Lab',
  }),
  entry({
    artifact: 'Feedback recipe',
    desc: 'One event graph coordinating VFX, SFX, camera impulses, hit-stop, time scale, flashes, UI, haptics, concurrency, and accessibility',
    group: 'effectsAudio',
    i: 'E03',
    id: 'game-feel',
    jp: '手応',
    npm: '@call-me-sensei/toonlab/game-feel',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Game Feel & Feedback Lab',
  }),
  entry({
    artifact: 'Sound cue / DSP recipe',
    desc: 'Assemble source audio into gameplay SFX with layers, randomization, envelopes, filters, pitch/volume variation, surface sets, loops, procedural DSP, gameplay parameters, concurrency, and preview',
    group: 'effectsAudio',
    i: 'E04',
    id: 'sfx',
    jp: '音効',
    npm: '@call-me-sensei/toonlab/sfx',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'SFX Cue & Sound Design Lab',
  }),
  entry({
    artifact: 'Mix and spatial profile',
    desc: 'Buses, loudness, dynamics, EQ, reverb, attenuation, spatialization, occlusion, priorities, concurrency, platform output, and accessibility',
    group: 'effectsAudio',
    i: 'E05',
    id: 'audio-mix',
    jp: '音響',
    npm: '@call-me-sensei/toonlab/audio',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Spatial Audio & Mix Lab',
  }),
  entry({
    artifact: 'Soundscape recipe',
    desc: 'Ambient beds, spot emitters, zones, portals, transitions, time/weather/biome response, randomization, streaming, and voice budgets',
    group: 'effectsAudio',
    i: 'E06',
    id: 'soundscape',
    jp: '音景',
    npm: '@call-me-sensei/toonlab/soundscape',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Soundscape Lab',
  }),
  entry({
    artifact: 'Adaptive score',
    desc: 'Music stems, sections, transitions, tempo, intensity, gameplay states, stingers, looping, synchronization, mixing, and rights metadata',
    group: 'effectsAudio',
    i: 'E07',
    id: 'music',
    jp: '楽曲',
    npm: '@call-me-sensei/toonlab/music',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Music & Adaptive Score Lab',
  }),
  entry({
    artifact: 'Dialogue performance document',
    desc: 'Voice assets, casting metadata, line variants, pronunciation, timing, localization, subtitles, lip-sync linkage, spatial playback, and consent/provenance',
    group: 'effectsAudio',
    i: 'E08',
    id: 'dialogue',
    jp: '台詞',
    npm: '@call-me-sensei/toonlab/dialogue',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Voice, Dialogue & Subtitle Lab',
  }),
]);

// WORLD BUILDING & SIMULATION
export const WORLD_BUILDING_LABS_SHOWCASE = Object.freeze([
  entry({
    artifact: 'Landscape project',
    desc: 'Terrain sculpting and generation, holes, splats, foliage paint, tunnels, groundwater, world scale, materials, collision, and export',
    group: 'world',
    href: '/landscape-lab/',
    i: 'W01',
    id: 'landscape',
    jp: '地形',
    npm: '@call-me-sensei/toonlab/landscape',
    labStatus: 'migrationRequired',
    libraryStatus: 'migrationRequired',
    title: 'Landscape & Terrain Authoring Lab',
  }),
  entry({
    artifact: 'Hydrology project',
    desc: 'Rivers, lakes, ponds, coasts, waterfalls, drainage, shorelines, flow fields, beds, crossings, water-body routing, and terrain carving',
    group: 'world',
    i: 'W02',
    id: 'hydrology',
    jp: '水系',
    npm: '@call-me-sensei/toonlab/hydrology',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Hydrology & Waterbody Lab',
  }),
  entry({
    artifact: 'Population recipe',
    desc: 'Biome layers, masks, density, exclusions, succession, cross-family scatter, terrain/weather rules, deterministic placement, LOD, and budgets',
    group: 'world',
    i: 'W03',
    id: 'biome',
    jp: '生態',
    npm: '@call-me-sensei/toonlab/biome',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Biome & Scatter Lab',
  }),
  entry({
    artifact: 'World-layout recipe',
    desc: 'Villages, towns and cities with districts, roads, lots, landmarks, building mixes, utilities, population anchors, and deterministic growth',
    group: 'world',
    i: 'W04',
    id: 'village',
    jp: '集落',
    npm: '@call-me-sensei/toonlab/villagegen',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Settlement & City Generation Lab',
  }),
  entry({
    artifact: 'Level-layout recipe',
    desc: 'Rooms, corridors, floors, dungeons, encounter spaces, portals, vertical circulation, visibility, modular-kit sockets, and navigation constraints',
    group: 'world',
    i: 'W05',
    id: 'level-layout',
    jp: '間取',
    npm: '@call-me-sensei/toonlab/levelgen',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Interior & Level Layout Lab',
  }),
  entry({
    artifact: 'Scene document',
    desc: 'Composition, set dressing, focal hierarchy, landmarks, prop placement, layers, variants, semantic zones, cameras, lighting scenarios, and export',
    group: 'world',
    i: 'W06',
    id: 'scene-composition',
    jp: '構景',
    npm: '@call-me-sensei/toonlab/scene',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Scene Composition & Set Dressing Lab',
  }),
  entry({
    artifact: 'Environment timeline',
    desc: 'Seasons, time of day, astronomical cycle, atmospheric-condition distributions, biome baselines, long-running transitions, overrides, and deterministic playback',
    group: 'world',
    i: 'W07',
    id: 'climate',
    jp: '気候',
    npm: '@call-me-sensei/toonlab/climate',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Climate, Seasons & Time Lab',
  }),
  entry({
    artifact: 'Atmospheric-condition recipe',
    desc: 'Author reusable air, cloud-ceiling, fog, precipitation, lighting, electrical, and flow state. The current fifteen-profile collection is the Call Me Sensei set; shader styles and generated source assets remain independent',
    group: 'world',
    href: '/atmospheric-condition-lab/',
    i: 'W08',
    id: 'atmospheric-condition',
    jp: '天変',
    npm: '@call-me-sensei/toonlab/atmospheric-condition',
    labStatus: 'inProgress',
    libraryStatus: 'inProgress',
    title: 'Atmospheric Condition Lab',
  }),
  entry({
    artifact: 'Population recipe',
    desc: 'Wildlife, crowds, schools, flocks and ambient agents with habitats, schedules, reactions, variants, animation, avoidance, spawning, and budgets',
    group: 'world',
    i: 'W09',
    id: 'fauna-system',
    jp: '群衆',
    npm: '@call-me-sensei/toonlab/fauna',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Fauna & Crowd Population Lab',
  }),
  entry({
    artifact: 'Simulation profile',
    desc: 'Rigid bodies, joints, ragdolls, breakage, fracture recipes, debris, impulses, buoyancy, collision layers, determinism, and quality budgets',
    group: 'world',
    i: 'W10',
    id: 'physics-destruction',
    jp: '物理',
    npm: '@call-me-sensei/toonlab/physics',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Physics, Ragdoll & Destruction Lab',
  }),
  entry({
    artifact: 'Traversal contract',
    desc: 'Walkable surfaces, navigation meshes/graphs, links, blockers, doors, ladders, climbs, moving platforms, interaction anchors, and validation',
    group: 'world',
    i: 'W11',
    id: 'navigation',
    jp: '移動',
    npm: '@call-me-sensei/toonlab/navigation',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Navigation, Traversal & Interaction Lab',
  }),
  entry({
    artifact: 'Streaming and visibility profile',
    desc: 'World partitioning, cells, portals, occlusion, impostors, streaming priorities, memory residency, distance bands, and deterministic handoff',
    group: 'world',
    i: 'W12',
    id: 'world-streaming',
    jp: '配信',
    npm: '@call-me-sensei/toonlab/world-streaming',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'World Streaming & Visibility Lab',
  }),
]);

// PIPELINE & SHIPPING
export const PIPELINE_LABS_SHOWCASE = Object.freeze([
  entry({
    artifact: 'Style bundle',
    desc: 'Compose, validate, compare, import and export every look, motion, UI and audio style owner as one local OSS bundle without a database',
    group: 'pipeline',
    i: 'P01',
    id: 'style-bundle',
    jp: '統一',
    npm: '@call-me-sensei/toonlab/styles',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Style Bundle Lab',
  }),
  entry({
    artifact: 'Accepted source record',
    desc: 'Search procedural entries and accepted CC0/CC-BY models, textures, audio, animation and graphics with provenance, attribution, and usage rights',
    group: 'pipeline',
    href: '/gallery/',
    i: 'P02',
    id: 'gallery',
    jp: '素材',
    npm: '@call-me-sensei/toonlab/assetlib',
    labStatus: 'migrationRequired',
    libraryStatus: 'migrationRequired',
    title: 'Asset Gallery & License Lab',
  }),
  entry({
    artifact: 'Normalized asset manifest',
    desc: 'Import models, textures, audio and animation; normalize scale/axes/maps; inspect quality; assign semantic labels; and record license/provenance',
    group: 'pipeline',
    href: '/asset-lab/',
    i: 'P03',
    id: 'asset-lab',
    jp: '取込',
    npm: '@call-me-sensei/toonlab/assetlib',
    labStatus: 'migrationRequired',
    libraryStatus: 'migrationRequired',
    title: 'Asset Import, Normalize & Label Lab',
  }),
  entry({
    artifact: 'Routing and compatibility manifest',
    desc: 'Route every material/part to its owner, audit masks and exceptions, preview fallbacks, flatten incompatible realism, and report unsupported content',
    group: 'pipeline',
    href: '/environment-lab/',
    i: 'P04',
    id: 'routing-audit',
    jp: '監査',
    npm: '@call-me-sensei/toonlab/styles',
    labStatus: 'migrationRequired',
    libraryStatus: 'migrationRequired',
    title: 'Material Routing, Compatibility & Audit Lab',
  }),
  entry({
    artifact: 'Reconstruction recipe',
    desc: 'Image-to-3D, multi-view reconstruction, cleanup, scale recovery, topology, UV/material recovery, semantic labeling, provenance, and export',
    group: 'pipeline',
    i: 'P05',
    id: 'reconstruction',
    jp: '復元',
    npm: '@call-me-sensei/toonlab/reconstruction',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Image-to-3D & Reconstruction Lab',
  }),
  entry({
    artifact: 'Generator base family',
    desc: 'Turn accepted first-party or open assets into canonical procedural base sets, parameter ranges, semantic parts, tests, variants, and quality envelopes',
    group: 'pipeline',
    i: 'P06',
    id: 'base-set',
    jp: '原型',
    npm: '@call-me-sensei/toonlab/generation',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Procedural Base Set & Variation Lab',
  }),
  entry({
    artifact: 'Coverage manifest',
    desc: 'Track scene roles across generators and accepted assets, licenses, style readiness, quality tiers and gaps before generation or sourcing',
    group: 'pipeline',
    i: 'P07',
    id: 'scene-kit-coverage',
    jp: '網羅',
    npm: '@call-me-sensei/toonlab/catalog',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Scene Kit Coverage Lab',
  }),
  entry({
    artifact: 'Quality profile',
    desc: 'Triangle, draw, shader, texture, particle, animation, audio, memory and CPU/GPU budgets with LOD/impostor planning and device tiers',
    group: 'pipeline',
    i: 'P08',
    id: 'quality-performance',
    jp: '性能',
    npm: '@call-me-sensei/toonlab/quality',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Quality, LOD & Performance Lab',
  }),
  entry({
    artifact: 'Build recipe',
    desc: 'Bake textures/lighting/data, optimize and merge, compress, generate LOD/collision, package dependencies, export GLB/bundles, and verify re-import',
    group: 'pipeline',
    i: 'P09',
    id: 'bake-export',
    jp: '出力',
    npm: '@call-me-sensei/toonlab/export',
    labStatus: 'notStarted',
    libraryStatus: 'notStarted',
    title: 'Bake, Optimize & Export Lab',
  }),
  entry({
    artifact: 'Composition audit',
    desc: 'Exercise complete style bundles across difficult assets, scenes, lighting, weather, distance, motion, VFX, audio and device fallbacks with actionable diffs',
    group: 'pipeline',
    i: 'P10',
    id: 'regression',
    jp: '回帰',
    npm: '@call-me-sensei/toonlab/debug',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Reference, Regression & Composition Lab',
  }),
  entry({
    artifact: 'Release manifest',
    desc: 'Verify public schemas, migrations, exports, tree shaking, licenses, generated references, bundles, examples, semver, package contents, and npm readiness',
    group: 'pipeline',
    i: 'P11',
    id: 'release',
    jp: '公開',
    npm: '@call-me-sensei/toonlab',
    labStatus: 'notStarted',
    libraryStatus: 'migrationRequired',
    title: 'Package & Release Lab',
  }),
]);

const SHADER_LAB_IDS = new Set([
  'shader',
  'tree-shader',
  'grass-shader',
  'flower-shader',
  'rock-shader',
  'terrain-shader',
  'manufactured-material',
  'transparent-shader',
  'decal-shader',
  'vfx-shader',
  'water',
  'sky',
  'cloud-shader',
  'atmosphere',
  'weather',
]);

export const SHADER_LABS_SHOWCASE = Object.freeze(
  LOOK_DEVELOPMENT_LABS_SHOWCASE.filter((lab) => SHADER_LAB_IDS.has(lab.id)),
);
export const RENDERING_STYLE_LABS_SHOWCASE = Object.freeze(
  LOOK_DEVELOPMENT_LABS_SHOWCASE.filter((lab) => !SHADER_LAB_IDS.has(lab.id)),
);

// Compatibility aliases for existing consumers. New code should use the six
// definitive product families and the explicit shader/rendering subsets.
export const MATERIAL_SHADER_LABS_SHOWCASE = Object.freeze(
  SHADER_LABS_SHOWCASE.filter((lab) => lab.artifact === 'Material profile'),
);
export const VISUAL_SYSTEM_LABS_SHOWCASE = RENDERING_STYLE_LABS_SHOWCASE;
export const ASSET_GENERATION_LABS_SHOWCASE = ASSET_CREATION_LABS_SHOWCASE;
export const ASSET_LABS_SHOWCASE = ASSET_CREATION_LABS_SHOWCASE;
export const WORLD_SYSTEMS_SHOWCASE = WORLD_BUILDING_LABS_SHOWCASE;
export const RUNTIME_SYSTEM_LABS_SHOWCASE = WORLD_BUILDING_LABS_SHOWCASE;
export const LOOK_LABS_SHOWCASE = LOOK_DEVELOPMENT_LABS_SHOWCASE;

export const LABS_SHOWCASE = Object.freeze([
  ...LOOK_DEVELOPMENT_LABS_SHOWCASE,
  ...ASSET_CREATION_LABS_SHOWCASE,
  ...MOTION_PERFORMANCE_LABS_SHOWCASE,
  ...EFFECTS_AUDIO_LABS_SHOWCASE,
  ...WORLD_BUILDING_LABS_SHOWCASE,
  ...PIPELINE_LABS_SHOWCASE,
]);

export const DEMOS_SHOWCASE = Object.freeze([
  entry({
    artifact: 'Validation scene',
    desc: 'Walk a character through the composed stylized systems',
    group: 'validation',
    href: '/playground/',
    i: 'V01',
    id: 'playground',
    jp: '遊場',
    npm: 'Integration only',
    labStatus: 'validation',
    libraryStatus: 'notApplicable',
    title: 'Character & Interaction Playground',
  }),
  entry({
    artifact: 'Validation scene',
    desc: 'Wade, swim, dive, splash, and validate water interaction in play',
    group: 'validation',
    href: '/playground/?scene=water',
    i: 'V02',
    id: 'water-playground',
    jp: '渚',
    npm: 'Integration only',
    labStatus: 'validation',
    libraryStatus: 'notApplicable',
    title: 'Water Playground',
  }),
  entry({
    artifact: 'Validation scene',
    desc: 'Validate paths, bridges, settlements, terrain, lighting, water, vegetation, streaming scale, and navigation',
    group: 'validation',
    href: '/examples/outdoor-world/?villages=2&shrines=1',
    i: 'V03',
    id: 'outdoor-world',
    jp: '世界',
    npm: 'Integration only',
    labStatus: 'validation',
    libraryStatus: 'notApplicable',
    title: 'Outdoor World',
  }),
  entry({
    artifact: 'Validation scene',
    desc: 'Validate combat effects, readability, timing, feedback, post, and performance in a walkable arena',
    group: 'validation',
    href: '/examples/vfx-arena/',
    i: 'V04',
    id: 'vfx-arena',
    jp: '闘技',
    npm: 'Integration only',
    labStatus: 'validation',
    libraryStatus: 'notApplicable',
    title: 'VFX & Game Feel Arena',
  }),
  entry({
    artifact: 'Validation scene',
    desc: 'Validate wildlife populations, variants, animation, movement, habitat rules, and budgets in a gameplay biome',
    group: 'validation',
    href: '/examples/fauna-demo/',
    i: 'V05',
    id: 'fauna',
    jp: '動物',
    npm: 'Integration only',
    labStatus: 'validation',
    libraryStatus: 'notApplicable',
    title: 'Fauna & Population Demo',
  }),
  entry({
    artifact: 'Validation scene',
    desc: 'Validate fireflies, motes, falling leaves, petals, pollen, mist, gates, weather response, and budgets in context',
    group: 'validation',
    href: '/examples/ambientfx-demo/',
    i: 'V06',
    id: 'ambientfx',
    jp: '気配',
    npm: 'Integration only',
    labStatus: 'validation',
    libraryStatus: 'notApplicable',
    title: 'Ambient VFX Demo',
  }),
]);
