// Source inference fallback: public names retained with permissive signatures.
export const CLOUD_DEEP_CONTRIBUTION: any;
export const CLOUD_DEEP_EXTINCTION_SCALE: any;
export const CLOUD_GROUND_HEMISPHERE_FRACTION: any;
export const CLOUD_MOON_RIM_PATH: any;
export const CLOUD_MULTISCATTER_ECCENTRICITY: any;
export const CLOUD_MULTISCATTER_EXTINCTION: any;
export const CLOUD_MULTISCATTER_SCATTER: any;
export const CLOUD_PHASE_BACKWARD_G: any;
export const CLOUD_PHASE_BASE_G: any;
export const CLOUD_PHASE_BLEND: any;
export const CLOUD_PHASE_FORWARD_G: any;
export const CLOUD_PHASE_SILVER_INTENSITY: any;
export const CLOUD_PHASE_SILVER_SPREAD: any;
export const CLOUD_POWDER_EXPONENT: any;
export function applyCloudBlueShadowNode(...args: any[]): any;
export function applyCloudInnerPaintNode(...args: any[]): any;
export function applyCloudLightBlendNode(...args: any[]): any;
export function applyCloudShadowWashNode(...args: any[]): any;
export function applyCloudStyleNode(...args: any[]): any;
export function applyCloudTimePaletteNode(...args: any[]): any;
export function applyCloudToneNode(...args: any[]): any;
export function applyCloudTopLightNode(...args: any[]): any;
export function applyCloudWhiteTopNode(...args: any[]): any;
export function beerLambertNode(...args: any[]): any;
export function cloudAmbientNode(...args: any[]): any;
export function cloudBaseShadowNode(...args: any[]): any;
export function cloudDirectionalAttenuationNode(...args: any[]): any;
export function cloudDirectionalScatteringNode(...args: any[]): any;
export function cloudGroundBounceNode(...args: any[]): any;
export function cloudGroundRadianceNode(...args: any[]): any;
export function cloudMoonDirectionalNode(...args: any[]): any;
export function cloudMoonRimNode(...args: any[]): any;
export function cloudPhaseNode(...args: any[]): any;
export function cloudSkyAmbientNode(...args: any[]): any;
export function cloudSunTransmittanceNode(...args: any[]): any;
export function createCloudLightingModel(...args: any[]): any;
export function powderNode(...args: any[]): any;
