// Source inference fallback: public names retained with permissive signatures.
export const CLOUD_BASE_CHANNEL_STRENGTHS: any;
export const CLOUD_BASE_STEP_SIZE: any;
export const CLOUD_COARSE_STEP_SCALE: any;
export const CLOUD_CORE_STEP_MIN_SCALE: any;
export const CLOUD_CUMULUS_HEIGHT_GRADIENT: any;
export const CLOUD_CURL_STRENGTH_FRACTION: any;
export const CLOUD_DECK_ALTITUDE_OFFSET: any;
export const CLOUD_DECK_EXTINCTION: any;
export const CLOUD_DECK_LIGHT_DEPTH: any;
export const CLOUD_DECK_MAX_SLANT: any;
export const CLOUD_DECK_MIN_COS: any;
export const CLOUD_DENSITY_EPSILON: any;
export const CLOUD_EROSION_CARVE_SCALE: any;
export const CLOUD_EROSION_CHANNEL_STRENGTHS: any;
export const CLOUD_EROSION_MIN_SCALE: any;
export const CLOUD_EROSION_WISP_HEIGHT: any;
export const CLOUD_FINE_EMPTY_LIMIT: any;
export const CLOUD_INTERIOR_COARSEN_FULL: any;
export const CLOUD_INTERIOR_COARSEN_START: any;
export const CLOUD_INTERIOR_STEP_SCALE: any;
export const CLOUD_LIGHT_CONE_OFFSETS: any;
export const CLOUD_LIGHT_CONE_SPREAD: any;
export const CLOUD_LIGHT_MARCH_GROWTH: any;
export const CLOUD_LIGHT_MARCH_LENGTH_FRACTION: any;
export const CLOUD_LIGHT_STEP_SIZE: any;
export const CLOUD_MAX_OPTICAL_DEPTH_PER_STEP: any;
export const CLOUD_PLANET_RADIUS: any;
export const CLOUD_STEP_CONE_FACTOR: any;
export const CLOUD_STRATOCUMULUS_HEIGHT_GRADIENT: any;
export const CLOUD_STRATUS_HEIGHT_GRADIENT: any;
export const CLOUD_SURFACE_LIGHT_MIN_WEIGHT: any;
export const CLOUD_SURFACE_NORMAL_RADIUS: any;
export const CLOUD_TRANSMITTANCE_EPSILON: any;
export const CLOUD_WEATHER_CARVE_WIDTH: any;
export const CLOUD_WHITE_TOP_DEPTH_SCALE: any;
export const CLOUD_WHITE_TOP_HEIGHT_GAIN: any;
export const CLOUD_WHITE_TOP_MIN_SUN_REACH: any;
export function createCloudDensityField(...args: any[]): any;
export function createCloudVolumeMaterial(...args: any[]): any;
export function findCloudLayerCrossing(...args: any[]): any;
export function intersectCloudShell(...args: any[]): any;
export function marchCloud(...args: any[]): any;
