// Source inference fallback: public names retained with permissive signatures.
export const APPROVED_CATALOG_SPDX_LICENSES: any;
export const ASSET_GAP_DOCUMENT_TYPE: any;
export const ASSET_GAP_SCHEMA_VERSION: any;
export const ASSET_POLICY_MODES: any;
export const ASSET_SOURCE_CLASSES: any;
export const ASSET_SOURCING_POLICY_DOCUMENT_TYPE: any;
export const ASSET_SOURCING_POLICY_SCHEMA_VERSION: any;
export const ATMOSPHERE_MEDIUM: any;
export const ATMOSPHERE_PARAM_KEYS: any;
export const ATMOSPHERE_PARAM_SCHEMA: any;
export const ATMOSPHERE_REBAKE_KEYS: any;
export class AtmosphereSky { constructor(...args: any[]); [key: string]: any; }
export const BARK_SHADER: any;
export const BASE_TEXTURE_MATERIAL_COLOR_MODES: any;
export const BASE_TEXTURE_SATURATION_MODES: any;
export const BEACH_DIRECTION_SPREAD: any;
export const BEACH_RUNUP_DISTANCE: any;
export const BEACH_WATER_LEVEL: any;
export const BEACH_WAVE_SPEED: any;
export const BRANCH_TREE_DOCUMENT_TYPE: any;
export const BRANCH_TREE_DOCUMENT_VERSION: any;
export const BRANCH_TREE_LEAF_SHAPES: any;
export const BUILT_IN_STYLE_ADAPTERS: any;
export class BranchTree { constructor(...args: any[]); [key: string]: any; }
export const CALL_ME_SENSEI_GRASS_CLUMP_VARIANTS: any;
export const CALL_ME_SENSEI_GRASS_MATERIAL_TEXTURE_URLS: any;
export const CALL_ME_SENSEI_GRASS_PROVENANCE: any;
export const CALL_ME_SENSEI_GROUND_SHADER_SETTINGS: any;
export const CALL_ME_SENSEI_LIGHTING_CONTRACT: any;
export const CALL_ME_SENSEI_ROCK_SHADER_SETTINGS: any;
export const CALL_ME_SENSEI_SKY_ATMOSPHERE: any;
export const CALL_ME_SENSEI_SKY_SHADER_SETTINGS: any;
export const CALL_ME_SENSEI_SKY_TIME_KEYFRAMES: any;
export const CALL_ME_SENSEI_STRICT_ASSET_POLICY: any;
export const CALL_ME_SENSEI_STYLE_BUNDLE: any;
export const CALL_ME_SENSEI_STYLE_SLOT_IDS: any;
export const CEL_SHADE_PRESETS: any;
export const CHARACTER_RUNTIME_STAGE: any;
export const CLOUD_AMORTIZATION_BLOCK: any;
export const CLOUD_BASE_CHANNEL_STRENGTHS: any;
export const CLOUD_BASE_SHAPE_EROSION_WEIGHTS: any;
export const CLOUD_BASE_SHAPE_MASTER_DIM: any;
export const CLOUD_BASE_SHAPE_MIN_DIM: any;
export const CLOUD_BASE_SHAPE_PLAN: any;
export const CLOUD_BASE_SHAPE_SEED_NAMESPACE: any;
export const CLOUD_BASE_STEP_SIZE: any;
export const CLOUD_CIRRUS_MAP_HEIGHT: any;
export const CLOUD_CIRRUS_MAP_WIDTH: any;
export const CLOUD_CIRRUS_SEED_NAMESPACE: any;
export const CLOUD_COARSE_STEP_SCALE: any;
export const CLOUD_CORE_STEP_MIN_SCALE: any;
export const CLOUD_CUMULUS_HEIGHT_GRADIENT: any;
export const CLOUD_CURL_STRENGTH_FRACTION: any;
export const CLOUD_DECK_ALTITUDE_OFFSET: any;
export const CLOUD_DECK_EXTINCTION: any;
export const CLOUD_DECK_LIGHT_DEPTH: any;
export const CLOUD_DECK_MAX_SLANT: any;
export const CLOUD_DECK_MIN_COS: any;
export const CLOUD_DEEP_CONTRIBUTION: any;
export const CLOUD_DEEP_EXTINCTION_SCALE: any;
export const CLOUD_DENSITY_EPSILON: any;
export const CLOUD_EROSION_CARVE_SCALE: any;
export const CLOUD_EROSION_CHANNEL_STRENGTHS: any;
export const CLOUD_EROSION_DEFAULT_DIMS: any;
export const CLOUD_EROSION_DETAIL_WEIGHTS: any;
export const CLOUD_EROSION_MIN_SCALE: any;
export const CLOUD_EROSION_PLAN: any;
export const CLOUD_EROSION_SEED_NAMESPACE: any;
export const CLOUD_EROSION_WISP_HEIGHT: any;
export const CLOUD_EVOLUTION_AXIS: any;
export const CLOUD_FINE_EMPTY_LIMIT: any;
export const CLOUD_GROUND_HEMISPHERE_FRACTION: any;
export const CLOUD_HISTORY_CLAMP_RADIUS: any;
export const CLOUD_HISTORY_CUT_COSINE: any;
export const CLOUD_HISTORY_CUT_DISTANCE: any;
export const CLOUD_HISTORY_FAR_DEPTH: any;
export const CLOUD_HISTORY_FRESH_BLEND: any;
export const CLOUD_HISTORY_STALE_BLEND: any;
export const CLOUD_HISTORY_WARMUP_FRAMES: any;
export const CLOUD_HIT_DISTANCE_MAX: any;
export const CLOUD_HIT_DISTANCE_MISS: any;
export const CLOUD_HIT_DISTANCE_MISS_THRESHOLD: any;
export const CLOUD_INTERIOR_COARSEN_FULL: any;
export const CLOUD_INTERIOR_COARSEN_START: any;
export const CLOUD_INTERIOR_STEP_SCALE: any;
export const CLOUD_LIGHT_CONE_OFFSETS: any;
export const CLOUD_LIGHT_CONE_SPREAD: any;
export const CLOUD_LIGHT_MARCH_GROWTH: any;
export const CLOUD_LIGHT_MARCH_LENGTH_FRACTION: any;
export const CLOUD_LIGHT_MARCH_STEPS: any;
export const CLOUD_LIGHT_STEP_SIZE: any;
export const CLOUD_MARCH_BUDGET: any;
export const CLOUD_MAX_OPTICAL_DEPTH_PER_STEP: any;
export const CLOUD_MOON_RIM_PATH: any;
export const CLOUD_MULTISCATTER_ECCENTRICITY: any;
export const CLOUD_MULTISCATTER_EXTINCTION: any;
export const CLOUD_MULTISCATTER_SCATTER: any;
export const CLOUD_PARAMS_FIELD_SCHEMA: any;
export const CLOUD_PARAM_GROUPS: any;
export const CLOUD_PARAM_GROUP_IDS: any;
export const CLOUD_PHASE_BACKWARD_G: any;
export const CLOUD_PHASE_BASE_G: any;
export const CLOUD_PHASE_BLEND: any;
export const CLOUD_PHASE_FORWARD_G: any;
export const CLOUD_PHASE_SILVER_INTENSITY: any;
export const CLOUD_PHASE_SILVER_SPREAD: any;
export const CLOUD_PLANET_RADIUS: any;
export const CLOUD_POWDER_EXPONENT: any;
export const CLOUD_PRIMARY_MARCH_STEPS: any;
export const CLOUD_STEP_CONE_FACTOR: any;
export const CLOUD_STRATOCUMULUS_HEIGHT_GRADIENT: any;
export const CLOUD_STRATUS_HEIGHT_GRADIENT: any;
export const CLOUD_STYLE_FIELD_SCHEMA: any;
export const CLOUD_STYLE_MODULE_IDS: any;
export const CLOUD_STYLE_SNAPSHOTS: any;
export const CLOUD_STYLE_SNAPSHOT_IDS: any;
export const CLOUD_SURFACE_LIGHT_MIN_WEIGHT: any;
export const CLOUD_SURFACE_NORMAL_RADIUS: any;
export const CLOUD_TRANSMITTANCE_EPSILON: any;
export const CLOUD_WEATHER_CARVE_WIDTH: any;
export const CLOUD_WHITE_TOP_DEPTH_SCALE: any;
export const CLOUD_WHITE_TOP_HEIGHT_GAIN: any;
export const CLOUD_WHITE_TOP_MIN_SUN_REACH: any;
export const COLLISION_METADATA_KINDS: any;
export const COLLISION_METADATA_VERSION: any;
export const COMPILED_TREE_MANIFEST_SCHEMA: any;
export const COMPILED_TREE_MANIFEST_VERSION: any;
export const CONTACT_SHADOW_AERIAL_FADE: any;
export const COOKIE_CAPABLE_LIGHT_TYPES: any;
export const CURL_NOISE_DEFAULT_DIMS: any;
export const CURL_NOISE_PLAN: any;
export class CloudCirrus { constructor(...args: any[]); [key: string]: any; }
export class CloudFade { constructor(...args: any[]); [key: string]: any; }
export class CloudHaze { constructor(...args: any[]); [key: string]: any; }
export class CloudLighting { constructor(...args: any[]); [key: string]: any; }
export class CloudParamGroup { constructor(...args: any[]); [key: string]: any; }
export class CloudParams { constructor(...args: any[]); [key: string]: any; }
export class CloudShape { constructor(...args: any[]); [key: string]: any; }
export class CloudStyleParams { constructor(...args: any[]); [key: string]: any; }
export class CloudWind { constructor(...args: any[]); [key: string]: any; }
export class CompiledTreeInstance { constructor(...args: any[]); [key: string]: any; }
export const DAY_CYCLE_PHASE: any;
export const DEFAULT_ALPHA_SETTINGS: any;
export const DEFAULT_ASSET_SOURCE_ORDER: any;
export const DEFAULT_ATMOSPHERE_PARAMS: any;
export const DEFAULT_AVERAGE_SHADOW_SETTINGS: any;
export const DEFAULT_BASE_TEXTURE_SETTINGS: any;
export const DEFAULT_BRANCH_TREE_SETTINGS: any;
export const DEFAULT_CALL_ME_SENSEI_GRASS_CLUMP: any;
export const DEFAULT_CEL_SHADE_SETTINGS: any;
export const DEFAULT_CHARACTER_ANIMATION_ROLES: any;
export const DEFAULT_CHARACTER_CONTROLLER_PROFILE: any;
export const DEFAULT_CLOUD_PARAMS: any;
export const DEFAULT_CLOUD_STYLE_PARAMS: any;
export const DEFAULT_CLOUD_STYLE_SNAPSHOT: any;
export const DEFAULT_CONTACT_SHADOW_SETTINGS: any;
export const DEFAULT_DAY_CYCLE_CURVES: any;
export const DEFAULT_ENVIRONMENT_FEATURES: any;
export const DEFAULT_ENVIRONMENT_PARAMETERS: any;
export const DEFAULT_ENV_MAP_OPTIONS: any;
export const DEFAULT_EYE_HIGHLIGHT_SETTINGS: any;
export const DEFAULT_FACE_LIGHTING_SETTINGS: any;
export const DEFAULT_FLOWER_SETTINGS: any;
export const DEFAULT_FUR_SETTINGS: any;
export const DEFAULT_GLITTER_SETTINGS: any;
export const DEFAULT_GOD_RAYS_PARAMS: any;
export const DEFAULT_GRASS_SETTINGS: any;
export const DEFAULT_GROUND_SHADER_PRESET: any;
export const DEFAULT_GROUND_SHADER_SETTINGS: any;
export const DEFAULT_GROUND_STABILIZER_CONFIG: any;
export const DEFAULT_HAIR_HIGHLIGHT_SETTINGS: any;
export const DEFAULT_HERO_CLOUD_RECIPE: any;
export const DEFAULT_INDIRECT_LIGHT_SETTINGS: any;
export const DEFAULT_LIGHTING_STYLE_DOMAINS: any;
export const DEFAULT_LIGHT_FIXTURE_DOMAINS: any;
export const DEFAULT_LOCAL_LIGHT_SETTINGS: any;
export const DEFAULT_LOCOMOTION_STATE_MACHINE_CONFIG: any;
export const DEFAULT_MATERIAL_MAP_SETTINGS: any;
export const DEFAULT_MOON_PARAMS: any;
export const DEFAULT_NIGHT_SKY_PARAMS: any;
export const DEFAULT_NOISE_PARAMS: any;
export const DEFAULT_OUTLINE_SETTINGS: any;
export const DEFAULT_PERSPECTIVE_REMOVAL_SETTINGS: any;
export const DEFAULT_POST_GENERATOR_DOMAINS: any;
export const DEFAULT_POST_PROCESSING_FEATURES: any;
export const DEFAULT_POST_PROCESSING_PARAMETERS: any;
export const DEFAULT_PRESET_NAME: any;
export const DEFAULT_QUALITY_LEVEL: any;
export const DEFAULT_RIM_LIGHT_SETTINGS: any;
export const DEFAULT_ROCKGEN_MESHING_SETTINGS: any;
export const DEFAULT_ROCK_COLUMNS_SETTINGS: any;
export const DEFAULT_ROCK_CRACKS_SETTINGS: any;
export const DEFAULT_ROCK_CUTS_SETTINGS: any;
export const DEFAULT_ROCK_FACET_SETTINGS: any;
export const DEFAULT_ROCK_FALLOFF_SETTINGS: any;
export const DEFAULT_ROCK_HEIGHTFIELD_SETTINGS: any;
export const DEFAULT_ROCK_LOD_DISTANCES: any;
export const DEFAULT_ROCK_NOISE_SETTINGS: any;
export const DEFAULT_ROCK_SHADER_PRESET: any;
export const DEFAULT_ROCK_SHADER_SETTINGS: any;
export const DEFAULT_ROCK_SHAPE_SETTINGS: any;
export const DEFAULT_ROCK_STRATA_SETTINGS: any;
export const DEFAULT_ROCK_SURFACE_SETTINGS: any;
export const DEFAULT_ROCK_WARP_SETTINGS: any;
export const DEFAULT_SCAN_STYLIZE_PARAMS: any;
export const DEFAULT_SCENE_SHADOW_SETTINGS: any;
export const DEFAULT_SELF_SHADOW_SETTINGS: any;
export const DEFAULT_SHADOW_COLOR_SETTINGS: any;
export const DEFAULT_SKIN_TONE_SETTINGS: any;
export const DEFAULT_SKY_ATMOSPHERE: any;
export const DEFAULT_SKY_COLOR_PARAMS: any;
export const DEFAULT_SKY_PARAMS: any;
export const DEFAULT_SKY_SCENARIO: any;
export const DEFAULT_SKY_SETTINGS: any;
export const DEFAULT_SKY_SHADER_PRESET: any;
export const DEFAULT_SKY_SHADER_SETTINGS: any;
export const DEFAULT_SKY_STYLE_SNAPSHOT: any;
export const DEFAULT_SKY_TIME_KEYFRAMES: any;
export const DEFAULT_SOLID_STYLE_DOMAINS: any;
export const DEFAULT_SPECULAR_SETTINGS: any;
export const DEFAULT_STICKER_SETTINGS: any;
export const DEFAULT_STYLE_BUNDLE_BASE_URL: any;
export const DEFAULT_STYLIZED_EROSION_PARAMS: any;
export const DEFAULT_STYLIZED_TREE_SETTINGS: any;
export const DEFAULT_SUN_PARAMS: any;
export const DEFAULT_TIME_OF_DAY_PARAMS: any;
export const DEFAULT_TOONLAB_ROCK_LIBRARY_BASE_URL: any;
export const DEFAULT_TOONLAB_ROCK_MATERIAL_LIBRARY_URL: any;
export const DEFAULT_TOONLAB_SHOWCASE_WEIGHT_LAYER_BASE_URL: any;
export const DEFAULT_TOONLAB_SOURCE_BASE_URL: any;
export const DEFAULT_UNSUPPORTED_STYLE_DOMAINS: any;
export const DEFAULT_VEGETATION_SHADER_SETTINGS: any;
export const DEFAULT_WATER_INTERACTION_CONFIG: any;
export const DEFAULT_WATER_SCENARIO: any;
export const DEFAULT_WATER_SETTINGS: any;
export const DEFAULT_WATER_UNDERWATER_ATMOSPHERE: any;
export const ENVIRONMENT_DEBUG_MODES: any;
export const ENVIRONMENT_MATERIAL_ROLES: any;
export const ENVIRONMENT_PRESET_ALIASES: any;
export const ENVIRONMENT_PRESET_DOCUMENT_TYPE: any;
export const ENVIRONMENT_PRESET_SCHEMA_VERSION: any;
export const ENVIRONMENT_SCENARIOS: any;
export const ENVIRONMENT_SETTING_FIELD_SCHEMA: any;
export const ENVIRONMENT_SETTING_GROUPS: any;
export const ENVIRONMENT_SHARED_UNIFORM_NAMES: any;
export const ENVIRONMENT_SUN_INTENSITY_SCALE: any;
export const EYE_HIGHLIGHT_MASK_CHANNELS: any;
export const EYE_HIGHLIGHT_SOURCE_MASK_MODES: any;
export const FACE_HEAD_SPACE_MODES: any;
export const FIRST_PARTY_STYLE_BUNDLES: any;
export const FIXTURE_SCHEDULE_MODES: any;
export const FLOWER_SETTING_FIELD_SCHEMA: any;
export const FLOWER_SETTING_GROUPS: any;
export const FLOWER_SHADER: any;
export const FLOWER_SHADER_PROFILE: any;
export const FLOWER_SHADER_PROFILE_DOCUMENT_TYPE: any;
export const FLOWER_SHADER_PROFILE_SCHEMA_VERSION: any;
export const FLOWER_SPECIES: any;
export const FOLIAGE_SHADER: any;
export const GOD_RAYS_PARAM_KEYS: any;
export const GOD_RAYS_PARAM_SCHEMA: any;
export const GRASS_CLUMP_GEOMETRY_RECIPE: any;
export const GRASS_CLUMP_LODS: any;
export const GRASS_COLOR_PALETTES: any;
export const GRASS_PRESET_DOCUMENT_TYPE: any;
export const GRASS_PRESET_SCHEMA_VERSION: any;
export const GRASS_SETTING_FIELD_SCHEMA: any;
export const GRASS_SETTING_GROUPS: any;
export const GRASS_SHADER: any;
export const GRASS_SHADER_PROFILE: any;
export const GRASS_SHADER_PROFILE_DOCUMENT_TYPE: any;
export const GRASS_SHADER_PROFILE_SCHEMA_VERSION: any;
export const GROUND_PRINT_SHAPES: any;
export const GROUND_SHADER: any;
export const GROUND_SHADER_DOCUMENT_TYPE: any;
export const GROUND_SHADER_FIELD_SCHEMA: any;
export const GROUND_SHADER_SCHEMA_VERSION: any;
export const GROUND_SHADER_SETTING_GROUPS: any;
export const GROUND_SHADER_UNIFORM_BY_FIELD: any;
export class GroundPrintLayer { constructor(...args: any[]); [key: string]: any; }
export const HAIR_HIGHLIGHT_MASK_CHANNELS: any;
export const HAIR_HIGHLIGHT_MODES: any;
export const HAIR_HIGHLIGHT_MODE_VALUES: any;
export const HAIR_HIGHLIGHT_SOURCE_MASK_MODES: any;
export const HERO_CLOUD_DEFAULT_RESOLUTION: any;
export const HERO_CLOUD_MAP_PADDING: any;
export const HERO_CLOUD_PREVIEW_ALTITUDE: any;
export const HERO_CLOUD_RECIPE_TYPE: any;
export const HERO_CLOUD_RECIPE_VERSION: any;
export const HUMANOID_ROLES: any;
export const LEAF_SHAPE_PRESETS: any;
export const LEGACY_STYLE_BUNDLE_SCHEMA_VERSION: any;
export const LEGACY_TREE_IDS: any;
export const LEGACY_TREE_PRESETS: any;
export const LIGHTING_LOOK_DOCUMENT_TYPE: any;
export const LIGHTING_LOOK_PRESETS: any;
export const LIGHTING_LOOK_SCHEMA_VERSION: any;
export const LIGHTING_LUMINAIRE_PRESETS: any;
export const LIGHTING_QUALITY_PRESETS: any;
export const LIGHTING_RECIPE_DOCUMENT_TYPE: any;
export const LIGHTING_RECIPE_SCHEMA_VERSION: any;
export const LIGHTING_RIG_PRESETS: any;
export const LIGHTING_STYLE_APPLY_METADATA: any;
export const LIGHTING_STYLE_DOCUMENT_TYPE: any;
export const LIGHTING_STYLE_GENERATOR_DOMAIN: any;
export const LIGHTING_STYLE_SCHEMA_VERSION: any;
export const LIGHTWEIGHT_WORLD_COLLISION_ADAPTER: any;
export const LIGHT_FIXTURE_APPLY_METADATA: any;
export const LIGHT_FIXTURE_DOCUMENT_TYPE: any;
export const LIGHT_FIXTURE_GENERATOR_DOMAIN: any;
export const LIGHT_FIXTURE_SCHEMA_VERSION: any;
export const LIGHT_INTENSITY_UNITS: any;
export const LIGHT_TYPES: any;
export const LOCOMOTION_ROLES: any;
export const LOMMEL_SEELIGER_AT_FULL: any;
export const MANUFACTURED_CONTENT_FLAGS: any;
export const MANUFACTURED_MATERIAL_BASES: any;
export const MANUFACTURED_MATERIAL_FINISHES: any;
export const MANUFACTURED_MATERIAL_LOOK_VERSION: any;
export const MANUFACTURED_MATERIAL_MANIFEST_TYPE: any;
export const MANUFACTURED_MATERIAL_MANIFEST_VERSION: any;
export const MANUFACTURED_OBJECT_CLASSES: any;
export const MANUFACTURED_RENDER_MODES: any;
export const MANUFACTURED_STRUCTURAL_ROLES: any;
export const MATERIAL_ROLES: any;
export const MATERIAL_ROLE_LABELS: any;
export const MATERIAL_ROLE_NAMES_BY_VALUE: any;
export const MAX_MARCH_DIST_MARGIN: any;
export const MIXAMO_CHAIN_CHILD: any;
export const MOON_ALBEDO_DISC_MEAN: any;
export const MOON_ALBEDO_PLAN: any;
export const MOON_ALBEDO_SCHEMA_VERSION: any;
export const MOON_ALBEDO_SEED_NAMESPACE: any;
export const MOON_COLOR_FIELD: any;
export const MOON_DISC_FULL_MEAN_RADIANCE: any;
export const MOON_DISC_NORMALISATION: any;
export const MULTI_SCATTERING_LUT_SIZE: any;
export class ManufacturedStyleLabelingError { constructor(...args: any[]); [key: string]: any; }
export const NATIVE_LOCOMOTION_CLIP_NAMES: any;
export const NIGHT_SKY_DEFAULT_RADIUS: any;
export const NIGHT_SKY_PARAM_KEYS: any;
export const NIGHT_SKY_PARAM_SCHEMA: any;
export const OFFICIAL_CATALOG_ASSET_VERSION: any;
export const OFFICIAL_CATALOG_PROVIDER_TRANSPORTS: any;
export class OfficialCatalogProviderError { constructor(...args: any[]); [key: string]: any; }
export const POST_GENERATOR_DOMAIN: any;
export const POST_PROCESSING_PRESETS: any;
export const POST_PROCESSING_PRESET_DOCUMENT_TYPE: any;
export const POST_PROCESSING_PRESET_SCHEMA_VERSION: any;
export const POST_PROCESSING_SETTING_FIELD_SCHEMA: any;
export const POST_PROCESSING_SETTING_GROUPS: any;
export const PRESETS: any;
export const PRESET_NAMES: any;
export const QUALITY_LEVELS: any;
export const QUALITY_LEVEL_FIELDS: any;
export const QUALITY_LEVEL_NAMES: any;
export const QUALITY_LEVEL_OPTIONS: any;
export const REFERENCE_CEL_SHADE_SETTINGS: any;
export const REFERENCE_ROCK_LOD_RATIOS: any;
export const REFERENCE_ROCK_LOD_ROLES: any;
export const REFERENCE_ROCK_LOD_ROLE_BUDGETS: any;
export const REFERENCE_SHADOW_COLOR_SETTINGS: any;
export const RENDER_LAYER_BAND: any;
export const RENDER_LAYER_NAMES: any;
export const RENDER_LAYER_USAGE: any;
export const RENDER_LISTS: any;
export const RESOLVED_SCENE_LOOK_DOCUMENT_TYPE: any;
export const RESOLVED_SCENE_LOOK_DOCUMENT_VERSION: any;
export const REVIEWED_CATALOG_LICENSES: any;
export const RIM_LIGHT_MODES: any;
export const ROCKGEN_MAX_MESH_EDIT_DELTAS: any;
export const ROCKGEN_MAX_MESH_EDIT_OPERATIONS: any;
export const ROCKGEN_MESH_EDIT_ENCODING: any;
export const ROCKGEN_PIECE_GROUP_IDS: any;
export const ROCKGEN_PRESET_DOCUMENT_TYPE: any;
export const ROCKGEN_PRESET_SCHEMA_VERSION: any;
export const ROCKGEN_PROJECT_DOCUMENT_TYPE: any;
export const ROCKGEN_PROJECT_SCHEMA_VERSION: any;
export const ROCKGEN_QUALITY_LEVELS: any;
export const ROCKGEN_QUALITY_PRESETS: any;
export const ROCKGEN_SETTING_DEFAULTS: any;
export const ROCKGEN_SETTING_FIELD_SCHEMA: any;
export const ROCKGEN_SETTING_GROUPS: any;
export const ROCK_HEIGHTFIELD_PROFILES: any;
export const ROCK_NORMALS_MODES: any;
export const ROCK_PBR_TEXTURE_PRESETS: any;
export const ROCK_SHADER_DOCUMENT_TYPE: any;
export const ROCK_SHADER_FIELD_SCHEMA: any;
export const ROCK_SHADER_SCHEMA_VERSION: any;
export const ROCK_SHADER_SETTING_GROUPS: any;
export const ROCK_SHAPE_TYPES: any;
export const ROCK_SURFACE_TEXTURE_PRESETS: any;
export const ROCK_SURFACE_TEXTURE_STYLES: any;
export const RenderLayer: any;
export class RetainedGrassClumpField { constructor(...args: any[]); [key: string]: any; }
export const SCENE_COLLISION_RUNTIME_VERSION: any;
export const SCENE_CONTENT_DOCUMENT_TYPE: any;
export const SCENE_LAYER_DOCUMENT_VERSION: any;
export const SCENE_OVERRIDE_DOCUMENT_TYPE: any;
export const SCENE_QUALITY_DOCUMENT_TYPE: any;
export const SCENE_QUALITY_PROFILES: any;
export const SCENE_QUALITY_PROFILE_VERSION: any;
export const SCENE_SCENARIO_DOCUMENT_TYPE: any;
export const SCENE_STYLE_MANIFEST_TYPE: any;
export const SCENE_STYLE_MANIFEST_VERSION: any;
export const SCENE_STYLE_OPERATION_NAMES: any;
export const SCENE_UPDATE_PHASES: any;
export const SCENE_UPDATE_SCHEDULER_VERSION: any;
export const SELF_SHADOW_SOURCE_MODES: any;
export const SHADOW_CAPABLE_LIGHT_TYPES: any;
export const SHADOW_COLOR_PRESETS: any;
export const SHADOW_POLICY_MODES: any;
export const SHADOW_UPDATE_MODES: any;
export const SHOREWARD_ORIENTATION: any;
export const SKY_COLOR_FIELD_SCHEMA: any;
export const SKY_COLOR_MODULE_IDS: any;
export const SKY_PARAMS_BLOCK_IDS: any;
export const SKY_PARAMS_DOCUMENT_TYPE: any;
export const SKY_PARAMS_FIELD_SCHEMA: any;
export const SKY_PARAMS_SCHEMA_VERSION: any;
export const SKY_PRESET_ALIASES: any;
export const SKY_PRESET_DOCUMENT_TYPE: any;
export const SKY_PRESET_SCHEMA_VERSION: any;
export const SKY_QUALITY_OPTIONS: any;
export const SKY_QUALITY_TIERS: any;
export const SKY_SCENARIOS: any;
export const SKY_SCENE_OVERRIDE_PRIORITIES: any;
export const SKY_SETTING_FIELD_SCHEMA: any;
export const SKY_SETTING_GROUPS: any;
export const SKY_SHADER_DOCUMENT_TYPE: any;
export const SKY_SHADER_FIELD_COUNT: any;
export const SKY_SHADER_FIELD_SCHEMA: any;
export const SKY_SHADER_SCHEMA_VERSION: any;
export const SKY_SHADER_SETTING_GROUPS: any;
export const SKY_STYLE_SNAPSHOTS: any;
export const SKY_STYLE_SNAPSHOT_IDS: any;
export const SPECULAR_DIRECTION_MODES: any;
export const SPECULAR_MASK_CHANNELS: any;
export const SPECULAR_SOURCE_MASK_MODES: any;
export const STICKER_BLEND_MODES: any;
export const STYLE_BUNDLE_DOCUMENT_TYPE: any;
export const STYLE_BUNDLE_PROVIDER_VERSION: any;
export const STYLE_BUNDLE_SCHEMA_VERSION: any;
export const STYLE_BUNDLE_SLOTS: any;
export const STYLE_BUNDLE_SLOT_IDS: any;
export const STYLE_DOMAIN_MATERIAL_ROLES: any;
export const STYLE_DOMAIN_SLOT_ROUTES: any;
export const STYLE_MATERIAL_CONTRACT_SCHEMA_VERSION: any;
export const STYLE_MATERIAL_EXEMPTION_STRATEGIES: any;
export const STYLE_MATERIAL_MASK_ENCODINGS: any;
export const STYLE_MATERIAL_STABLE_ID_PATTERN: any;
export const STYLE_SCENE_AUDIT_DOCUMENT_TYPE: any;
export const STYLE_SCENE_AUDIT_MODES: any;
export const STYLE_SCENE_AUDIT_SCHEMA_VERSION: any;
export const STYLE_TARGET_DOMAINS: any;
export const STYLE_TARGET_LABEL_KEY: any;
export const STYLE_TARGET_LABEL_SCHEMA_VERSION: any;
export const STYLIZED_FOREST_IMPOSTOR_QUALITY: any;
export const STYLIZED_TREE_EXAMPLES: any;
export const STYLIZED_TREE_SETTING_FIELD_SCHEMA: any;
export const STYLIZED_TREE_SETTING_GROUPS: any;
export const SUN_COLOR_FIELD: any;
export const SURFACE_MATERIAL_MODE: any;
export class SceneCollisionRuntimeError { constructor(...args: any[]); [key: string]: any; }
export class SceneLookCompositionError { constructor(...args: any[]); [key: string]: any; }
export class SceneQualityApplicationError { constructor(...args: any[]); [key: string]: any; }
export class SceneUpdateSchedulerError { constructor(...args: any[]); [key: string]: any; }
export class SkyColorParams { constructor(...args: any[]); [key: string]: any; }
export class SkySystem { constructor(...args: any[]); [key: string]: any; }
export class StyleBundleApplicationError { constructor(...args: any[]); [key: string]: any; }
export class StyleBundleTransactionError { constructor(...args: any[]); [key: string]: any; }
export class StyleTargetDiscoveryError { constructor(...args: any[]); [key: string]: any; }
export class StyleTargetLabelError { constructor(...args: any[]); [key: string]: any; }
export class StylizedBush { constructor(...args: any[]); [key: string]: any; }
export class StylizedContactShadowField { constructor(...args: any[]); [key: string]: any; }
export class StylizedFlower { constructor(...args: any[]); [key: string]: any; }
export class StylizedFlowerField { constructor(...args: any[]); [key: string]: any; }
export class StylizedForest { constructor(...args: any[]); [key: string]: any; }
export class StylizedGrassClumpField { constructor(...args: any[]); [key: string]: any; }
export class StylizedGrassField { constructor(...args: any[]); [key: string]: any; }
export class StylizedSky { constructor(...args: any[]); [key: string]: any; }
export class StylizedTree { constructor(...args: any[]); [key: string]: any; }
export class StylizedTreeFoliage { constructor(...args: any[]); [key: string]: any; }
export class StylizedUnderstory { constructor(...args: any[]); [key: string]: any; }
export const TOONLAB_ANIME_GAME_PROFILE: any;
export const TOONLAB_ANIME_GAME_PROFILE_FAMILY: any;
export const TOONLAB_ANIME_GAME_RENDERING: any;
export const TOONLAB_INSPECTOR_DOCUMENT_TYPE: any;
export const TOONLAB_INSPECTOR_VERSION: any;
export const TOONLAB_LANDSCAPE_LAYERS: any;
export const TOONLAB_LANDSCAPE_WEIGHTMAP_SCHEMA: any;
export const TOONLAB_LIGHTING_MANIFEST_SCHEMA_VERSION: any;
export const TOONLAB_LIGHTING_MANIFEST_TYPE: any;
export const TOONLAB_MANNEQUIN_ASSET: any;
export const TOONLAB_MANNEQUIN_ASSET_URL: any;
export const TOONLAB_MATERIAL_FAMILIES: any;
export const TOONLAB_MOUNTAIN_PROFILE_DEFAULTS: any;
export const TOONLAB_MOUNTAIN_SHADER_GUID: any;
export const TOONLAB_RENDERER_BACKENDS: any;
export const TOONLAB_RENDERER_CONFIGURATION_VERSION: any;
export const TOONLAB_ROCK_FAMILY_VERTEX_MOTION_CONTRACT: any;
export const TOONLAB_ROCK_MANIFEST_SCHEMA: any;
export const TOONLAB_ROCK_MANIFEST_VERSION: any;
export const TOONLAB_ROCK_MATERIAL_CROSSWALK: any;
export const TOONLAB_ROCK_MATERIAL_FALLBACKS: any;
export const TOONLAB_ROCK_MATERIAL_LIBRARY_SCHEMA: any;
export const TOONLAB_ROCK_MATERIAL_LIBRARY_SCHEMA_VERSION: any;
export const TOONLAB_ROCK_PROFILES: any;
export const TOONLAB_ROCK_PROFILE_DEFAULTS: any;
export const TOONLAB_ROCK_PROFILE_IDS: any;
export const TOONLAB_ROCK_SHADER_GUID: any;
export const TOONLAB_SHOWCASE_WEIGHTMAP_CONTRACT: any;
export const TOONLAB_SHOWCASE_WEIGHT_PACK_LAYOUT: any;
export const TOONLAB_SOURCE_MATERIAL_BASE_URL: any;
export const TOONLAB_SOURCE_SCHEMA: any;
export const TOONLAB_VERSION: any;
export const TOON_CHARACTER_LAYER: any;
export const TOON_DEBUG_OUTPUT_LABELS: any;
export const TOON_DEBUG_OUTPUT_MODES: any;
export const TOON_PRESET_DOCUMENT_TYPE: any;
export const TOON_PRESET_IDS: any;
export const TOON_PRESET_SCHEMA_VERSION: any;
export const TOON_SETTING_DEFAULTS: any;
export const TOON_SETTING_FIELD_SCHEMA: any;
export const TOON_SETTING_GROUPS: any;
export const TOON_SETTING_GROUP_METADATA: any;
export const TRANSMITTANCE_LUT_HEIGHT: any;
export const TRANSMITTANCE_LUT_WIDTH: any;
export const TREE_FOLIAGE_ARCHITECTURES: any;
export const TREE_FOLIAGE_BLOBS: any;
export const TREE_RECIPE_SCHEMA: any;
export const TREE_RECIPE_VERSION: any;
export const TREE_RUNTIME_QUALITY_PROFILES: any;
export const TREE_SHADER_DOCUMENT_TYPE: any;
export const TREE_SHADER_PROFILE: any;
export const TREE_SHADER_SCHEMA_VERSION: any;
export const TREE_SURFACE_PROFILES: any;
export const TREE_SURFACE_PROFILE_DEFAULTS: any;
export const TREE_TRUNK_STYLES: any;
export const TRIMESH_DATA_COLLISION_ADAPTER: any;
export class ToonLabInspectorToggleError { constructor(...args: any[]); [key: string]: any; }
export class ToonLabSourceLibrary { constructor(...args: any[]); [key: string]: any; }
export const UNDERSTORY_AERIAL_FADE: any;
export const VEGETATION_MATERIAL_CONTRACT_VERSION: any;
export const VEGETATION_MATERIAL_ROLES: any;
export const VEGETATION_MATERIAL_VARIANTS: any;
export const VEGETATION_SHADER: any;
export const VEGETATION_SHADERS: any;
export const VEGETATION_SHADER_DOCUMENT_TYPE: any;
export const VEGETATION_SHADER_FAMILY: any;
export const VEGETATION_SHADER_FIELD_SCHEMA: any;
export const VEGETATION_SHADER_SCHEMA_VERSION: any;
export const VEGETATION_SHADER_SCOPES: any;
export const VEGETATION_SHADER_SCOPE_EXCLUDED_FIELDS: any;
export const VEGETATION_SHADER_SCOPE_IDS: any;
export const VEGETATION_SHADER_SETTING_GROUPS: any;
export const VEGETATION_SHADER_UNIFORM_BY_FIELD: any;
export const VEGETATION_SHARED_SHADER_GROUP_IDS: any;
export const WATER_COLOR_TONES: any;
export const WATER_COLOR_TONE_NAMES: any;
export const WATER_DEBUG_MODES: any;
export const WATER_GERSTNER_WAVE_COUNT: any;
export const WATER_PRESET_DOCUMENT_TYPE: any;
export const WATER_PRESET_NAMES: any;
export const WATER_PRESET_SCHEMA_VERSION: any;
export const WATER_QUALITY_LEVELS: any;
export const WATER_QUALITY_TIERS: any;
export const WATER_SCENARIOS: any;
export const WATER_SCENE_OVERRIDE_KEYS: any;
export const WATER_SCENE_OVERRIDE_PRIORITIES: any;
export const WATER_SETTING_FIELD_SCHEMA: any;
export const WATER_SETTING_FIELD_SCHEMA_BY_GROUP: any;
export const WATER_SETTING_GROUPS: any;
export const WATER_SIM_MAX_IMPULSES: any;
export const WEATHER_MAP_DEFAULT_RESOLUTION: any;
export const WEATHER_MAP_PROFILE_DEFAULTS: any;
export const WEATHER_MAP_PROFILE_FIELDS: any;
export const WEATHER_MAP_RESOLUTIONS: any;
export const WEATHER_MAP_SCHEMA_VERSION: any;
export class WaterBreakerSystem { constructor(...args: any[]); [key: string]: any; }
export class WaterCurrentField { constructor(...args: any[]); [key: string]: any; }
export class WaterInteractionManager { constructor(...args: any[]); [key: string]: any; }
export class WaterKelpField { constructor(...args: any[]); [key: string]: any; }
export class WaterRain { constructor(...args: any[]); [key: string]: any; }
export class WaterRippleSimulation { constructor(...args: any[]); [key: string]: any; }
export class WaterScenePasses { constructor(...args: any[]); [key: string]: any; }
export class WaterShoreStateField { constructor(...args: any[]); [key: string]: any; }
export class WaterSplashSystem { constructor(...args: any[]); [key: string]: any; }
export class WaterSurface { constructor(...args: any[]); [key: string]: any; }
export class WaterUnderwaterAtmosphere { constructor(...args: any[]); [key: string]: any; }
export function addPieceToDocument(...args: any[]): any;
export function advanceEnvironmentShaderTime(...args: any[]): any;
export function advanceToonLabSourceEnvironmentState(...args: any[]): any;
export function aerosolScaleForTurbidity(...args: any[]): any;
export function alphaCutoffForMaterial(...args: any[]): any;
export function alphaTestForMaterial(...args: any[]): any;
export function analyzeManufacturedAsset(...args: any[]): any;
export function applyBarkShader(...args: any[]): any;
export function applyCloudBlueShadowNode(...args: any[]): any;
export function applyCloudInnerPaintNode(...args: any[]): any;
export function applyCloudLightBlendNode(...args: any[]): any;
export function applyCloudShadowWashNode(...args: any[]): any;
export function applyCloudStyleNode(...args: any[]): any;
export function applyCloudTimePaletteNode(...args: any[]): any;
export function applyCloudToneNode(...args: any[]): any;
export function applyCloudTopLightNode(...args: any[]): any;
export function applyCloudWhiteTopNode(...args: any[]): any;
export function applyCompatibilityGroundShader(...args: any[]): any;
export function applyEnvironmentLampEmissive(...args: any[]): any;
export function applyEnvironmentSettingsToMaterial(...args: any[]): any;
export function applyEnvironmentShader(...args: any[]): any;
export function applyEnvironmentTimeOfDay(...args: any[]): any;
export function applyFlowerShader(...args: any[]): any;
export function applyFoliageShader(...args: any[]): any;
export function applyGrassColorPalette(...args: any[]): any;
export function applyGrassShader(...args: any[]): any;
export function applyGroundShader(...args: any[]): any;
export function applyGroundStabilizerFrame(...args: any[]): any;
export function applyLocomotionFrame(...args: any[]): any;
export function applyManufacturedMaterialManifest(...args: any[]): any;
export function applyManufacturedStyleTargetLabelProposal(...args: any[]): any;
export function applyRockShader(...args: any[]): any;
export function applyScanStylizeToMaterial(...args: any[]): any;
export function applySceneQualityProfile(...args: any[]): any;
export function applySculptEdit(...args: any[]): any;
export function applySculptEditToField(...args: any[]): any;
export function applySkyColorNode(...args: any[]): any;
export function applySkySettingsToMaterial(...args: any[]): any;
export function applySkyShaderSettings(...args: any[]): any;
export function applyStyleBundle(...args: any[]): any;
export function applyToonLabNamedSourceMaterials(...args: any[]): any;
export function applyToonLabSourceMaterials(...args: any[]): any;
export function applyToonSettingsToMaterial(...args: any[]): any;
export function applyToonShader(...args: any[]): any;
export function applyVegetationShader(...args: any[]): any;
export function applyVegetationShaderScope(...args: any[]): any;
export function applyWaterInteractionFrame(...args: any[]): any;
export function applyWaterSettingsToMaterial(...args: any[]): any;
export function assertCatalogLicenseRelease(...args: any[]): any;
export function assertFixedMarchBudget(...args: any[]): any;
export function assertLightingLook(...args: any[]): any;
export function assertLightingRecipe(...args: any[]): any;
export function atmosphereRaymarchNodes(...args: any[]): any;
export function auditSceneStyleContract(...args: any[]): any;
export function auditStyleBundleApplication(...args: any[]): any;
export function azimuthOf(...args: any[]): any;
export function bakeEnvironmentVertexAo(...args: any[]): any;
export function bakeFoliageGeometry(...args: any[]): any;
export function bakeSolidBaseColorTextures(...args: any[]): any;
export function beerLambertNode(...args: any[]): any;
export function buildGerstnerWaves(...args: any[]): any;
export function buildLightFixtureFromSample(...args: any[]): any;
export function buildLightingStyleFromSample(...args: any[]): any;
export function buildNearshorePhaseField(...args: any[]): any;
export function buildToonLabLandscapeMaterial(...args: any[]): any;
export function bumpDocumentRevision(...args: any[]): any;
export function candelaToLumens(...args: any[]): any;
export function captureEnvironmentAmbientProbe(...args: any[]): any;
export function captureStyleTargetSnapshot(...args: any[]): any;
export function celestialDirectionForHour(...args: any[]): any;
export function celestialFrame(...args: any[]): any;
export function classifyEnvironmentMaterialRole(...args: any[]): any;
export function classifyManufacturedMaterial(...args: any[]): any;
export function classifyMaterialRole(...args: any[]): any;
export function classifyToonLabMaterialProfile(...args: any[]): any;
export function cloneAnimeGameProfile(...args: any[]): any;
export function cloudAmbientNode(...args: any[]): any;
export function cloudBaseShadowNode(...args: any[]): any;
export function cloudBaseShapeDimsForMip(...args: any[]): any;
export function cloudDirectionalAttenuationNode(...args: any[]): any;
export function cloudDirectionalScatteringNode(...args: any[]): any;
export function cloudGroundBounceNode(...args: any[]): any;
export function cloudGroundRadianceNode(...args: any[]): any;
export function cloudHistoryJitterOffsets(...args: any[]): any;
export function cloudHistoryWarmupFrames(...args: any[]): any;
export function cloudMoonDirectionalNode(...args: any[]): any;
export function cloudMoonRimNode(...args: any[]): any;
export function cloudParamsToLive(...args: any[]): any;
export function cloudPhaseNode(...args: any[]): any;
export function cloudSkyAmbientNode(...args: any[]): any;
export function cloudStyleParamsToLive(...args: any[]): any;
export function cloudSunTransmittanceNode(...args: any[]): any;
export function collectBones(...args: any[]): any;
export function collectCatalogLodBindings(...args: any[]): any;
export function collectObjectTrimesh(...args: any[]): any;
export function collectStyleTargets(...args: any[]): any;
export function colorTemperatureToRgb(...args: any[]): any;
export function combineMasks(...args: any[]): any;
export function compareGeometryBounds(...args: any[]): any;
export function compareGeometrySilhouettes(...args: any[]): any;
export function compareRockLodGeometry(...args: any[]): any;
export function compileDocument(...args: any[]): any;
export function computeBreakingDepth(...args: any[]): any;
export function computeDocumentBounds(...args: any[]): any;
export function computeModelBounds(...args: any[]): any;
export function coneSolidAngle(...args: any[]): any;
export function configureCallMeSenseiDirectionalLight(...args: any[]): any;
export function configureToonLabRenderer(...args: any[]): any;
export function copySurfaceMaterialModes(...args: any[]): any;
export function copyTextureTransform(...args: any[]): any;
export function createAlphaSettings(...args: any[]): any;
export function createAmbientLightDescriptor(...args: any[]): any;
export function createArmPoseState(...args: any[]): any;
export function createAssetGapRecord(...args: any[]): any;
export function createAssetSourcingPolicy(...args: any[]): any;
export function createAtmosphereDome(...args: any[]): any;
export function createAtmosphereParams(...args: any[]): any;
export function createAtmosphereScattering(...args: any[]): any;
export function createAverageShadowSettings(...args: any[]): any;
export function createBakedFoliageMaterial(...args: any[]): any;
export function createBakedLeafTexture(...args: any[]): any;
export function createBarkGradientMap(...args: any[]): any;
export function createBarkShaderSettings(...args: any[]): any;
export function createBaseTextureSettings(...args: any[]): any;
export function createBranchTree(...args: any[]): any;
export function createBranchTreeDocument(...args: any[]): any;
export function createBranchTreeSettings(...args: any[]): any;
export function createBranchTubeGeometry(...args: any[]): any;
export function createBranchingTreeSkeleton(...args: any[]): any;
export function createCallMeSenseiGrassField(...args: any[]): any;
export function createCallMeSenseiGrassMaterial(...args: any[]): any;
export function createCallMeSenseiSkyLightProbe(...args: any[]): any;
export function createCanopyBlobs(...args: any[]): any;
export function createCapEdgeWeight(...args: any[]): any;
export function createCatalogLodRuntime(...args: any[]): any;
export function createCelShadeSettings(...args: any[]): any;
export function createCharacterControllerProfile(...args: any[]): any;
export function createCharacterRenderPasses(...args: any[]): any;
export function createCharacterRuntime(...args: any[]): any;
export function createCloudBaseShapeData(...args: any[]): any;
export function createCloudBaseShapeVolume(...args: any[]): any;
export function createCloudCirrusMap(...args: any[]): any;
export function createCloudCirrusMapData(...args: any[]): any;
export function createCloudDensityField(...args: any[]): any;
export function createCloudErosionData(...args: any[]): any;
export function createCloudErosionVolume(...args: any[]): any;
export function createCloudLightingModel(...args: any[]): any;
export function createCloudParams(...args: any[]): any;
export function createCloudReprojection(...args: any[]): any;
export function createCloudStyleParams(...args: any[]): any;
export function createCloudVolumeMaterial(...args: any[]): any;
export function createCollisionAdapter(...args: any[]): any;
export function createCollisionMetadata(...args: any[]): any;
export function createCompatibilityGroundShaderMaterial(...args: any[]): any;
export function createContactShadowSettings(...args: any[]): any;
export function createCurlNoiseData(...args: any[]): any;
export function createCurlNoiseField(...args: any[]): any;
export function createCurlNoiseVolume(...args: any[]): any;
export function createDebugEnvironmentMaterial(...args: any[]): any;
export function createDefaultRockShaderTextureSet(...args: any[]): any;
export function createDensityWeightMask(...args: any[]): any;
export function createDirectionalLightDescriptor(...args: any[]): any;
export function createDiscAreaLightDescriptor(...args: any[]): any;
export function createEnvironmentAoMaterial(...args: any[]): any;
export function createEnvironmentBackdrop(...args: any[]): any;
export function createEnvironmentDustMotes(...args: any[]): any;
export function createEnvironmentLampRig(...args: any[]): any;
export function createEnvironmentMaterial(...args: any[]): any;
export function createEnvironmentPlanarReflection(...args: any[]): any;
export function createEnvironmentPresetDocument(...args: any[]): any;
export function createEnvironmentSettings(...args: any[]): any;
export function createEnvironmentShadowMaterial(...args: any[]): any;
export function createEnvironmentSunRig(...args: any[]): any;
export function createEnvironmentWindowOpeningMaterial(...args: any[]): any;
export function createEyeHighlightSettings(...args: any[]): any;
export function createFaceLightingSettings(...args: any[]): any;
export function createFlowerBloomNodeMaterial(...args: any[]): any;
export function createFlowerHeadBillboardNodeMaterial(...args: any[]): any;
export function createFlowerHeadGeometry(...args: any[]): any;
export function createFlowerHeadNodeMaterial(...args: any[]): any;
export function createFlowerHeadTexture(...args: any[]): any;
export function createFlowerNodeMaterial(...args: any[]): any;
export function createFlowerSettings(...args: any[]): any;
export function createFlowerShaderProfilePresetDocument(...args: any[]): any;
export function createFlowerShaderProfileSettings(...args: any[]): any;
export function createFlowerShaderSettings(...args: any[]): any;
export function createFlowerStemNodeMaterial(...args: any[]): any;
export function createFoliageShaderSettings(...args: any[]): any;
export function createFreestyleSwimClip(...args: any[]): any;
export function createFurSettings(...args: any[]): any;
export function createGeneratedLightFixtureDocument(...args: any[]): any;
export function createGeneratedLightingStyleDocument(...args: any[]): any;
export function createGeneratedPostPresetDocument(...args: any[]): any;
export function createGlitterSettings(...args: any[]): any;
export function createGodRaysPass(...args: any[]): any;
export function createGrassClumpGeometry(...args: any[]): any;
export function createGrassClumpMaterial(...args: any[]): any;
export function createGrassNodeMaterial(...args: any[]): any;
export function createGrassPresetDocument(...args: any[]): any;
export function createGrassSettings(...args: any[]): any;
export function createGrassShaderProfilePresetDocument(...args: any[]): any;
export function createGrassShaderProfileSettings(...args: any[]): any;
export function createGrassShaderSettings(...args: any[]): any;
export function createGroundPrintLayer(...args: any[]): any;
export function createGroundSampler(...args: any[]): any;
export function createGroundShaderMaterial(...args: any[]): any;
export function createGroundShaderMesh(...args: any[]): any;
export function createGroundShaderPresetDocument(...args: any[]): any;
export function createGroundShaderSettings(...args: any[]): any;
export function createGroundStabilizer(...args: any[]): any;
export function createHairHighlightSettings(...args: any[]): any;
export function createHemisphereLightDescriptor(...args: any[]): any;
export function createHeroCloudRecipe(...args: any[]): any;
export function createHeroCloudWeatherTexture(...args: any[]): any;
export function createImportedVegetationMaterial(...args: any[]): any;
export function createIndirectLightSettings(...args: any[]): any;
export function createLeafSpriteTexture(...args: any[]): any;
export function createLegacyTree(...args: any[]): any;
export function createLightArtisticSettings(...args: any[]): any;
export function createLightColor(...args: any[]): any;
export function createLightCookie(...args: any[]): any;
export function createLightDescriptor(...args: any[]): any;
export function createLightFixtureDocument(...args: any[]): any;
export function createLightFixtureGeneratorRecipe(...args: any[]): any;
export function createLightFixtureSettings(...args: any[]): any;
export function createLightIesProfile(...args: any[]): any;
export function createLightIntensity(...args: any[]): any;
export function createLightLinking(...args: any[]): any;
export function createLightShadow(...args: any[]): any;
export function createLightingCapabilityReport(...args: any[]): any;
export function createLightingLook(...args: any[]): any;
export function createLightingLookPreset(...args: any[]): any;
export function createLightingManager(...args: any[]): any;
export function createLightingQualityProfile(...args: any[]): any;
export function createLightingRecipe(...args: any[]): any;
export function createLightingRig(...args: any[]): any;
export function createLightingStyleGeneratorRecipe(...args: any[]): any;
export function createLightingStylePresetDocument(...args: any[]): any;
export function createLightingStyleSettings(...args: any[]): any;
export function createLightingSystem(...args: any[]): any;
export function createLocalLightSettings(...args: any[]): any;
export function createLocomotionActions(...args: any[]): any;
export function createLocomotionStateMachine(...args: any[]): any;
export function createManufacturedMaterialClassification(...args: any[]): any;
export function createManufacturedMaterialLook(...args: any[]): any;
export function createMaterialMapSettings(...args: any[]): any;
export function createMoonAlbedoData(...args: any[]): any;
export function createMoonAlbedoTexture(...args: any[]): any;
export function createNightSky(...args: any[]): any;
export function createNoisePatchMask(...args: any[]): any;
export function createOfficialCatalogAssetRuntime(...args: any[]): any;
export function createOfficialCatalogProvider(...args: any[]): any;
export function createOrganLeafSpriteTexture(...args: any[]): any;
export function createOssStyleBundleProvider(...args: any[]): any;
export function createOutlineSettings(...args: any[]): any;
export function createPerspectiveRemovalSettings(...args: any[]): any;
export function createPointLightDescriptor(...args: any[]): any;
export function createPostGeneratorRecipe(...args: any[]): any;
export function createPostProcessingPipeline(...args: any[]): any;
export function createPostProcessingPresetDocument(...args: any[]): any;
export function createPostProcessingSettings(...args: any[]): any;
export function createRapierCollisionAdapter(...args: any[]): any;
export function createRectAreaLightDescriptor(...args: any[]): any;
export function createReferenceRockLodPolicy(...args: any[]): any;
export function createReferenceRockLodPolicyForDocument(...args: any[]): any;
export function createRimLightSettings(...args: any[]): any;
export function createRockColumnsSettings(...args: any[]): any;
export function createRockCracksSettings(...args: any[]): any;
export function createRockCutsSettings(...args: any[]): any;
export function createRockDocument(...args: any[]): any;
export function createRockFacetSettings(...args: any[]): any;
export function createRockFalloffSettings(...args: any[]): any;
export function createRockHeightfieldSettings(...args: any[]): any;
export function createRockLodObject(...args: any[]): any;
export function createRockLodTriangleTargets(...args: any[]): any;
export function createRockNoiseSettings(...args: any[]): any;
export function createRockPiece(...args: any[]): any;
export function createRockPieceSettings(...args: any[]): any;
export function createRockReferenceIdentity(...args: any[]): any;
export function createRockShaderMaterial(...args: any[]): any;
export function createRockShaderPresetDocument(...args: any[]): any;
export function createRockShaderSettings(...args: any[]): any;
export function createRockShapeSettings(...args: any[]): any;
export function createRockStrataSettings(...args: any[]): any;
export function createRockSurfaceSettings(...args: any[]): any;
export function createRockWarpSettings(...args: any[]): any;
export function createRockgenMeshingSettings(...args: any[]): any;
export function createSceneCollisionRuntime(...args: any[]): any;
export function createSceneContentDocument(...args: any[]): any;
export function createSceneOverrideDocument(...args: any[]): any;
export function createSceneQualityDocument(...args: any[]): any;
export function createSceneQualityProfile(...args: any[]): any;
export function createSceneScenarioDocument(...args: any[]): any;
export function createSceneShadowSettings(...args: any[]): any;
export function createSceneStyleRuntime(...args: any[]): any;
export function createSceneSurfaceRuntime(...args: any[]): any;
export function createSceneUpdateScheduler(...args: any[]): any;
export function createSelfShadowSettings(...args: any[]): any;
export function createShadowColorSettings(...args: any[]): any;
export function createShadowPolicy(...args: any[]): any;
export function createSkinToneSettings(...args: any[]): any;
export function createSkyAtmosphereSettings(...args: any[]): any;
export function createSkyColorParams(...args: any[]): any;
export function createSkyDayCycle(...args: any[]): any;
export function createSkyMaterial(...args: any[]): any;
export function createSkyParams(...args: any[]): any;
export function createSkyParamsDocument(...args: any[]): any;
export function createSkyPresetDocument(...args: any[]): any;
export function createSkySettings(...args: any[]): any;
export function createSkyShaderPresetDocument(...args: any[]): any;
export function createSkyShaderSettings(...args: any[]): any;
export function createSkySystem(...args: any[]): any;
export function createSkyTimeKeyframes(...args: any[]): any;
export function createSlopeMask(...args: any[]): any;
export function createSpecularSettings(...args: any[]): any;
export function createSpotLightDescriptor(...args: any[]): any;
export function createStickerSettings(...args: any[]): any;
export function createStrokeEdit(...args: any[]): any;
export function createStyleBundleDocument(...args: any[]): any;
export function createStyleBundleProvider(...args: any[]): any;
export function createStyleMaterialContract(...args: any[]): any;
export function createStyleTarget(...args: any[]): any;
export function createStyleTargetLabel(...args: any[]): any;
export function createStylizedTreeSettings(...args: any[]): any;
export function createSun(...args: any[]): any;
export function createSunBeamMaterial(...args: any[]): any;
export function createSunDiskMaterial(...args: any[]): any;
export function createSunDriver(...args: any[]): any;
export function createSunShaftMaterial(...args: any[]): any;
export function createSunSpillMaterial(...args: any[]): any;
export function createSurfaceWeightMask(...args: any[]): any;
export function createTimeOfDay(...args: any[]): any;
export function createToonLabBasicMaterialFromPbr(...args: any[]): any;
export function createToonLabInspector(...args: any[]): any;
export function createToonLabMountainMaterial(...args: any[]): any;
export function createToonLabRendererOptions(...args: any[]): any;
export function createToonLabRendererProfile(...args: any[]): any;
export function createToonLabRockMaterialIndex(...args: any[]): any;
export function createToonLabSourceEnvironmentState(...args: any[]): any;
export function createToonLabSourceMaterial(...args: any[]): any;
export function createToonLabSourceMaterialFromProfile(...args: any[]): any;
export function createToonPresetDocument(...args: any[]): any;
export function createToonRockMaterial(...args: any[]): any;
export function createToonSettings(...args: any[]): any;
export function createTreeFoliageGeometry(...args: any[]): any;
export function createTreeFoliageMaterials(...args: any[]): any;
export function createTreeLeafNodeMaterial(...args: any[]): any;
export function createTreeShaderPresetDocument(...args: any[]): any;
export function createTreeShaderSettings(...args: any[]): any;
export function createTreeSkeleton(...args: any[]): any;
export function createTreeSurfaceTexture(...args: any[]): any;
export function createTreeSurfaceTextureData(...args: any[]): any;
export function createTreeTrunkGeometry(...args: any[]): any;
export function createTubeAreaLightDescriptor(...args: any[]): any;
export function createUserStyleBundleProvider(...args: any[]): any;
export function createVegetationShaderPresetDocument(...args: any[]): any;
export function createVegetationShaderScopePresetDocument(...args: any[]): any;
export function createVegetationShaderScopeSettings(...args: any[]): any;
export function createVegetationShaderSettings(...args: any[]): any;
export function createVegetationSharedShaderSettings(...args: any[]): any;
export function createWalkableCharacterRuntime(...args: any[]): any;
export function createWalkableCharacterSlot(...args: any[]): any;
export function createWaterInteractionController(...args: any[]): any;
export function createWaterMask(...args: any[]): any;
export function createWaterMaterial(...args: any[]): any;
export function createWaterPresetDocument(...args: any[]): any;
export function createWaterSettings(...args: any[]): any;
export function createWaterShoreMaterial(...args: any[]): any;
export function createWaterUnderwaterAtmosphereOptions(...args: any[]): any;
export function createWeatherMap(...args: any[]): any;
export function createWeatherMapData(...args: any[]): any;
export function createWeatherMapProfile(...args: any[]): any;
export function createWoodySurfaceNodeMaterial(...args: any[]): any;
export function createWorldCollision(...args: any[]): any;
export function curlNoiseOffsetNode(...args: any[]): any;
export function dayCycleProgressFromTime(...args: any[]): any;
export function decodeCurlNoise(...args: any[]): any;
export function deriveCanopyPalette(...args: any[]): any;
export function deserializeLightingLook(...args: any[]): any;
export function deserializeLightingLookPreset(...args: any[]): any;
export function deserializeLightingRecipe(...args: any[]): any;
export function deserializeRockDocument(...args: any[]): any;
export function detectEnvironmentFloorY(...args: any[]): any;
export function detectToonLabRendererBackend(...args: any[]): any;
export function directionFromAngles(...args: any[]): any;
export function disposeCloudBaseShapeVolumes(...args: any[]): any;
export function disposeCloudCirrusMaps(...args: any[]): any;
export function disposeCloudErosionVolumes(...args: any[]): any;
export function disposeCompatibilityGroundShaderMaterial(...args: any[]): any;
export function disposeCurlNoiseVolumes(...args: any[]): any;
export function disposeDefaultRockShaderTextures(...args: any[]): any;
export function disposeExportGroup(...args: any[]): any;
export function disposeGroundShaderMaterial(...args: any[]): any;
export function disposeMoonAlbedoTextures(...args: any[]): any;
export function disposeWeatherMaps(...args: any[]): any;
export function downloadArrayBuffer(...args: any[]): any;
export function elevationOf(...args: any[]): any;
export function enforceWaterInteractionFrame(...args: any[]): any;
export function ensureAreaLightSupport(...args: any[]): any;
export function environmentBackdropPeriodForHour(...args: any[]): any;
export function environmentRelativePoint(...args: any[]): any;
export function environmentSourceOpacity(...args: any[]): any;
export const environmentStateUniforms: any;
export function environmentUsesAlphaCutout(...args: any[]): any;
export function erodeHeightfield(...args: any[]): any;
export function erodeHeightfieldStylized(...args: any[]): any;
export function estimateSurfaceNetsResolution(...args: any[]): any;
export function evaluateAssetCandidate(...args: any[]): any;
export function evaluateField(...args: any[]): any;
export function evaluateSculptEdit(...args: any[]): any;
export function exportDocumentToGLB(...args: any[]): any;
export function exportGeometryToGLB(...args: any[]): any;
export function exportLightingRecipeToToonLab(...args: any[]): any;
export function exposePoseDebug(...args: any[]): any;
export function extractBreakLineChains(...args: any[]): any;
export const fallbackEnvironmentBlackTexture: any;
export const fallbackEnvironmentNormalTexture: any;
export const fallbackEnvironmentWhiteTexture: any;
export function fetchStyleBundle(...args: any[]): any;
export function findCloudLayerCrossing(...args: any[]): any;
export function findPrimarySkinnedMesh(...args: any[]): any;
export function finiteDepthWaveNumberRatio(...args: any[]): any;
export function fitModelForController(...args: any[]): any;
export function fiveStopCurve(...args: any[]): any;
export function getAreaLightSupportState(...args: any[]): any;
export function getCloudBaseShapeVolume(...args: any[]): any;
export function getCloudCirrusMap(...args: any[]): any;
export function getCloudErosionVolume(...args: any[]): any;
export function getCloudStyleSnapshotOptions(...args: any[]): any;
export function getCurlNoiseVolume(...args: any[]): any;
export function getDefaultIntensityUnit(...args: any[]): any;
export function getEnvironmentPresetOptions(...args: any[]): any;
export function getEnvironmentScenarioOptions(...args: any[]): any;
export function getEnvironmentState(...args: any[]): any;
export function getFirstPartyStyleBundle(...args: any[]): any;
export function getFlowerPresetOptions(...args: any[]): any;
export function getGeometryBounds(...args: any[]): any;
export function getGeometryTriangleCount(...args: any[]): any;
export function getGrassPresetOptions(...args: any[]): any;
export function getGroundShaderPresetOptions(...args: any[]): any;
export function getHeroCloudPreviewCenter(...args: any[]): any;
export function getLegacyTreePreset(...args: any[]): any;
export function getLegacyTreePresetOptions(...args: any[]): any;
export function getLightFixtureGeneratorFamilyOptions(...args: any[]): any;
export function getLightFixtureOptions(...args: any[]): any;
export function getLightingPresetOptions(...args: any[]): any;
export function getLightingStyleGeneratorFamilyOptions(...args: any[]): any;
export function getLightingStylePresetOptions(...args: any[]): any;
export function getLightingTypeCapability(...args: any[]): any;
export function getMoonAlbedoTexture(...args: any[]): any;
export function getPostGeneratorFamilyOptions(...args: any[]): any;
export function getPostProcessingPresetOptions(...args: any[]): any;
export function getRenderLayer(...args: any[]): any;
export function getRockShaderPresetOptions(...args: any[]): any;
export function getRockgenPresetOptions(...args: any[]): any;
export function getRockgenStyleOptions(...args: any[]): any;
export function getSceneQualityProfileOptions(...args: any[]): any;
export function getSkyPresetOptions(...args: any[]): any;
export function getSkyScenarioOptions(...args: any[]): any;
export function getSkyShaderPresetOptions(...args: any[]): any;
export function getSkyStyleSnapshotOptions(...args: any[]): any;
export function getStylizedTreePresetOptions(...args: any[]): any;
export function getToonPresetDefinition(...args: any[]): any;
export function getToonPresetIds(...args: any[]): any;
export function getToonPresetMetadata(...args: any[]): any;
export function getToonPresetOptions(...args: any[]): any;
export function getToonSettingFieldSchema(...args: any[]): any;
export function getToonSettingGroupMetadata(...args: any[]): any;
export function getTreeSurfaceProfileOptions(...args: any[]): any;
export function getVegetationMaterialContract(...args: any[]): any;
export function getVegetationShaderPresetOptions(...args: any[]): any;
export function getVegetationShaderScopeExcludedFields(...args: any[]): any;
export function getVegetationShaderScopeFieldSchema(...args: any[]): any;
export function getVegetationShaderScopeSettingGroups(...args: any[]): any;
export function getWaterPresetOptions(...args: any[]): any;
export function getWaterScenarioOptions(...args: any[]): any;
export function getWaterStyleOptions(...args: any[]): any;
export function getWeatherMap(...args: any[]): any;
export function hashGeometry(...args: any[]): any;
export function henyeyGreensteinPhaseNode(...args: any[]): any;
export function heroCloudSkyOverrides(...args: any[]): any;
export function hourFromDayCycleTime(...args: any[]): any;
export function inferManufacturedObjectClass(...args: any[]): any;
export function inspectToonLabLandscapeWeightmapSet(...args: any[]): any;
export function intersectCloudShell(...args: any[]): any;
export function isAoOverlayMaterial(...args: any[]): any;
export function isEmissiveEnvironmentMaterial(...args: any[]): any;
export function isEnvironmentAoOverlay(...args: any[]): any;
export function isEnvironmentShadowMesh(...args: any[]): any;
export function isFoliageMaterial(...args: any[]): any;
export function isPostProcessingEnabled(...args: any[]): any;
export function isRockHelperPiece(...args: any[]): any;
export function isScanAssetMaterial(...args: any[]): any;
export function isUtilityTextureLabel(...args: any[]): any;
export function isVegetationSharedShaderGroup(...args: any[]): any;
export function isWindowCutoutMaterial(...args: any[]): any;
export function labelManufacturedStyleTarget(...args: any[]): any;
export function labelStyleTarget(...args: any[]): any;
export function layoutTreeRow(...args: any[]): any;
export function listFirstPartyStyleBundles(...args: any[]): any;
export function listSurfaceMaterialModes(...args: any[]): any;
export function loadAsync(...args: any[]): any;
export function loadCallMeSenseiGrassClump(...args: any[]): any;
export function loadCompiledTreeAsset(...args: any[]): any;
export function loadEnvironmentTexture(...args: any[]): any;
export function loadIdleClipForTarget(...args: any[]): any;
export function loadJumpClipForTarget(...args: any[]): any;
export function loadOfficialCatalogAsset(...args: any[]): any;
export function loadPackagedLocomotionClipsForTarget(...args: any[]): any;
export function loadRetargetedMixamoClipForTarget(...args: any[]): any;
export function loadRunningClipForTarget(...args: any[]): any;
export function loadSitClipForTarget(...args: any[]): any;
export function loadSwimClipForTarget(...args: any[]): any;
export function loadToonLabMountainMaterial(...args: any[]): any;
export function loadToonLabRockMaterialIndex(...args: any[]): any;
export function loadToonLabRockMaterialLibrary(...args: any[]): any;
export function loadToonLabSourceLibrary(...args: any[]): any;
export function loadToonRockMaterial(...args: any[]): any;
export function loadToonRockMaterialInputs(...args: any[]): any;
export function loadWalkingClipForTarget(...args: any[]): any;
export function lumensToCandela(...args: any[]): any;
export function lumensToNits(...args: any[]): any;
export function luxAtDistance(...args: any[]): any;
export function marchCloud(...args: any[]): any;
export function matchCloudStyleSnapshot(...args: any[]): any;
export function matchGrassColorPalette(...args: any[]): any;
export function matchRockGeometryBounds(...args: any[]): any;
export function matchSkyStyleSnapshot(...args: any[]): any;
export function materialBaseColor(...args: any[]): any;
export function materialRoleName(...args: any[]): any;
export function materialRoleValue(...args: any[]): any;
export function materialText(...args: any[]): any;
export function materialUsesFur(...args: any[]): any;
export function mergeLightDescriptor(...args: any[]): any;
export function mergeVegetationSharedShaderSettings(...args: any[]): any;
export function meshDocument(...args: any[]): any;
export function migrateLegacyVegetationShaderDocuments(...args: any[]): any;
export function migrateStyleBundleDocument(...args: any[]): any;
export function migrateStyleTargetLabel(...args: any[]): any;
export function moonAmbientRadianceNode(...args: any[]): any;
export function moonDirectionAt(...args: any[]): any;
export function moonDiscRadianceNode(...args: any[]): any;
export function moonPhaseTerms(...args: any[]): any;
export function moonSurfaceUVNode(...args: any[]): any;
export function normalizeCatalogLodDistances(...args: any[]): any;
export function normalizeCloudParams(...args: any[]): any;
export function normalizeCloudStyleParams(...args: any[]): any;
export function normalizeEnvironmentDebugMode(...args: any[]): any;
export function normalizeEnvironmentPresetName(...args: any[]): any;
export function normalizeMaterialRole(...args: any[]): any;
export function normalizeMaterialRoleOverrides(...args: any[]): any;
export function normalizeMixamoBoneName(...args: any[]): any;
export function normalizeOfficialCatalogAsset(...args: any[]): any;
export function normalizeRockLodDistances(...args: any[]): any;
export function normalizeRockShaderPresetName(...args: any[]): any;
export function normalizeRockgenPresetName(...args: any[]): any;
export function normalizeRockgenStyleName(...args: any[]): any;
export function normalizeSkyColorParams(...args: any[]): any;
export function normalizeToonLabLandscapeWeightManifest(...args: any[]): any;
export function normalizeToonLabMountainProfile(...args: any[]): any;
export function normalizeToonLabRockMaterialLibrarySchema(...args: any[]): any;
export function normalizeToonLabRockMaterialReference(...args: any[]): any;
export function normalizeToonLabRockProfile(...args: any[]): any;
export function normalizeToonLabSourceManifestSchema(...args: any[]): any;
export function normalizeToonPresetName(...args: any[]): any;
export function objectMaterialText(...args: any[]): any;
export function parseBranchTreeDocument(...args: any[]): any;
export function parseCompiledTreeManifest(...args: any[]): any;
export function parseFlowerShaderProfilePresetDocument(...args: any[]): any;
export function parseGrassPresetDocument(...args: any[]): any;
export function parseGrassShaderProfilePresetDocument(...args: any[]): any;
export function parseGroundShaderPresetDocument(...args: any[]): any;
export function parseHeroCloudRecipe(...args: any[]): any;
export function parseLightFixtureDocument(...args: any[]): any;
export function parseLightFixtureGeneratorRecipe(...args: any[]): any;
export function parseLightingStyleGeneratorRecipe(...args: any[]): any;
export function parseLightingStylePresetDocument(...args: any[]): any;
export function parsePostGeneratorRecipe(...args: any[]): any;
export function parseRockShaderPresetDocument(...args: any[]): any;
export function parseSceneContentDocument(...args: any[]): any;
export function parseSceneOverrideDocument(...args: any[]): any;
export function parseSceneQualityDocument(...args: any[]): any;
export function parseSceneQualityProfile(...args: any[]): any;
export function parseSceneScenarioDocument(...args: any[]): any;
export function parseSkyParams(...args: any[]): any;
export function parseSkyParamsDocument(...args: any[]): any;
export function parseSkyPresetDocument(...args: any[]): any;
export function parseSkyShaderPresetDocument(...args: any[]): any;
export function parseStyleBundleDocument(...args: any[]): any;
export function parseStyleMaterialContract(...args: any[]): any;
export function parseStyleTargetLabel(...args: any[]): any;
export function parseToonPresetDocument(...args: any[]): any;
export function parseTreeShaderPresetDocument(...args: any[]): any;
export function parseVegetationShaderPresetDocument(...args: any[]): any;
export function parseVegetationShaderScopePresetDocument(...args: any[]): any;
export function parseWaterPresetDocument(...args: any[]): any;
export function placeInLayer(...args: any[]): any;
export function planRockLodMeshes(...args: any[]): any;
export function polarProfileFromOutline(...args: any[]): any;
export function powderNode(...args: any[]): any;
export function prepareGeometryForExport(...args: any[]): any;
export function prepareModelForRealtime(...args: any[]): any;
export function prepareTreeForExport(...args: any[]): any;
export function projectedTreeScreenCoverage(...args: any[]): any;
export function proposeManufacturedStyleTargetLabel(...args: any[]): any;
export function rasterizeHeroCloudFootprint(...args: any[]): any;
export function rayleighPhaseNode(...args: any[]): any;
export function readStyleTargetLabel(...args: any[]): any;
export function realizeLightingRecipe(...args: any[]): any;
export function rebaseRockDocumentStyle(...args: any[]): any;
export function rebaseWaterSettingsStyle(...args: any[]): any;
export function registerCollisionTarget(...args: any[]): any;
export function registerEnvironmentPreset(...args: any[]): any;
export function registerEnvironmentPresetDocument(...args: any[]): any;
export function registerFlowerPreset(...args: any[]): any;
export function registerGrassPreset(...args: any[]): any;
export function registerGroundShaderPreset(...args: any[]): any;
export function registerLightFixture(...args: any[]): any;
export function registerLightFixtureDocument(...args: any[]): any;
export function registerLightFixtureGeneratorFamily(...args: any[]): any;
export function registerLightingStyleGeneratorFamily(...args: any[]): any;
export function registerLightingStylePreset(...args: any[]): any;
export function registerLightingStylePresetDocument(...args: any[]): any;
export function registerPostGeneratorFamily(...args: any[]): any;
export function registerPostProcessingPreset(...args: any[]): any;
export function registerRockShaderPreset(...args: any[]): any;
export function registerRockgenPreset(...args: any[]): any;
export function registerRockgenStyle(...args: any[]): any;
export function registerSerializedGrassPreset(...args: any[]): any;
export function registerSerializedGroundShaderPreset(...args: any[]): any;
export function registerSerializedSkyPreset(...args: any[]): any;
export function registerSerializedSkyShaderPreset(...args: any[]): any;
export function registerSerializedToonPreset(...args: any[]): any;
export function registerSerializedVegetationShaderPreset(...args: any[]): any;
export function registerSerializedWaterPreset(...args: any[]): any;
export function registerSkyPreset(...args: any[]): any;
export function registerSkyShaderPreset(...args: any[]): any;
export function registerStylizedTreePreset(...args: any[]): any;
export function registerSurfaceMaterialMode(...args: any[]): any;
export function registerToonPreset(...args: any[]): any;
export function registerVegetationShaderPreset(...args: any[]): any;
export function registerWaterPreset(...args: any[]): any;
export function registerWaterStyle(...args: any[]): any;
export function rehydrateToonLabSourceMaterialLighting(...args: any[]): any;
export function removePieceFromDocument(...args: any[]): any;
export function removeStyleTargetLabel(...args: any[]): any;
export function renderAssetGapReport(...args: any[]): any;
export function repairToonLabAuthoredBakeMaterials(...args: any[]): any;
export function requireToonLabRockMaterial(...args: any[]): any;
export function resetEnvironmentShaderTime(...args: any[]): any;
export function resetLocomotionActions(...args: any[]): any;
export function resolveAlphaForMaterial(...args: any[]): any;
export function resolveAverageShadowForMaterial(...args: any[]): any;
export function resolveCanopyColor(...args: any[]): any;
export function resolveCatalogLicense(...args: any[]): any;
export function resolveCatalogLodDistancesForQuality(...args: any[]): any;
export function resolveCatalogQualityOptions(...args: any[]): any;
export function resolveCharacterRig(...args: any[]): any;
export function resolveCloudStyleSnapshot(...args: any[]): any;
export function resolveContactShadowForMaterial(...args: any[]): any;
export function resolveEnvironmentPreset(...args: any[]): any;
export function resolveEnvironmentTextureSet(...args: any[]): any;
export function resolveEyeHighlightForMaterial(...args: any[]): any;
export function resolveFixturePlacement(...args: any[]): any;
export function resolveGlitterForMaterial(...args: any[]): any;
export function resolveGrassColorPalette(...args: any[]): any;
export function resolveGroundShaderPreset(...args: any[]): any;
export function resolveHairHighlightForMaterial(...args: any[]): any;
export function resolveIndirectLightForMaterial(...args: any[]): any;
export function resolveLightColor(...args: any[]): any;
export function resolveLightFixture(...args: any[]): any;
export function resolveLightFixtureGeneratorRecipe(...args: any[]): any;
export function resolveLightingLookPreset(...args: any[]): any;
export function resolveLightingPreset(...args: any[]): any;
export function resolveLightingQualityPreset(...args: any[]): any;
export function resolveLightingRigPreset(...args: any[]): any;
export function resolveLightingStyleGeneratorRecipe(...args: any[]): any;
export function resolveLightingStylePreset(...args: any[]): any;
export function resolveLocalLightForMaterial(...args: any[]): any;
export function resolveLuminairePreset(...args: any[]): any;
export function resolveManufacturedMaterialLook(...args: any[]): any;
export function resolveMarchBudget(...args: any[]): any;
export function resolveNativeLocomotionClips(...args: any[]): any;
export function resolveOfficialCatalogUrl(...args: any[]): any;
export function resolveOutlineForMaterial(...args: any[]): any;
export function resolvePostGeneratorRecipe(...args: any[]): any;
export function resolveQuality(...args: any[]): any;
export function resolveQualityLevelName(...args: any[]): any;
export function resolveReferenceRockLodPolicy(...args: any[]): any;
export function resolveRimLightForMaterial(...args: any[]): any;
export function resolveRockgenPreset(...args: any[]): any;
export function resolveRockgenQuality(...args: any[]): any;
export function resolveSceneLook(...args: any[]): any;
export function resolveSceneQualityProfile(...args: any[]): any;
export function resolveSceneShadowForMaterial(...args: any[]): any;
export function resolveSelfShadowForMaterial(...args: any[]): any;
export function resolveSkyQuality(...args: any[]): any;
export function resolveSkyQualityOptions(...args: any[]): any;
export function resolveSkyStyleName(...args: any[]): any;
export function resolveSkyStyleSnapshot(...args: any[]): any;
export function resolveSkySystemStyleSnapshot(...args: any[]): any;
export function resolveSpecularForMaterial(...args: any[]): any;
export function resolveStickerForMaterial(...args: any[]): any;
export function resolveStyleBundleSelection(...args: any[]): any;
export function resolveStyleBundleSettings(...args: any[]): any;
export function resolveStyleTargetAdapter(...args: any[]): any;
export function resolveSurfaceMaterialFamily(...args: any[]): any;
export function resolveSurfaceMaterialMode(...args: any[]): any;
export function resolveThreeLightIntensity(...args: any[]): any;
export function resolveToonDebugOutputMode(...args: any[]): any;
export function resolveToonLabRockMaterial(...args: any[]): any;
export function resolveToonLabRockProfile(...args: any[]): any;
export function resolveToonLabShaderSwipeBaseline(...args: any[]): any;
export function resolveTreeDitherMode(...args: any[]): any;
export function resolveVegetationQualityOptions(...args: any[]): any;
export function resolveVegetationShaderPreset(...args: any[]): any;
export function resolveVegetationShaderRoleSettings(...args: any[]): any;
export function resolveWaterColorToneName(...args: any[]): any;
export function resolveWaterDebugMode(...args: any[]): any;
export function resolveWaterPresetName(...args: any[]): any;
export function resolveWaterQualityDefines(...args: any[]): any;
export function resolveWaterQualityOptions(...args: any[]): any;
export function resolveWaterStyleName(...args: any[]): any;
export function resolveWaterUnderwaterAtmosphereState(...args: any[]): any;
export function resolveWeatherMapResolution(...args: any[]): any;
export function restoreRockShader(...args: any[]): any;
export function restoreStyleTargetSnapshot(...args: any[]): any;
export function rockShaderSettingsToProfile(...args: any[]): any;
export function roleIsCatchlight(...args: any[]): any;
export function roleIsEye(...args: any[]): any;
export function roleIsEyeHighlight(...args: any[]): any;
export function roleIsIris(...args: any[]): any;
export function roleIsPupil(...args: any[]): any;
export function roleIsSclera(...args: any[]): any;
export function runSceneStyleOperation(...args: any[]): any;
export function sampleCloudCirrusDensity(...args: any[]): any;
export function sampleDayCurve(...args: any[]): any;
export function sampleEnvironmentTimeOfDay(...args: any[]): any;
export function sampleGerstnerHeight(...args: any[]): any;
export function sampleGerstnerSwellHeight(...args: any[]): any;
export function sampleLightingStyle(...args: any[]): any;
export function sampleNearshorePhaseField(...args: any[]): any;
export function samplePrimarySwellCycle(...args: any[]): any;
export function samplePrimarySwellSequence(...args: any[]): any;
export function sampleSkyTimeKeyframes(...args: any[]): any;
export function sampleSwashCycleVariation(...args: any[]): any;
export function sampleSwashDistance(...args: any[]): any;
export function sampleSwashEdgeOffset(...args: any[]): any;
export function sampleSwashEventShape(...args: any[]): any;
export function sampleSwashFrameState(...args: any[]): any;
export function sanitizeEnvironmentPreset(...args: any[]): any;
export function sanitizeGrassPresetSettings(...args: any[]): any;
export function sanitizeLightFixtureSettings(...args: any[]): any;
export function sanitizeLightingStyleSettings(...args: any[]): any;
export function sanitizePostProcessingPresetSettings(...args: any[]): any;
export function sanitizeSkyPresetSettings(...args: any[]): any;
export function sanitizeToonPresetSettings(...args: any[]): any;
export function sanitizeWaterPresetSettings(...args: any[]): any;
export function scatterForest(...args: any[]): any;
export function scatterGrassAround(...args: any[]): any;
export function scatterInRect(...args: any[]): any;
export function scatterOnSurface(...args: any[]): any;
export function scatterUnderstory(...args: any[]): any;
export function sceneCollisionRuntimeFor(...args: any[]): any;
export function sculptEditBounds(...args: any[]): any;
export function searchSurfaceNetsResolution(...args: any[]): any;
export function selectCatalogLodLevel(...args: any[]): any;
export function serializableTreeOptions(...args: any[]): any;
export function serializeGrassPreset(...args: any[]): any;
export function serializeGroundShaderPreset(...args: any[]): any;
export function serializeHeroCloudRecipe(...args: any[]): any;
export function serializeLightFixtureDocument(...args: any[]): any;
export function serializeLightFixtureGeneratorRecipe(...args: any[]): any;
export function serializeLightingLook(...args: any[]): any;
export function serializeLightingLookPreset(...args: any[]): any;
export function serializeLightingRecipe(...args: any[]): any;
export function serializeLightingStyleGeneratorRecipe(...args: any[]): any;
export function serializeLightingStylePresetDocument(...args: any[]): any;
export function serializePostGeneratorRecipe(...args: any[]): any;
export function serializeResolvedSceneLook(...args: any[]): any;
export function serializeRockDocument(...args: any[]): any;
export function serializeRockShaderPreset(...args: any[]): any;
export function serializeSceneContentDocument(...args: any[]): any;
export function serializeSceneOverrideDocument(...args: any[]): any;
export function serializeSceneQualityDocument(...args: any[]): any;
export function serializeSceneQualityProfile(...args: any[]): any;
export function serializeSceneScenarioDocument(...args: any[]): any;
export function serializeSceneStyleAudit(...args: any[]): any;
export function serializeSkyParams(...args: any[]): any;
export function serializeSkyParamsDocument(...args: any[]): any;
export function serializeSkyPreset(...args: any[]): any;
export function serializeSkyShaderPreset(...args: any[]): any;
export function serializeStyleBundle(...args: any[]): any;
export function serializeStyleMaterialContract(...args: any[]): any;
export function serializeStyleTargetLabel(...args: any[]): any;
export function serializeToonLabLightingManifest(...args: any[]): any;
export function serializeToonPreset(...args: any[]): any;
export function serializeVegetationShaderPreset(...args: any[]): any;
export function serializeVegetationShaderScopePreset(...args: any[]): any;
export function serializeWaterPreset(...args: any[]): any;
export function setCanopyCloudShadow(...args: any[]): any;
export function setCanopySceneShadow(...args: any[]): any;
export function setCanopySun(...args: any[]): any;
export function setCanopyWind(...args: any[]): any;
export function setCompatibilityGroundShaderSceneState(...args: any[]): any;
export function setEnvironmentAmbientProbeColors(...args: any[]): any;
export function setEnvironmentCloudShadow(...args: any[]): any;
export function setEnvironmentDebugOutput(...args: any[]): any;
export function setEnvironmentOpenings(...args: any[]): any;
export function setEnvironmentPlanarReflection(...args: any[]): any;
export function setEnvironmentPlayer(...args: any[]): any;
export function setEnvironmentState(...args: any[]): any;
export function setGlobalWind(...args: any[]): any;
export function setGroundShaderPrintLayer(...args: any[]): any;
export function setGroundShaderSceneState(...args: any[]): any;
export function setLocomotionActionWeights(...args: any[]): any;
export function setObjectTextureColorSpaces(...args: any[]): any;
export function setRockShaderSceneState(...args: any[]): any;
export function setToonDebugOutput(...args: any[]): any;
export function setToonDitherOpacity(...args: any[]): any;
export function setWaterDebugMode(...args: any[]): any;
export function setWoodySurfaceSun(...args: any[]): any;
export function shapeSwashProgress(...args: any[]): any;
export function shouldUseDedicatedBreakerShell(...args: any[]): any;
export function simplifyRockGeometryToTriangleBudget(...args: any[]): any;
export function skyColorParamsToLive(...args: any[]): any;
export function skyDarknessFor(...args: any[]): any;
export function snapshotLightingCapabilities(...args: any[]): any;
export function snapshotSkeletonLocalPose(...args: any[]): any;
export function solveFiniteDepthWaveNumber(...args: any[]): any;
export function stabilizeToonLabWebGPUResourceLifetime(...args: any[]): any;
export function starPanoramaUVNode(...args: any[]): any;
export function starRadianceNode(...args: any[]): any;
export function starRotationAt(...args: any[]): any;
export function stylizeScanBaseMap(...args: any[]): any;
export function summarizeRockLodPlan(...args: any[]): any;
export function sunDirectionAt(...args: any[]): any;
export function sunHorizonFade(...args: any[]): any;
export function syncFoliageFog(...args: any[]): any;
export function tagVegetationMaterial(...args: any[]): any;
export function targetBoneNameForRole(...args: any[]): any;
export function targetBoneNamesForRole(...args: any[]): any;
export function textureKindCandidateUrl(...args: any[]): any;
export function textureLabel(...args: any[]): any;
export function textureSourceUrl(...args: any[]): any;
export function textureUrlExists(...args: any[]): any;
export function threePositionToToonLab(...args: any[]): any;
export function tickCanopyTime(...args: any[]): any;
export function timeStyleWeightsFor(...args: any[]): any;
export function toMaterialArray(...args: any[]): any;
export function toSerializableCloudStyleParams(...args: any[]): any;
export function toSerializableSkyColorParams(...args: any[]): any;
export function toSerializableSkyParams(...args: any[]): any;
export function toonLabMountainProfileFromResolvedMaterial(...args: any[]): any;
export function toonLabRockProfileFromResolvedMaterial(...args: any[]): any;
export function toonLabScalar(...args: any[]): any;
export function toonLabSwitch(...args: any[]): any;
export function toonLabTexturePath(...args: any[]): any;
export function toonLabVector(...args: any[]): any;
export function toonSourceOpacity(...args: any[]): any;
export function toonUsesAlphaCutout(...args: any[]): any;
export function traceLeafShapePath(...args: any[]): any;
export function undoLastSculptEdit(...args: any[]): any;
export function unregisterGrassPreset(...args: any[]): any;
export function updateCallMeSenseiSkyLightProbe(...args: any[]): any;
export function updateEnvironmentBoundsUniforms(...args: any[]): any;
export function updateToonLabSourceEnvironmentState(...args: any[]): any;
export function updateWaterMaterialCamera(...args: any[]): any;
export function updateWaterShoreMaterial(...args: any[]): any;
export function usesAlphaBlend(...args: any[]): any;
export function validateAssetSourcingPolicy(...args: any[]): any;
export function validateCollisionMetadata(...args: any[]): any;
export function validateCompiledTreeManifest(...args: any[]): any;
export function validateEnvironmentPresetDocument(...args: any[]): any;
export function validateGrassPresetDocument(...args: any[]): any;
export function validateGroundShaderPresetDocument(...args: any[]): any;
export function validateLightDescriptor(...args: any[]): any;
export function validateLightFixtureDocument(...args: any[]): any;
export function validateLightFixtureGeneratorRecipe(...args: any[]): any;
export function validateLightingLook(...args: any[]): any;
export function validateLightingLookPreset(...args: any[]): any;
export function validateLightingRecipe(...args: any[]): any;
export function validateLightingStyleGeneratorRecipe(...args: any[]): any;
export function validateLightingStylePresetDocument(...args: any[]): any;
export function validateManufacturedMaterialLook(...args: any[]): any;
export function validateManufacturedMaterialManifest(...args: any[]): any;
export function validatePostGeneratorRecipe(...args: any[]): any;
export function validatePostProcessingPresetDocument(...args: any[]): any;
export function validateRockLodLevels(...args: any[]): any;
export function validateSceneContentDocument(...args: any[]): any;
export function validateSceneOverrideDocument(...args: any[]): any;
export function validateSceneQualityDocument(...args: any[]): any;
export function validateSceneQualityProfile(...args: any[]): any;
export function validateSceneScenarioDocument(...args: any[]): any;
export function validateSceneStyleManifest(...args: any[]): any;
export function validateSkyParams(...args: any[]): any;
export function validateSkyParamsDocument(...args: any[]): any;
export function validateSkyPresetDocument(...args: any[]): any;
export function validateSkyShaderPresetDocument(...args: any[]): any;
export function validateStyleBundleDocument(...args: any[]): any;
export function validateStyleMaterialContract(...args: any[]): any;
export function validateStyleTargetLabel(...args: any[]): any;
export function validateToonPresetDocument(...args: any[]): any;
export function validateVegetationShaderPresetDocument(...args: any[]): any;
export function validateVegetationShaderScopePresetDocument(...args: any[]): any;
export function validateWaterPresetDocument(...args: any[]): any;
export function visibilityForTurbidity(...args: any[]): any;
export function waitForObjectTextures(...args: any[]): any;
export function waitForTexture(...args: any[]): any;
export function waterStageOverrides(...args: any[]): any;
export function wrapDayTime(...args: any[]): any;
