// Source inference fallback: public names retained with permissive signatures.
export const BARK_SHADER: any;
export const BRANCH_TREE_DOCUMENT_TYPE: any;
export const BRANCH_TREE_DOCUMENT_VERSION: any;
export const BRANCH_TREE_LEAF_SHAPES: any;
export class BranchTree { constructor(...args: any[]); [key: string]: any; }
export const CALL_ME_SENSEI_GRASS_CLUMP_VARIANTS: any;
export const CALL_ME_SENSEI_GRASS_MATERIAL_TEXTURE_URLS: any;
export const CALL_ME_SENSEI_GRASS_PROVENANCE: any;
export const COMPILED_TREE_MANIFEST_SCHEMA: any;
export const COMPILED_TREE_MANIFEST_VERSION: any;
export const CONTACT_SHADOW_AERIAL_FADE: any;
export class CompiledTreeInstance { constructor(...args: any[]); [key: string]: any; }
export const DEFAULT_BRANCH_TREE_SETTINGS: any;
export const DEFAULT_CALL_ME_SENSEI_GRASS_CLUMP: any;
export const DEFAULT_FLOWER_SETTINGS: any;
export const DEFAULT_GRASS_SETTINGS: any;
export const DEFAULT_STYLIZED_TREE_SETTINGS: any;
export const DEFAULT_VEGETATION_SHADER_SETTINGS: any;
export const FLOWER_SETTING_FIELD_SCHEMA: any;
export const FLOWER_SETTING_GROUPS: any;
export const FLOWER_SHADER: any;
export const FLOWER_SHADER_PROFILE: any;
export const FLOWER_SHADER_PROFILE_DOCUMENT_TYPE: any;
export const FLOWER_SHADER_PROFILE_SCHEMA_VERSION: any;
export const FLOWER_SPECIES: any;
export const FOLIAGE_SHADER: any;
export const GRASS_CLUMP_GEOMETRY_RECIPE: any;
export const GRASS_CLUMP_LODS: any;
export const GRASS_COLOR_PALETTES: any;
export const GRASS_PRESET_DOCUMENT_TYPE: any;
export const GRASS_PRESET_SCHEMA_VERSION: any;
export const GRASS_SETTING_FIELD_SCHEMA: any;
export const GRASS_SETTING_GROUPS: any;
export const GRASS_SHADER: any;
export const GRASS_SHADER_PROFILE: any;
export const GRASS_SHADER_PROFILE_DOCUMENT_TYPE: any;
export const GRASS_SHADER_PROFILE_SCHEMA_VERSION: any;
export const LEAF_SHAPE_PRESETS: any;
export const LEGACY_TREE_IDS: any;
export const LEGACY_TREE_PRESETS: any;
export class RetainedGrassClumpField { constructor(...args: any[]); [key: string]: any; }
export const STYLIZED_FOREST_IMPOSTOR_QUALITY: any;
export const STYLIZED_TREE_EXAMPLES: any;
export const STYLIZED_TREE_SETTING_FIELD_SCHEMA: any;
export const STYLIZED_TREE_SETTING_GROUPS: any;
export class StylizedBush { constructor(...args: any[]); [key: string]: any; }
export class StylizedContactShadowField { constructor(...args: any[]); [key: string]: any; }
export class StylizedFlower { constructor(...args: any[]); [key: string]: any; }
export class StylizedFlowerField { constructor(...args: any[]); [key: string]: any; }
export class StylizedForest { constructor(...args: any[]); [key: string]: any; }
export class StylizedGrassClumpField { constructor(...args: any[]); [key: string]: any; }
export class StylizedGrassField { constructor(...args: any[]); [key: string]: any; }
export class StylizedTree { constructor(...args: any[]); [key: string]: any; }
export class StylizedTreeFoliage { constructor(...args: any[]); [key: string]: any; }
export class StylizedUnderstory { constructor(...args: any[]); [key: string]: any; }
export const TREE_FOLIAGE_ARCHITECTURES: any;
export const TREE_FOLIAGE_BLOBS: any;
export const TREE_RECIPE_SCHEMA: any;
export const TREE_RECIPE_VERSION: any;
export const TREE_RUNTIME_QUALITY_PROFILES: any;
export const TREE_SHADER_DOCUMENT_TYPE: any;
export const TREE_SHADER_PROFILE: any;
export const TREE_SHADER_SCHEMA_VERSION: any;
export const TREE_SURFACE_PROFILES: any;
export const TREE_SURFACE_PROFILE_DEFAULTS: any;
export const TREE_TRUNK_STYLES: any;
export const UNDERSTORY_AERIAL_FADE: any;
export const VEGETATION_MATERIAL_CONTRACT_VERSION: any;
export const VEGETATION_MATERIAL_ROLES: any;
export const VEGETATION_MATERIAL_VARIANTS: any;
export const VEGETATION_SHADER: any;
export const VEGETATION_SHADERS: any;
export const VEGETATION_SHADER_DOCUMENT_TYPE: any;
export const VEGETATION_SHADER_FAMILY: any;
export const VEGETATION_SHADER_FIELD_SCHEMA: any;
export const VEGETATION_SHADER_SCHEMA_VERSION: any;
export const VEGETATION_SHADER_SCOPES: any;
export const VEGETATION_SHADER_SCOPE_EXCLUDED_FIELDS: any;
export const VEGETATION_SHADER_SCOPE_IDS: any;
export const VEGETATION_SHADER_SETTING_GROUPS: any;
export const VEGETATION_SHADER_UNIFORM_BY_FIELD: any;
export const VEGETATION_SHARED_SHADER_GROUP_IDS: any;
export function applyBarkShader(...args: any[]): any;
export function applyFlowerShader(...args: any[]): any;
export function applyFoliageShader(...args: any[]): any;
export function applyGrassColorPalette(...args: any[]): any;
export function applyGrassShader(...args: any[]): any;
export function applyVegetationShader(...args: any[]): any;
export function applyVegetationShaderScope(...args: any[]): any;
export function bakeFoliageGeometry(...args: any[]): any;
export function combineMasks(...args: any[]): any;
export function createBakedFoliageMaterial(...args: any[]): any;
export function createBakedLeafTexture(...args: any[]): any;
export function createBarkGradientMap(...args: any[]): any;
export function createBarkShaderSettings(...args: any[]): any;
export function createBranchTree(...args: any[]): any;
export function createBranchTreeDocument(...args: any[]): any;
export function createBranchTreeSettings(...args: any[]): any;
export function createBranchTubeGeometry(...args: any[]): any;
export function createBranchingTreeSkeleton(...args: any[]): any;
export function createCallMeSenseiGrassField(...args: any[]): any;
export function createCallMeSenseiGrassMaterial(...args: any[]): any;
export function createCanopyBlobs(...args: any[]): any;
export function createCapEdgeWeight(...args: any[]): any;
export function createDensityWeightMask(...args: any[]): any;
export function createFlowerBloomNodeMaterial(...args: any[]): any;
export function createFlowerHeadBillboardNodeMaterial(...args: any[]): any;
export function createFlowerHeadGeometry(...args: any[]): any;
export function createFlowerHeadNodeMaterial(...args: any[]): any;
export function createFlowerHeadTexture(...args: any[]): any;
export function createFlowerNodeMaterial(...args: any[]): any;
export function createFlowerSettings(...args: any[]): any;
export function createFlowerShaderProfilePresetDocument(...args: any[]): any;
export function createFlowerShaderProfileSettings(...args: any[]): any;
export function createFlowerShaderSettings(...args: any[]): any;
export function createFlowerStemNodeMaterial(...args: any[]): any;
export function createFoliageShaderSettings(...args: any[]): any;
export function createGrassClumpGeometry(...args: any[]): any;
export function createGrassClumpMaterial(...args: any[]): any;
export function createGrassNodeMaterial(...args: any[]): any;
export function createGrassPresetDocument(...args: any[]): any;
export function createGrassSettings(...args: any[]): any;
export function createGrassShaderProfilePresetDocument(...args: any[]): any;
export function createGrassShaderProfileSettings(...args: any[]): any;
export function createGrassShaderSettings(...args: any[]): any;
export function createImportedVegetationMaterial(...args: any[]): any;
export function createLeafSpriteTexture(...args: any[]): any;
export function createLegacyTree(...args: any[]): any;
export function createNoisePatchMask(...args: any[]): any;
export function createOrganLeafSpriteTexture(...args: any[]): any;
export function createSlopeMask(...args: any[]): any;
export function createStylizedTreeSettings(...args: any[]): any;
export function createSurfaceWeightMask(...args: any[]): any;
export function createTreeFoliageGeometry(...args: any[]): any;
export function createTreeFoliageMaterials(...args: any[]): any;
export function createTreeLeafNodeMaterial(...args: any[]): any;
export function createTreeShaderPresetDocument(...args: any[]): any;
export function createTreeShaderSettings(...args: any[]): any;
export function createTreeSkeleton(...args: any[]): any;
export function createTreeSurfaceTexture(...args: any[]): any;
export function createTreeSurfaceTextureData(...args: any[]): any;
export function createTreeTrunkGeometry(...args: any[]): any;
export function createVegetationShaderPresetDocument(...args: any[]): any;
export function createVegetationShaderScopePresetDocument(...args: any[]): any;
export function createVegetationShaderScopeSettings(...args: any[]): any;
export function createVegetationShaderSettings(...args: any[]): any;
export function createVegetationSharedShaderSettings(...args: any[]): any;
export function createWaterMask(...args: any[]): any;
export function createWoodySurfaceNodeMaterial(...args: any[]): any;
export function deriveCanopyPalette(...args: any[]): any;
export function disposeExportGroup(...args: any[]): any;
export function getFlowerPresetOptions(...args: any[]): any;
export function getGrassPresetOptions(...args: any[]): any;
export function getLegacyTreePreset(...args: any[]): any;
export function getLegacyTreePresetOptions(...args: any[]): any;
export function getStylizedTreePresetOptions(...args: any[]): any;
export function getTreeSurfaceProfileOptions(...args: any[]): any;
export function getVegetationMaterialContract(...args: any[]): any;
export function getVegetationShaderPresetOptions(...args: any[]): any;
export function getVegetationShaderScopeExcludedFields(...args: any[]): any;
export function getVegetationShaderScopeFieldSchema(...args: any[]): any;
export function getVegetationShaderScopeSettingGroups(...args: any[]): any;
export function isVegetationSharedShaderGroup(...args: any[]): any;
export function layoutTreeRow(...args: any[]): any;
export function loadCallMeSenseiGrassClump(...args: any[]): any;
export function loadCompiledTreeAsset(...args: any[]): any;
export function matchGrassColorPalette(...args: any[]): any;
export function mergeVegetationSharedShaderSettings(...args: any[]): any;
export function migrateLegacyVegetationShaderDocuments(...args: any[]): any;
export function parseBranchTreeDocument(...args: any[]): any;
export function parseCompiledTreeManifest(...args: any[]): any;
export function parseFlowerShaderProfilePresetDocument(...args: any[]): any;
export function parseGrassPresetDocument(...args: any[]): any;
export function parseGrassShaderProfilePresetDocument(...args: any[]): any;
export function parseTreeShaderPresetDocument(...args: any[]): any;
export function parseVegetationShaderPresetDocument(...args: any[]): any;
export function parseVegetationShaderScopePresetDocument(...args: any[]): any;
export function polarProfileFromOutline(...args: any[]): any;
export function prepareTreeForExport(...args: any[]): any;
export function projectedTreeScreenCoverage(...args: any[]): any;
export function registerFlowerPreset(...args: any[]): any;
export function registerGrassPreset(...args: any[]): any;
export function registerSerializedGrassPreset(...args: any[]): any;
export function registerSerializedVegetationShaderPreset(...args: any[]): any;
export function registerStylizedTreePreset(...args: any[]): any;
export function registerVegetationShaderPreset(...args: any[]): any;
export function resolveCanopyColor(...args: any[]): any;
export function resolveGrassColorPalette(...args: any[]): any;
export function resolveTreeDitherMode(...args: any[]): any;
export function resolveVegetationShaderPreset(...args: any[]): any;
export function resolveVegetationShaderRoleSettings(...args: any[]): any;
export function sanitizeGrassPresetSettings(...args: any[]): any;
export function scatterForest(...args: any[]): any;
export function scatterGrassAround(...args: any[]): any;
export function scatterInRect(...args: any[]): any;
export function scatterOnSurface(...args: any[]): any;
export function scatterUnderstory(...args: any[]): any;
export function serializableTreeOptions(...args: any[]): any;
export function serializeGrassPreset(...args: any[]): any;
export function serializeVegetationShaderPreset(...args: any[]): any;
export function serializeVegetationShaderScopePreset(...args: any[]): any;
export function setCanopyCloudShadow(...args: any[]): any;
export function setCanopySceneShadow(...args: any[]): any;
export function setCanopySun(...args: any[]): any;
export function setCanopyWind(...args: any[]): any;
export function setWoodySurfaceSun(...args: any[]): any;
export function syncFoliageFog(...args: any[]): any;
export function tagVegetationMaterial(...args: any[]): any;
export function tickCanopyTime(...args: any[]): any;
export function traceLeafShapePath(...args: any[]): any;
export function unregisterGrassPreset(...args: any[]): any;
export function validateCompiledTreeManifest(...args: any[]): any;
export function validateGrassPresetDocument(...args: any[]): any;
export function validateVegetationShaderPresetDocument(...args: any[]): any;
export function validateVegetationShaderScopePresetDocument(...args: any[]): any;
