// Source inference fallback: public names retained with permissive signatures.
export const BARK_SHADER: any;
export const DEFAULT_VEGETATION_SHADER_SETTINGS: any;
export const FLOWER_SHADER: any;
export const FLOWER_SHADER_PROFILE: any;
export const FLOWER_SHADER_PROFILE_DOCUMENT_TYPE: any;
export const FLOWER_SHADER_PROFILE_SCHEMA_VERSION: any;
export const FOLIAGE_SHADER: any;
export const GRASS_SHADER: any;
export const GRASS_SHADER_PROFILE: any;
export const GRASS_SHADER_PROFILE_DOCUMENT_TYPE: any;
export const GRASS_SHADER_PROFILE_SCHEMA_VERSION: any;
export const TREE_SHADER_DOCUMENT_TYPE: any;
export const TREE_SHADER_PROFILE: any;
export const TREE_SHADER_SCHEMA_VERSION: any;
export const VEGETATION_MATERIAL_CONTRACT_VERSION: any;
export const VEGETATION_MATERIAL_ROLES: any;
export const VEGETATION_MATERIAL_VARIANTS: any;
export const VEGETATION_SHADER: any;
export const VEGETATION_SHADERS: any;
export const VEGETATION_SHADER_DOCUMENT_TYPE: any;
export const VEGETATION_SHADER_FAMILY: any;
export const VEGETATION_SHADER_FIELD_SCHEMA: any;
export const VEGETATION_SHADER_SCHEMA_VERSION: any;
export const VEGETATION_SHADER_SCOPES: any;
export const VEGETATION_SHADER_SCOPE_EXCLUDED_FIELDS: any;
export const VEGETATION_SHADER_SCOPE_IDS: any;
export const VEGETATION_SHADER_SETTING_GROUPS: any;
export const VEGETATION_SHADER_UNIFORM_BY_FIELD: any;
export const VEGETATION_SHARED_SHADER_GROUP_IDS: any;
export function applyBarkShader(...args: any[]): any;
export function applyFlowerShader(...args: any[]): any;
export function applyFoliageShader(...args: any[]): any;
export function applyGrassShader(...args: any[]): any;
export function applyVegetationShader(...args: any[]): any;
export function applyVegetationShaderScope(...args: any[]): any;
export function createBarkGradientMap(...args: any[]): any;
export function createBarkShaderSettings(...args: any[]): any;
export function createFlowerShaderProfilePresetDocument(...args: any[]): any;
export function createFlowerShaderProfileSettings(...args: any[]): any;
export function createFlowerShaderSettings(...args: any[]): any;
export function createFoliageShaderSettings(...args: any[]): any;
export function createGrassShaderProfilePresetDocument(...args: any[]): any;
export function createGrassShaderProfileSettings(...args: any[]): any;
export function createGrassShaderSettings(...args: any[]): any;
export function createTreeShaderPresetDocument(...args: any[]): any;
export function createTreeShaderSettings(...args: any[]): any;
export function createVegetationShaderPresetDocument(...args: any[]): any;
export function createVegetationShaderScopePresetDocument(...args: any[]): any;
export function createVegetationShaderScopeSettings(...args: any[]): any;
export function createVegetationShaderSettings(...args: any[]): any;
export function createVegetationSharedShaderSettings(...args: any[]): any;
export function getVegetationMaterialContract(...args: any[]): any;
export function getVegetationShaderPresetOptions(...args: any[]): any;
export function getVegetationShaderScopeExcludedFields(...args: any[]): any;
export function getVegetationShaderScopeFieldSchema(...args: any[]): any;
export function getVegetationShaderScopeSettingGroups(...args: any[]): any;
export function isVegetationSharedShaderGroup(...args: any[]): any;
export function mergeVegetationSharedShaderSettings(...args: any[]): any;
export function migrateLegacyVegetationShaderDocuments(...args: any[]): any;
export function parseFlowerShaderProfilePresetDocument(...args: any[]): any;
export function parseGrassShaderProfilePresetDocument(...args: any[]): any;
export function parseTreeShaderPresetDocument(...args: any[]): any;
export function parseVegetationShaderPresetDocument(...args: any[]): any;
export function parseVegetationShaderScopePresetDocument(...args: any[]): any;
export function registerSerializedVegetationShaderPreset(...args: any[]): any;
export function registerVegetationShaderPreset(...args: any[]): any;
export function resolveVegetationShaderPreset(...args: any[]): any;
export function resolveVegetationShaderRoleSettings(...args: any[]): any;
export function serializeVegetationShaderPreset(...args: any[]): any;
export function serializeVegetationShaderScopePreset(...args: any[]): any;
export function tagVegetationMaterial(...args: any[]): any;
export function validateVegetationShaderPresetDocument(...args: any[]): any;
export function validateVegetationShaderScopePresetDocument(...args: any[]): any;
