// Real renders (WebP, transparent, real toon shader) generated by
// scripts/generate-debris-thumbs.mjs — regenerate after changing a preset
// or its generator. Presets without a render fall back to the SVG doodle.
const PRESET_RENDERS = import.meta.glob('./thumbs/*.webp', { eager: true, import: 'default', query: '?url' });

const TYPE_COLORS = {
  ash: ['#191817', '#68645f', '#dc5d24'],
  bone: ['#4a4032', '#e6d8b5', '#a88a62'],
  masonry: ['#2b3033', '#777b78', '#b4653e'],
  metal: ['#273237', '#7d8c8d', '#c45124'],
  organic: ['#2f1c0a', '#a56d20', '#d64c18'],
  stone: ['#2c3236', '#7e8887', '#57b6b4'],
  wood: ['#2c1a0e', '#78502f', '#c4935c'],
};

function Wood({ variant }) {
  if (variant === 'rootStump') return <><circle cx="85" cy="52" r="17" fill="var(--mid)" /><path d="M85 40V22m-9 22L52 44m18 18L28 78m36-8-14 26m35-22 4 26m14-32 34 16m-30-26 24-8" /></>;
  if (variant === 'barkChips') return <><path d="m28 70 26-12 8 16-26 12Z" fill="var(--mid)" /><path d="m72 50 30-10 6 18-30 10Z" fill="var(--dark)" /><path d="m112 74 28-12 6 14-28 13Z" fill="var(--mid)" /><path d="m60 86 22-8 5 12-23 8Z" fill="var(--accent)" opacity=".8" /></>;
  if (variant === 'planks') return <><path d="m20 72 96-38 26 14-97 40Z" fill="var(--mid)" /><path d="m20 72 5-14 20 4-6 13m52-46 22-9 4 16" fill="var(--dark)" /><circle cx="74" cy="56" r="5" fill="var(--bg)" stroke="none" /></>;
  if (variant === 'logs') return <><g transform="rotate(-14 80 65)"><rect x="30" y="48" width="100" height="34" rx="16" fill="var(--mid)" /><ellipse cx="130" cy="65" rx="12" ry="17" fill="var(--accent)" /><ellipse cx="130" cy="65" rx="5" ry="8" fill="none" /></g><path d="m52 44 8-12m22 12 4-9" /></>;
  return <><path d="M18 79C39 70 50 47 88 37c24-7 38-17 53-35" /><path d="M63 52 48 29M92 36l14 19M119 23l-1-18" /><path d="m16 82 13 5m-11-5 8-10" /></>;
}

function Bone({ variant }) {
  if (variant === 'skull') return <><path d="M46 62c-5-27 10-43 38-42 25 1 39 14 35 36l20 12-18 22-25-7-13 18-17-19-20-4Z" fill="var(--mid)" /><circle cx="74" cy="55" r="11" fill="var(--bg)" stroke="none" /><circle cx="103" cy="54" r="10" fill="var(--bg)" stroke="none" /><path d="m119 63 23 5-10 17-18-5" /></>;
  if (variant === 'jawBone') return <><path d="M22 62c30-14 62-16 88-8l22 8 8-28c2-8 12-10 16-2 5 10 2 26-6 36-16 20-56 24-90 12L22 74Z" fill="var(--mid)" /><path d="M42 58v-8m14 5v-9m14 7v-9m14 10v-9" /></>;
  if (variant === 'antler') return <><path d="M19 93C52 88 65 67 82 43c17-23 37-24 62-26" /><path d="m57 76-2-30M78 50l-2-31M101 31l9-22M122 22l17 15" /></>;
  return <><path d="M31 78c20-4 24-25 42-27l43-4c12-1 16-15 30-13" /><circle cx="29" cy="79" r="13" fill="var(--mid)" /><circle cx="145" cy="34" r="14" fill="var(--mid)" /></>;
}

function Masonry({ variant }) {
  if (variant === 'bricks') return <><path d="m24 77 44-15 18 23-45 17Z" fill="var(--mid)" /><path d="m79 55 48-17 18 22-47 19Z" fill="var(--accent)" /><path d="m48 43 34-13 16 19-36 12Z" fill="var(--mid)" /></>;
  return <><path d="m18 90 23-42 35 14 18-33 35 17 22 48Z" fill="var(--mid)" /><path d="m18 90 58-28 18-33 8 65Z" fill="var(--dark)" /><path d="m102 94 27-48 22 48Z" fill="var(--accent)" /></>;
}

function Stone({ variant }) {
  if (variant === 'rubble' || variant === 'bricks' || variant === 'shards') return <Masonry variant={variant} />;
  if (variant === 'obsidian') return <><path d="m40 92 24-68 18 60Z" fill="var(--dark)" /><path d="m78 90 20-52 26 48Z" fill="var(--mid)" /><path d="m52 70 18-2m-14-16 12-2" /></>;
  if (variant === 'meteor') return <><circle cx="82" cy="62" r="34" fill="var(--mid)" /><circle cx="70" cy="52" r="9" fill="var(--dark)" stroke="none" /><circle cx="96" cy="70" r="6" fill="var(--dark)" stroke="none" /><circle cx="88" cy="46" r="4" fill="var(--dark)" stroke="none" /><path d="M120 30 134 16m-6 30 14-6" stroke="var(--accent)" /></>;
  if (variant === 'gems') return <><path d="m54 88 -18-26 20-22 26 6 8 28-16 16Z" fill="var(--accent)" /><path d="m36 62 26-8 20-14M62 54l12 34" /><path d="m104 78 8-24 20 6-4 24Z" fill="var(--mid)" /></>;
  return <><ellipse cx="60" cy="74" rx="34" ry="18" fill="var(--mid)" /><ellipse cx="112" cy="58" rx="26" ry="14" fill="var(--dark)" /><ellipse cx="86" cy="88" rx="22" ry="10" fill="var(--accent)" opacity=".7" /></>;
}

function Metal({ variant }) {
  if (variant === 'cans') return <><g transform="rotate(-18 61 67)"><rect x="39" y="33" width="43" height="69" rx="12" fill="var(--mid)" /><ellipse cx="61" cy="36" rx="21" ry="8" fill="none" /></g><g transform="rotate(25 111 64)"><rect x="92" y="31" width="39" height="65" rx="11" fill="var(--accent)" /><ellipse cx="111" cy="34" rx="18" ry="7" fill="none" /></g></>;
  return <><path d="m18 84 27-57 50 19 44-20 17 59-58-11-31 25Z" fill="var(--mid)" /><path d="m45 27 22 72M95 46l3 28M139 26l-41 48" /><path d="m102 43 17 38" stroke="var(--accent)" /></>;
}

function Organic({ variant }) {
  if (variant === 'pinecones') return <><path d="M54 25c24 7 29 55 3 78-28-20-28-65-3-78ZM112 36c23 8 25 48 1 66-25-18-25-55-1-66Z" fill="var(--mid)" /><path d="m38 52 35 16M35 72l31 14m30-27 31 15m-31 6 25 12" /></>;
  if (variant === 'shells') return <><path d="M30 94C20 50 42 28 76 26c30 9 46 32 36 68Z" fill="var(--mid)" /><path d="M72 28 44 94M75 29l-7 65m11-64 17 64m-13-62 43 62" /></>;
  return <><path d="M25 90C27 51 51 23 87 18c8 37-13 70-52 80Z" fill="var(--mid)" /><path d="M36 91 78 29M48 74l-11-20m24 1 18-13" /><path d="M98 96c-3-27 13-48 37-53 10 27-4 49-29 57Z" fill="var(--accent)" /></>;
}

function Ash({ variant }) {
  return <><ellipse cx="85" cy="88" rx="67" ry="23" fill="var(--dark)" opacity=".55" /><path d="M20 86c11-36 39-50 67-48 33 1 60 19 65 48Z" fill="var(--mid)" />{variant === 'campfire' && <><path d="m38 78 92-35M40 45l89 35" strokeWidth="14" stroke="var(--dark)" /><path d="m71 67 26-10" stroke="var(--accent)" /></>}{variant !== 'campfire' && <><path d="m47 70 22-15 14 19-24 11Z" fill="var(--dark)" /><path d="m105 62 20 10-8 17-23-8Z" fill="var(--dark)" /></>}</>;
}

export function DebrisThumbnail({ preset }) {
  const render = preset.id ? PRESET_RENDERS[`./thumbs/${preset.id}.webp`] : null;
  if (render) {
    return <img alt="" className="db-thumb db-thumb--render" loading="lazy" src={render} />;
  }
  const [dark, mid, accent] = TYPE_COLORS[preset.type] ?? TYPE_COLORS.wood;
  const Shape = preset.type === 'wood' ? Wood
    : preset.type === 'bone' ? Bone
      : preset.type === 'stone' || preset.type === 'masonry' ? Stone
        : preset.type === 'metal' ? Metal
          : preset.type === 'organic' ? Organic : Ash;
  return (
    <svg
      aria-hidden="true"
      className="db-thumb"
      viewBox="0 0 170 118"
      style={{ '--accent': accent, '--dark': dark, '--mid': mid }}
    >
      <rect width="170" height="118" rx="10" fill="#182026" />
      <ellipse cx="85" cy="99" rx="65" ry="10" fill="#080b0d" opacity=".42" />
      <g fill="none" stroke="var(--mid)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="9">
        <Shape variant={preset.variant} />
      </g>
    </svg>
  );
}
