export function plateauLandmarkAssetRef(landmark: any): {
    attribution: Readonly<{
        text: string;
        license: "PDL 1.0 / CC BY 4.0 compatible";
        requiresAttribution: true;
        sourceLabel: "Project PLATEAU";
        sourceUrl: "https://www.mlit.go.jp/plateau/opendata/";
    }>;
    authors: string[];
    categories: any[];
    citygml: {
        featureId: any;
        url: any;
    };
    download: {
        format: string;
        resources: {};
        sizeBytes: any;
        url: string;
    };
    id: string;
    kind: string;
    metadata: {
        address: any;
        aliases: any[];
        areaCode: any;
        buildingId: any;
        boundsMetres: any[];
        city: any;
        coordinateSystem: string;
        latitude: any;
        licenseUrl: string;
        longitude: any;
        measuredHeight: any;
        nameJa: any;
        payloadType: string;
        prefecture: any;
        processed: boolean;
        sourceGmlId: any;
        sourceTileUrl: any;
        sourceTilesetUrl: any;
        wikidataId: any;
        triangleCount: any;
        vertexCount: any;
    };
    name: string;
    openAccess: boolean;
    pageUrl: string;
    source: string;
    streamOnly: boolean;
    tags: any[];
    thumbnailUrl: string;
};
export function listPlateauLandmarks(): {
    attribution: Readonly<{
        text: string;
        license: "PDL 1.0 / CC BY 4.0 compatible";
        requiresAttribution: true;
        sourceLabel: "Project PLATEAU";
        sourceUrl: "https://www.mlit.go.jp/plateau/opendata/";
    }>;
    authors: string[];
    categories: any[];
    citygml: {
        featureId: any;
        url: any;
    };
    download: {
        format: string;
        resources: {};
        sizeBytes: any;
        url: string;
    };
    id: string;
    kind: string;
    metadata: {
        address: any;
        aliases: any[];
        areaCode: any;
        buildingId: any;
        boundsMetres: any[];
        city: any;
        coordinateSystem: string;
        latitude: any;
        licenseUrl: string;
        longitude: any;
        measuredHeight: any;
        nameJa: any;
        payloadType: string;
        prefecture: any;
        processed: boolean;
        sourceGmlId: any;
        sourceTileUrl: any;
        sourceTilesetUrl: any;
        wikidataId: any;
        triangleCount: any;
        vertexCount: any;
    };
    name: string;
    openAccess: boolean;
    pageUrl: string;
    source: string;
    streamOnly: boolean;
    tags: any[];
    thumbnailUrl: string;
}[];
export function findPlateauLandmark(id: any): {
    attribution: Readonly<{
        text: string;
        license: "PDL 1.0 / CC BY 4.0 compatible";
        requiresAttribution: true;
        sourceLabel: "Project PLATEAU";
        sourceUrl: "https://www.mlit.go.jp/plateau/opendata/";
    }>;
    authors: string[];
    categories: any[];
    citygml: {
        featureId: any;
        url: any;
    };
    download: {
        format: string;
        resources: {};
        sizeBytes: any;
        url: string;
    };
    id: string;
    kind: string;
    metadata: {
        address: any;
        aliases: any[];
        areaCode: any;
        buildingId: any;
        boundsMetres: any[];
        city: any;
        coordinateSystem: string;
        latitude: any;
        licenseUrl: string;
        longitude: any;
        measuredHeight: any;
        nameJa: any;
        payloadType: string;
        prefecture: any;
        processed: boolean;
        sourceGmlId: any;
        sourceTileUrl: any;
        sourceTilesetUrl: any;
        wikidataId: any;
        triangleCount: any;
        vertexCount: any;
    };
    name: string;
    openAccess: boolean;
    pageUrl: string;
    source: string;
    streamOnly: boolean;
    tags: any[];
    thumbnailUrl: string;
};
export function searchPlateauLandmarks(query?: string): {
    attribution: Readonly<{
        text: string;
        license: "PDL 1.0 / CC BY 4.0 compatible";
        requiresAttribution: true;
        sourceLabel: "Project PLATEAU";
        sourceUrl: "https://www.mlit.go.jp/plateau/opendata/";
    }>;
    authors: string[];
    categories: any[];
    citygml: {
        featureId: any;
        url: any;
    };
    download: {
        format: string;
        resources: {};
        sizeBytes: any;
        url: string;
    };
    id: string;
    kind: string;
    metadata: {
        address: any;
        aliases: any[];
        areaCode: any;
        buildingId: any;
        boundsMetres: any[];
        city: any;
        coordinateSystem: string;
        latitude: any;
        licenseUrl: string;
        longitude: any;
        measuredHeight: any;
        nameJa: any;
        payloadType: string;
        prefecture: any;
        processed: boolean;
        sourceGmlId: any;
        sourceTileUrl: any;
        sourceTilesetUrl: any;
        wikidataId: any;
        triangleCount: any;
        vertexCount: any;
    };
    name: string;
    openAccess: boolean;
    pageUrl: string;
    source: string;
    streamOnly: boolean;
    tags: any[];
    thumbnailUrl: string;
}[];
export const PLATEAU_LANDMARK_ASSET_BASE: "/plateau-landmarks";
export const PLATEAU_LANDMARKS: readonly Readonly<{
    address: "4 Chome Shibakoen, Minato City, Tokyo";
    aliases: readonly string[];
    areaCode: "13103";
    artifactSizeBytes: 950796;
    boundsMetres: readonly number[];
    buildingId: "13103-bldg-6915";
    city: "Minato City";
    citygmlUrl: "https://assets.cms.plateau.reearth.io/assets/ea/d75459-6d62-4a1f-8081-317603bd5f8d/13103_minato-ku_pref_2025_citygml_1_op/udx/bldg/53393599_bldg_6697_op.gml";
    id: "tokyo-tower";
    latitude: 35.6586;
    longitude: 139.7454;
    measuredHeight: 332.1;
    name: "Tokyo Tower";
    nameJa: "東京タワー";
    prefecture: "Tokyo";
    sourceGmlId: "bldg_7aff4a51-be8b-405b-abe4-ac489697cbc8";
    sourceTileUrl: "https://assets.cms.plateau.reearth.io/assets/c7/ffcc73-1d33-434b-a49a-aa0289160814/13103_minato-ku_pref_2025_citygml_1_op_bldg_3dtiles_13103_minato-ku_lod3/data/data248.b3dm";
    sourceTilesetUrl: "https://api.plateauview.mlit.go.jp/datacatalog/3dtiles/13103-bldg-lod3-texture-latest/tileset.json";
    wikidataId: "Q183536";
    triangleCount: 460;
    vertexCount: 1380;
}>[];
export { PLATEAU_LICENSE };
import { PLATEAU_LICENSE } from "./plateau.js";
