// First-party natural comparison range for the Rock and Ground Shader Labs.
// Every visible asset is generated by a public ToonLab system at runtime.

import * as THREE from 'three';

import { buildProp } from '../../../src/propgen/index.js';
import { createRockDocument, meshDocument } from '../../../src/rockgen/index.js';
import { PRESETS, SkySystem } from '../../../src/sky/index.js';
import {
  StylizedFlowerField,
  StylizedTree,
  createCallMeSenseiGrassField,
} from '../../../src/vegetation/index.js';
import { applyLabPreviewEnvironment } from '../previewEnvironmentRig.js';
import { createLabRenderer } from '../rendererFactory.js';
import {
  createShaderPreviewSettings,
  resolveShaderPreviewComponentStyles,
} from './previewStyles.js';

export const ROCK_SHADER_PREVIEW_FIXTURES = Object.freeze([
  Object.freeze({ id: 'spire-01', label: 'Karst Needle', preset: 'karst-spire', seed: 11, scale: [1.15, 1, 1.15] }),
  Object.freeze({ id: 'spire-02', label: 'Sea Stack', preset: 'sea-stack', seed: 23, scale: [1.15, 1.18, 1.15] }),
  Object.freeze({ id: 'spire-03', label: 'Granite Block', preset: 'granite-boulder', seed: 37, scale: [1.35, 1.55, 1.35] }),
  Object.freeze({ id: 'spire-04', label: 'Basalt Columns', preset: 'basalt-columns', seed: 41, scale: [0.9, 1.05, 0.9] }),
  Object.freeze({ id: 'spire-05', label: 'Hero Karst Spire', preset: 'karst-spire', seed: 53, scale: [1.45, 1.25, 1.35] }),
  Object.freeze({ id: 'spire-06', label: 'Eroded Mesa', preset: 'eroded-mesa', seed: 67, scale: [1, 1.15, 1] }),
  Object.freeze({ id: 'spire-07', label: 'Shard Monolith', preset: 'shard-monolith', seed: 71, scale: [1.05, 1.15, 1.05] }),
  Object.freeze({ id: 'spire-08', label: 'Canyon Ridge', preset: 'canyon-ridge', seed: 89, scale: [0.85, 0.95, 0.85] }),
]);

const STYLE_COLORS = Object.freeze({
  call_me_sensei: Object.freeze({
    clouds: '#f1f5ff',
    flowerCenter: '#f1bd58',
    flowers: '#f5eee0',
    grass: '#4f8b3f',
    grassTip: '#8fbd5b',
    ground: '#66824f',
    manufacturedProps: '#d6c3a0',
    rock: '#aaa79e',
    tree: '#3f7541',
    treeBark: '#72503a',
  }),
  neutral_review: Object.freeze({
    clouds: '#d9dcdf',
    flowerCenter: '#a6a49f',
    flowers: '#d4d2ce',
    grass: '#747c70',
    grassTip: '#9a9f96',
    ground: '#7f857c',
    manufacturedProps: '#a29d94',
    rock: '#92969b',
    tree: '#6f776f',
    treeBark: '#716e69',
  }),
});

function clamp01(value) {
  return Math.min(Math.max(value, 0), 1);
}

function pseudoNoise(x, z, seed = 0) {
  const value = Math.sin(x * 12.9898 + z * 78.233 + seed * 37.719) * 43758.5453;
  return value - Math.floor(value);
}

function seededRandom(seed = 1) {
  let state = seed >>> 0;
  return () => {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state / 0x100000000;
  };
}

function srgbArray(value) {
  return new THREE.Color(value).convertLinearToSRGB().toArray();
}

function groundHeight(x, z) {
  const rolling = Math.sin(x * 0.24) * Math.cos(z * 0.2) * 0.48;
  const woodedShoulder = Math.exp(-(((x + 6.2) ** 2) / 20 + ((z + 3.4) ** 2) / 28)) * 1.45;
  const rockyShelf = Math.exp(-(((x - 1.2) ** 2) / 34 + ((z + 5.1) ** 2) / 11)) * 0.52;
  const meadowHollow = Math.exp(-(((x - 5.4) ** 2) / 11 + ((z - 3.8) ** 2) / 10)) * 0.78;
  return rolling + woodedShoulder + rockyShelf - meadowHollow - 0.04;
}

function createGroundGeometry() {
  const geometry = new THREE.PlaneGeometry(28, 23, 82, 68);
  geometry.rotateX(-Math.PI / 2);
  const positions = geometry.getAttribute('position');
  for (let index = 0; index < positions.count; index += 1) {
    positions.setY(index, groundHeight(positions.getX(index), positions.getZ(index)));
  }
  positions.needsUpdate = true;
  geometry.computeVertexNormals();
  geometry.computeBoundingBox();
  geometry.computeBoundingSphere();
  geometry.name = 'ToonLab natural shader-preview terrain';
  return geometry;
}

function createGroundField(width = 96, depth = 80) {
  const splat = new Uint8Array(width * depth * 4);
  for (let row = 0; row < depth; row += 1) {
    for (let column = 0; column < width; column += 1) {
      const u = column / Math.max(width - 1, 1);
      const v = row / Math.max(depth - 1, 1);
      const x = (u - 0.5) * 28;
      const z = (0.5 - v) * 23;
      const dx = groundHeight(x + 0.18, z) - groundHeight(x - 0.18, z);
      const dz = groundHeight(x, z + 0.18) - groundHeight(x, z - 0.18);
      const slope = Math.sqrt(dx * dx + dz * dz) / 0.36;
      const rock = clamp01((slope - 0.42) * 1.8);
      const pathDistance = Math.abs(x + z * 0.28 - 3.0);
      const dirt = Math.exp(-(pathDistance ** 2) / 1.7) * (1 - rock * 0.8) * 0.78;
      const damp = clamp01((0.12 - groundHeight(x, z)) * 0.75)
        * clamp01((x + z + 4) / 10) * 0.24;
      const variation = 0.9 + pseudoNoise(x * 0.42, z * 0.42, 17) * 0.18;
      const grass = Math.max(0.18, (1 - rock) * (1 - dirt * 0.74) * variation);
      const total = Math.max(grass + dirt + rock + damp, 0.0001);
      const offset = (row * width + column) * 4;
      splat[offset] = Math.round((grass / total) * 255);
      splat[offset + 1] = Math.round((dirt / total) * 255);
      splat[offset + 2] = Math.round((rock / total) * 255);
      splat[offset + 3] = Math.round((damp / total) * 255);
    }
  }
  return { splat, splatD: depth, splatW: width };
}

function createProceduralLayerTexture(base, seed) {
  const size = 64;
  const data = new Uint8Array(size * size * 4);
  const source = new THREE.Color(base);
  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      const fine = pseudoNoise(x * 0.7, y * 0.7, seed);
      const broad = pseudoNoise(Math.floor(x / 7), Math.floor(y / 7), seed + 13);
      const shade = 0.76 + fine * 0.12 + broad * 0.14;
      const offset = (y * size + x) * 4;
      data[offset] = Math.round(clamp01(source.r * shade) * 255);
      data[offset + 1] = Math.round(clamp01(source.g * shade) * 255);
      data[offset + 2] = Math.round(clamp01(source.b * shade) * 255);
      data[offset + 3] = 255;
    }
  }
  const texture = new THREE.DataTexture(data, size, size, THREE.RGBAFormat);
  texture.name = `ToonLab generated meadow layer ${seed}`;
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.wrapS = THREE.RepeatWrapping;
  texture.wrapT = THREE.RepeatWrapping;
  texture.needsUpdate = true;
  return texture;
}

function createGroundLayers() {
  return [
    { texture: createProceduralLayerTexture('#6d9754', 3) },
    { texture: createProceduralLayerTexture('#796753', 7) },
    { texture: createProceduralLayerTexture('#7d8581', 11) },
    { texture: createProceduralLayerTexture('#58715c', 19) },
  ];
}

function ensurePreviewUv(geometry) {
  if (geometry.getAttribute('uv')) return geometry;
  geometry.computeBoundingBox();
  const positions = geometry.getAttribute('position');
  const bounds = geometry.boundingBox;
  const width = Math.max(bounds.max.x - bounds.min.x, 0.0001);
  const depth = Math.max(bounds.max.z - bounds.min.z, 0.0001);
  const values = new Float32Array(positions.count * 2);
  for (let index = 0; index < positions.count; index += 1) {
    values[index * 2] = (positions.getX(index) - bounds.min.x) / width;
    values[index * 2 + 1] = (positions.getZ(index) - bounds.min.z) / depth;
  }
  geometry.setAttribute('uv', new THREE.BufferAttribute(values, 2));
  return geometry;
}

function registerMaterial(bindings, material, component, tone = component) {
  material.userData.toonlabPreviewMaterial = { component, tone };
  bindings.push({ component, material, tone });
  return material;
}

function registerObjectMaterials(bindings, root, component, tone = component) {
  root.traverse((object) => {
    const materials = Array.isArray(object.material) ? object.material : [object.material];
    materials.filter(Boolean).forEach((material) => registerMaterial(bindings, material, component, tone));
  });
}

function createMeadowPlacements() {
  const placements = [];
  const random = seededRandom(20260807);
  let attempts = 0;
  while (placements.length < 148 && attempts < 4000) {
    attempts += 1;
    const x = (random() - 0.5) * 25.4;
    const z = (random() - 0.5) * 20.4;
    const y = groundHeight(x, z);
    const pathDistance = Math.abs(x + z * 0.28 - 3.0);
    const rockClearing = Math.hypot(x, z + 0.4);
    if (pathDistance < 1.05 || rockClearing < 3.45 || y < -0.55) continue;
    placements.push({
      phase: random(),
      scale: 0.72 + random() * 0.48,
      x,
      y,
      yaw: random() * Math.PI * 2,
      z,
    });
  }
  return placements;
}

function createFlowerPlacements() {
  const placements = [];
  const random = seededRandom(7707);
  for (let index = 0; index < 34; index += 1) {
    const x = -10.4 + random() * 5.2;
    const z = 1.8 + random() * 7.4;
    placements.push({
      headHeight: 0.42 + random() * 0.24,
      size: 0.22 + random() * 0.12,
      x,
      y: groundHeight(x, z),
      z,
    });
  }
  return placements;
}

function createTreeGrove() {
  const root = new THREE.Group();
  root.name = 'ToonLab procedural broadleaf grove';
  const trees = [
    { position: [7.2, -5.0], seed: 2107, size: 1.72, yaw: -0.25 },
    { position: [10.3, -6.4], seed: 2119, size: 1.18, yaw: 0.42 },
    { position: [-8.9, -7.1], seed: 2131, size: 1.08, yaw: -0.52 },
  ].map(({ position: [x, z], seed, size, yaw }) => {
    const tree = new StylizedTree({
      preset: 'call_me_sensei',
      roots: { preset: 'medium' },
      seed,
      size,
    });
    tree.position.set(x, groundHeight(x, z) - 0.03, z);
    tree.rotation.y = yaw;
    root.add(tree);
    return tree;
  });
  return { root, trees };
}

function createScaleProps(bindings) {
  const root = new THREE.Group();
  root.name = 'ToonLab generated meadow props';
  const definitions = [
    {
      position: [8.0, 1.0],
      rotation: -0.34,
      settings: {
        asset: { scale: 0.92, seed: 7, type: 'lantern', variant: 'stoneToro' },
        shape: { glow: 0.18, height: 1.75, lampSize: 0.9, roofOverhang: 1.12, wear: 0.48 },
      },
    },
    {
      position: [9.6, 2.2],
      rotation: 0.18,
      settings: {
        asset: { scale: 0.82, seed: 31, type: 'milestone', variant: 'jizo' },
        shape: { girth: 0.95, height: 1.0, inscription: 0.42, moss: 0.35 },
      },
    },
  ];
  definitions.forEach(({ position: [x, z], rotation, settings }) => {
    const { object3D } = buildProp(settings, { detail: 'hi' });
    object3D.position.set(x, groundHeight(x, z), z);
    object3D.rotation.y = rotation;
    registerObjectMaterials(bindings, object3D, 'manufacturedProps');
    root.add(object3D);
  });
  return root;
}

function createRockMesh(fixture, variant, bindings) {
  const rockDocument = createRockDocument({
    name: variant.label,
    preset: variant.preset ?? fixture.preset,
    seed: variant.seed,
    style: 'default',
  });
  rockDocument.pieces.forEach((piece, index) => {
    piece.seed = variant.seed + index * 101;
  });
  const geometry = ensurePreviewUv(meshDocument(rockDocument, { resolution: variant.resolution ?? 40 }));
  const material = registerMaterial(
    bindings,
    new THREE.MeshStandardMaterial({
      color: STYLE_COLORS.call_me_sensei.rock,
      roughness: 0.9,
      vertexColors: true,
    }),
    'rock',
    'rock',
  );
  material.name = 'ToonLab Rock Generator preview source';
  const mesh = new THREE.Mesh(geometry, material);
  mesh.name = variant.label;
  mesh.scale.fromArray(variant.scale);
  const [x, z] = variant.position;
  const bounds = geometry.boundingBox ?? new THREE.Box3().setFromBufferAttribute(
    geometry.getAttribute('position'),
  );
  mesh.position.set(x, groundHeight(x, z) - bounds.min.y * variant.scale[1] + 0.02, z);
  mesh.rotation.y = variant.yaw;
  mesh.castShadow = true;
  mesh.receiveShadow = true;
  return mesh;
}

function disposeObject(root) {
  const geometries = new Set();
  const materials = new Set();
  root?.traverse?.((object) => {
    if (object.geometry) geometries.add(object.geometry);
    const entries = Array.isArray(object.material) ? object.material : [object.material];
    entries.filter(Boolean).forEach((material) => materials.add(material));
  });
  geometries.forEach((geometry) => geometry.dispose?.());
  materials.forEach((material) => material.dispose?.());
}

function removeBindingsForRoot(bindings, root) {
  const materials = new Set();
  root.traverse((object) => {
    const entries = Array.isArray(object.material) ? object.material : [object.material];
    entries.filter(Boolean).forEach((material) => materials.add(material));
  });
  for (let index = bindings.length - 1; index >= 0; index -= 1) {
    if (materials.has(bindings[index].material)) bindings.splice(index, 1);
  }
}

export function createShaderPreviewRenderer() {
  document.body.dataset.previewRendererRequirement = 'portable-tsl';
  return createLabRenderer({ antialias: true, preserveDrawingBuffer: true });
}

export async function createShaderPreviewScene({ authoredComponent, camera, renderer, scene }) {
  const authoredComponents = new Set(
    (Array.isArray(authoredComponent) ? authoredComponent : [authoredComponent]).filter(Boolean),
  );
  const materialBindings = [];
  const field = createGroundField();
  const layers = createGroundLayers();

  const terrainRoot = new THREE.Group();
  terrainRoot.name = 'ToonLab natural terrain context';
  const groundMaterial = registerMaterial(
    materialBindings,
    new THREE.MeshStandardMaterial({ color: STYLE_COLORS.call_me_sensei.ground, roughness: 0.94 }),
    'ground',
  );
  const groundRoot = new THREE.Mesh(createGroundGeometry(), groundMaterial);
  groundRoot.name = 'ToonLab Ground Shader preview target';
  groundRoot.castShadow = true;
  groundRoot.receiveShadow = true;
  groundRoot.frustumCulled = false;
  terrainRoot.add(groundRoot);

  const rockRoot = new THREE.Group();
  rockRoot.name = 'ToonLab Rock Generator geological family';
  const grass = await createCallMeSenseiGrassField({
    groundField: false,
    placements: createMeadowPlacements(),
    seed: 1337,
    variant: 'primary',
    windStrength: 0.11,
  });
  grass.name = 'ToonLab first-party tapered-clump meadow';
  const flowers = new StylizedFlowerField({
    centerColor: srgbArray(STYLE_COLORS.call_me_sensei.flowerCenter),
    petalColor: srgbArray(STYLE_COLORS.call_me_sensei.flowers),
    placements: createFlowerPlacements(),
    windStrength: 0.08,
  });
  const { root: tree, trees } = createTreeGrove();
  const manufacturedProps = createScaleProps(materialBindings);

  scene.fog = new THREE.FogExp2('#a7c4d8', 0.011);
  const sun = new THREE.DirectionalLight('#fff0d2', 2.15);
  sun.name = 'ToonLab meadow sun';
  sun.castShadow = true;
  sun.shadow.mapSize.set(2048, 2048);
  sun.shadow.camera.left = -22;
  sun.shadow.camera.right = 22;
  sun.shadow.camera.top = 22;
  sun.shadow.camera.bottom = -22;
  sun.shadow.camera.near = 0.1;
  sun.shadow.camera.far = 90;
  const focus = authoredComponents.has('rock')
    ? new THREE.Vector3(0, 2.35, -0.2)
    : new THREE.Vector3(0.7, 0.3, 0.4);
  sun.target.position.copy(focus);
  const hemisphereLight = new THREE.HemisphereLight('#c7dcff', '#5f744e', 0.78);
  const ambientLight = new THREE.AmbientLight('#c7dcff', 0.18);
  const lightingRoot = new THREE.Group();
  lightingRoot.name = 'ToonLab meadow lighting';
  lightingRoot.add(sun, sun.target, hemisphereLight, ambientLight);

  scene.add(terrainRoot, rockRoot, grass, tree, flowers, manufacturedProps, lightingRoot);

  const skySystem = await SkySystem.create({
    camera,
    godRays: false,
    quality: 'low',
    renderer,
    scene,
    timeOfDay: { autoAdvanceSecondsPerDay: 0, latitude: 38, time: 13 / 24 },
  });
  const skyPreset = PRESETS.partlyCloudy;
  await skySystem.applyPreset({
    ...skyPreset,
    atmosphere: { ...skyPreset.atmosphere, exposure: 0.78, fogDensity: 0.86 },
    cloud: {
      ...skyPreset.cloud,
      shape: { ...skyPreset.cloud.shape, coverage: 0.38, density: 0.015 },
    },
    godRays: { ...skyPreset.godRays, enabled: false },
    noise: {
      ...skyPreset.noise,
      weather: { ...skyPreset.noise.weather, resolution: 192 },
    },
  });
  skySystem.groundLevel = -0.6;
  const [skyRoot, clouds] = skySystem.backdrops;
  skyRoot.name = 'ToonLab atmospheric sky';
  clouds.name = 'ToonLab volumetric cloud layer';

  const componentRoots = {
    clouds,
    flowers,
    grass,
    ground: terrainRoot,
    lighting: lightingRoot,
    manufacturedProps,
    rock: rockRoot,
    sky: skyRoot,
    tree,
  };
  const defaultCameraPosition = authoredComponents.has('rock')
    ? new THREE.Vector3(12.6, 7.4, 15.4)
    : new THREE.Vector3(13.8, 9.4, 16.2);
  let currentRockGroup = null;
  let lightingStyle = 'call_me_sensei';
  let skyStyle = 'call_me_sensei';
  let currentHour = 13;

  async function setRockFixture(id) {
    const fixture = ROCK_SHADER_PREVIEW_FIXTURES.find((entry) => entry.id === id)
      ?? ROCK_SHADER_PREVIEW_FIXTURES[4];
    if (currentRockGroup) {
      removeBindingsForRoot(materialBindings, currentRockGroup);
      rockRoot.remove(currentRockGroup);
      disposeObject(currentRockGroup);
    }
    await Promise.resolve();
    const heroScale = fixture.scale;
    const variants = [
      {
        label: fixture.label,
        position: [0, -0.35],
        preset: fixture.preset,
        resolution: 42,
        scale: heroScale,
        seed: fixture.seed,
        yaw: (fixture.seed % 17) * 0.11,
      },
      {
        label: `${fixture.label} — weathered fragment`,
        position: [-3.15, 0.85],
        resolution: 30,
        scale: heroScale.map((value, axis) => value * [0.4, 0.35, 0.42][axis]),
        seed: fixture.seed + 101,
        yaw: 1.08,
      },
      {
        label: `${fixture.label} — meadow outcrop`,
        position: [2.9, 1.5],
        resolution: 30,
        scale: heroScale.map((value, axis) => value * [0.34, 0.28, 0.42][axis]),
        seed: fixture.seed + 211,
        yaw: -0.72,
      },
    ];
    currentRockGroup = new THREE.Group();
    currentRockGroup.name = `${fixture.label} geological set`;
    variants.forEach((variant) => currentRockGroup.add(
      createRockMesh(fixture, variant, materialBindings),
    ));
    rockRoot.add(currentRockGroup);
    document.body.dataset.previewFixtureSource = 'toonlab-rockgen';
    document.body.dataset.previewFixturePreset = fixture.preset;
    return currentRockGroup;
  }

  function applyTime(hour) {
    currentHour = ((Number(hour) % 24) + 24) % 24;
    const lightingScale = lightingStyle === 'neutral_review' ? 0.84 : 1;
    const result = applyLabPreviewEnvironment(currentHour, {
      ambientIntensity: 0.18 * lightingScale,
      ambientLight,
      background: false,
      hemisphereIntensity: 0.78 * lightingScale,
      hemisphereLight,
      renderer,
      scene,
      sun,
      sunDistance: 36,
      sunIntensity: 2.15 * lightingScale,
    });
    sun.target.position.copy(focus);
    scene.fog.color.copy(result.timeState.fogColor);
    renderer.setClearColor(result.timeState.fogColor);
    skySystem.timeOfDay.applyParams({
      autoAdvanceSecondsPerDay: 0,
      latitude: 38,
      time: currentHour / 24,
    });
    skySystem.skyColor.applyParams(skyStyle === 'neutral_review'
      ? {
        amount: 0.68,
        enabled: true,
        palette: {
          brightness: 0.9,
          contrast: 0.86,
          enabled: true,
          horizonBlend: 0.22,
          horizonColor: new THREE.Color('#c4c8cb'),
          saturation: 0.16,
          zenithColor: new THREE.Color('#90979d'),
        },
      }
      : { enabled: false, palette: { enabled: false } });
    const sunState = {
      color: result.sunColor,
      direction: result.sunDirection,
      sky: result.skyColor,
    };
    grass.setSun(sunState);
    flowers.setSun(sunState);
    trees.forEach((item) => item.setSun(sunState));
    return {
      skyColor: result.skyColor,
      sunColor: lightingRoot.visible ? result.sunColor : new THREE.Color(0, 0, 0),
      sunDirection: result.sunDirection,
      waterLevel: -0.58,
    };
  }

  function applyComponentStyles(input) {
    const settings = createShaderPreviewSettings(input);
    const styles = resolveShaderPreviewComponentStyles(settings);
    materialBindings.forEach(({ component, material, tone }) => {
      if (authoredComponents.has(component)) return;
      const palette = STYLE_COLORS[styles[component]] ?? STYLE_COLORS.call_me_sensei;
      material.color?.set?.(palette[tone] ?? palette[component] ?? '#909090');
    });
    const grassPalette = STYLE_COLORS[styles.grass] ?? STYLE_COLORS.call_me_sensei;
    grass.applySettings({
      baseColor: srgbArray(grassPalette.grass),
      tipColor: srgbArray(grassPalette.grassTip),
    });
    const treePalette = STYLE_COLORS[styles.tree] ?? STYLE_COLORS.call_me_sensei;
    trees.forEach((item) => item.applySettings({ tree: { canopyColor: treePalette.tree } }));
    const flowerPalette = STYLE_COLORS[styles.flowers] ?? STYLE_COLORS.call_me_sensei;
    flowers.applySettings({
      centerColor: srgbArray(flowerPalette.flowerCenter),
      petalColor: srgbArray(flowerPalette.flowers),
    });
    lightingStyle = styles.lighting;
    skyStyle = styles.sky;
    applyTime(currentHour);
    document.body.dataset.previewStyleBundle = settings.bundle;
    document.body.dataset.previewScenePreset = settings.scenePreset;
    return styles;
  }

  function applyComponentVisibility(input) {
    const settings = createShaderPreviewSettings(input);
    const visible = {};
    Object.entries(componentRoots).forEach(([component, root]) => {
      const show = authoredComponents.has(component)
        || settings.componentVisibility[component] !== false;
      root.visible = show;
      if (component === 'clouds') skySystem.clouds.enabled = show;
      visible[component] = show;
    });
    document.body.dataset.previewVisibleComponents = Object.entries(visible)
      .filter(([, show]) => show)
      .map(([component]) => component)
      .join(',');
    return visible;
  }

  function resetCamera() {
    camera.up.set(0, 1, 0);
    camera.position.copy(defaultCameraPosition);
    camera.lookAt(focus);
    camera.updateProjectionMatrix();
    return focus;
  }

  resetCamera();
  document.body.dataset.previewLandscape = 'toonlab-natural-meadow';
  document.body.dataset.previewVegetationSource = 'toonlab-procedural-systems';
  document.body.dataset.previewSkySource = 'toonlab-sky-system';
  return {
    applyComponentStyles,
    applyComponentVisibility,
    applyTime,
    dispose() {
      skySystem.dispose();
      scene.remove(terrainRoot, rockRoot, grass, tree, flowers, manufacturedProps, lightingRoot);
      disposeObject(terrainRoot);
      disposeObject(rockRoot);
      grass.dispose();
      flowers.dispose();
      trees.forEach((item) => item.dispose());
      disposeObject(manufacturedProps);
      layers.forEach((layer) => layer.texture.dispose());
    },
    focus,
    groundField: field,
    groundLayers: layers,
    groundRoot,
    resetCamera,
    resize(width, height) {
      skySystem.resize(width, height);
    },
    rockRoot,
    setRockFixture,
    update(delta) {
      grass.update(delta, camera);
      flowers.update(delta);
      trees.forEach((item) => item.update(delta));
      skySystem.update(delta);
    },
  };
}
