export function materialText(mat: any): string;
export function hasAnyToken(text: any, tokens: any): any;
export function normalizeMaterialRole(value: any, fallback?: string): any;
export function materialRoleValue(value: any): any;
export function materialRoleName(value: any): any;
export function normalizeMaterialRoleOverrides(overrides?: any): Readonly<{
    byName: Map<any, any>;
    byUuid: Map<any, any>;
    patterns: any[];
    sourcesByUuid: Map<any, any>;
}> | {
    byName: Map<any, any>;
    byUuid: Map<any, any>;
    patterns: any;
    sourcesByUuid: Map<any, any>;
};
export function classifyMaterialRole(mat: any, overrides?: any): {
    isCostume: boolean;
    primaryRole: any;
    role: any;
    roleLabel: any;
    roleValue: any;
    source: any;
    isBlush: boolean;
    isCatchlight: boolean;
    isEye: boolean;
    isEyeHighlight: boolean;
    isFace: boolean;
    isHair: boolean;
    isIris: boolean;
    isMetal: boolean;
    isPupil: boolean;
    isSclera: boolean;
    isSkin: boolean;
    isTransparentOverlay: boolean;
} | {
    role: string;
    roleLabel: any;
    roleValue: any;
    source: string;
    isBlush: any;
    isCatchlight: any;
    isCostume: any;
    isEye: any;
    isEyeHighlight: any;
    isFace: any;
    isHair: any;
    isIris: any;
    isMetal: any;
    isPupil: any;
    isSclera: any;
    isSkin: any;
    isTransparentOverlay: any;
    primaryRole: string;
};
export function roleIsTransparentOverlay(roleInfo: any): boolean;
export function roleIsEyeHighlight(roleInfo: any): boolean;
export function roleIsCatchlight(roleInfo: any): boolean;
export function roleIsEye(roleInfo: any): boolean;
export function roleIsIris(roleInfo: any): boolean;
export function roleIsPupil(roleInfo: any): boolean;
export function roleIsSclera(roleInfo: any): boolean;
export function roleIsFace(roleInfo: any): boolean;
export function roleIsSkin(roleInfo: any): boolean;
export function roleIsHair(roleInfo: any): boolean;
export const MATERIAL_ROLES: Readonly<{
    default: 0;
    costume: 1;
    skin: 2;
    face: 3;
    hair: 4;
    eye: 5;
    eyeHighlight: 6;
    blush: 7;
    transparentOverlay: 8;
    metal: 9;
    outline: 10;
    iris: 11;
    pupil: 12;
    sclera: 13;
    catchlight: 14;
}>;
export const MATERIAL_ROLE_LABELS: Readonly<{
    default: "Default";
    costume: "Costume";
    skin: "Skin";
    face: "Face";
    hair: "Hair";
    eye: "Eye";
    eyeHighlight: "Eye Highlight";
    blush: "Blush";
    transparentOverlay: "Transparent Overlay";
    metal: "Metal";
    outline: "Outline";
    iris: "Iris";
    pupil: "Pupil";
    sclera: "Sclera";
    catchlight: "Catchlight";
}>;
export const MATERIAL_ROLE_NAMES_BY_VALUE: Readonly<{
    [k: string]: string;
}>;
