export function resolveToonDebugOutputMode(value: any): {
    label: any;
    name: any;
    value: any;
};
export function waitForTexture(texture: any): Promise<any>;
export function waitForObjectTextures(root: any): Promise<any[]>;
export function setObjectTextureColorSpaces(root: any): void;
export function setToonDebugOutput(root: any, debugOutputMode?: string): {
    label: any;
    name: any;
    value: any;
};
export function setToonDitherOpacity(target: any, opacity?: number): number;
export function applyToonSettingsToMaterial(target: any, settingsInput?: {}): {
    settings: {
        alpha: {
            blendCutoff: any;
            costumeCutout: boolean;
            cutoutCutoff: any;
            ditherOpacity: any;
            enabled: boolean;
            expressionTokenCutout: boolean;
            eyeHighlightOrder: any;
            eyeOrder: any;
            faceCutout: boolean;
            hairCutout: boolean;
            mapTransparentCutout: boolean;
            overlayDepthWrite: boolean;
            overlayOrder: any;
            preserveSourceAlphaTest: boolean;
            scleraOrder: any;
            skinCutout: boolean;
            sortOverlays: boolean;
            sourceAlphaMapCutout: boolean;
            sourceTransparentCutout: boolean;
            transparentOverlayBlend: boolean;
            transparentOpacityThreshold: any;
        };
        averageShadow: {
            defaultMinLight: any;
            defaultStrength: any;
            enabled: boolean;
            measuredBlend: any;
            eyeMinLight: any;
            eyeStrength: any;
            faceMinLight: any;
            faceStrength: any;
            hairMinLight: any;
            hairStrength: any;
            skinMinLight: any;
            skinStrength: any;
            softness: any;
        };
        baseTexture: Readonly<{
            customSaturation: 1;
            materialColorMode: "legacy";
            saturationMode: "legacy";
        }> | {
            customSaturation: any;
            materialColorMode: any;
            saturationMode: any;
        };
        celShade: {
            bodyCelMidPoint: any;
            bodyCelSoftness: any;
            bodyMainLightIgnoreCelShade: any;
            edgeAntiAliasStrength: any;
            enabled: boolean;
        };
        contactShadow: {
            enabled: boolean;
            faceHeadUpBlend: any;
            faceStrength: any;
            fadeRange: any;
            strength: any;
            thresholdOffset: any;
            width: any;
        };
        eyeHighlight: {
            color: any;
            enabled: boolean;
            intensity: any;
            maskChannel: any;
            maskMap: any;
            maskStrength: any;
            power: any;
            showInShadowArea: any;
            sourceMaskMode: "off" | "source";
        };
        faceLighting: {
            enabled: boolean;
            faceCelMidPoint: any;
            faceCelSoftness: any;
            faceLocalLightLift: any;
            faceMainLightIgnoreCelShade: any;
            faceNormalProxyBlend: any;
            faceProxyNormal: any[];
            faceSceneShadowStrength: any;
            faceSphereBlend: any;
            headSpaceMode: any;
        };
        fur: {
            density: any;
            enabled: boolean;
            gravity: any;
            length: any;
            materials: any[];
            roles: string[];
            rootOffset: any;
            rootShade: any;
            shellCount: number;
        };
        glitter: {
            enabled: boolean;
            intensity: any;
            density: any;
            size: any;
            randomNormalStrength: any;
            showInShadowArea: any;
            uvChannel: number;
            defaultIntensity: any;
            eyeIntensity: any;
            faceIntensity: any;
            hairIntensity: any;
            skinIntensity: any;
        };
        hairHighlight: {
            materialPresets: {
                byName: any;
                byUuid: any;
                patterns: any;
            };
            direction: any[];
            enabled: boolean;
            maskChannel: any;
            maskMap: any;
            maskStrength: any;
            mode: "legacy" | "anisotropic";
            intensity: any;
            shadowFloor: any;
            sideBandPower: any;
            sourceMaskMode: "off" | "source";
            strandPower: any;
            uvBandAxis: number;
            uvBandCenter: any;
            uvBandHalfWidth: any;
            uvPreset: string;
        };
        perspectiveRemoval: {
            amount: any;
            enabled: boolean;
            endHeight: any;
            radius: any;
            startHeight: any;
        };
        sticker: {
            blendMode: any;
            enabled: boolean;
            map: any;
            offset: any[];
            repeat: any[];
            strength: any;
            uvChannel: number;
        };
        indirectLight: {
            ambientTint: any;
            defaultIntensity: any;
            defaultMinimumIndirectLight: any;
            enabled: boolean;
            environmentIndirectLight: any;
            eyeIntensity: any;
            eyeMinimumIndirectLight: any;
            faceIntensity: any;
            faceMinimumIndirectLight: any;
            hairIntensity: any;
            hairMinimumIndirectLight: any;
            hemisphereLightIntensity: any;
            skinIntensity: any;
            skinMinimumIndirectLight: any;
        };
        localLights: {
            defaultIntensity: any;
            defaultMaxContribution: any;
            defaultShadowLift: any;
            enabled: boolean;
            eyeIntensity: any;
            eyeMaxContribution: any;
            eyeShadowLift: any;
            faceIntensity: any;
            faceMaxContribution: any;
            faceShadowLift: any;
            hairIntensity: any;
            hairMaxContribution: any;
            hairShadowLift: any;
            skinIntensity: any;
            skinMaxContribution: any;
            skinShadowLift: any;
        };
        materialMaps: {
            aoMap: any;
            aoStrength: any;
            detailMap: any;
            detailRepeat: any;
            detailStrength: any;
            emissiveColor: any;
            emissiveMap: any;
            emissiveStrength: any;
            enabled: boolean;
            matcapMap: any;
            matcapStrength: any;
            metalnessMap: any;
            metalnessStrength: any;
            normalMap: any;
            normalScale: any;
            normalStrength: any;
            rampMap: any;
            rampStrength: any;
            roughnessMap: any;
            roughnessStrength: any;
            sourceMode: "off" | "source";
            specularColorMap: any;
            specularColorStrength: any;
        };
        materialRoles: any;
        outline: {
            defaultLightingMix: any;
            defaultMaxBrightness: any;
            defaultMinBrightness: any;
            defaultTintColor: any;
            defaultWidth: any;
            depthOffset: any;
            depthTest: boolean;
            depthWrite: boolean;
            enabled: boolean;
            eyeLightingMix: any;
            eyeMaxBrightness: any;
            eyeMinBrightness: any;
            eyeTintColor: any;
            eyeWidth: any;
            faceLightingMix: any;
            faceMaxBrightness: any;
            faceMinBrightness: any;
            faceTintColor: any;
            faceWidth: any;
            hairCutoutWidth: any;
            hairLightingMix: any;
            hairMaxBrightness: any;
            hairMinBrightness: any;
            hairTintColor: any;
            hairWidth: any;
            maxWidth: any;
            metalLightingMix: any;
            metalMaxBrightness: any;
            metalMinBrightness: any;
            metalTintColor: any;
            metalWidth: any;
            polygonOffset: boolean;
            polygonOffsetFactor: any;
            polygonOffsetUnits: any;
            referenceDistance: any;
            referenceFov: any;
            screenSpaceWidth: any;
            smoothNormals: boolean;
            widthFadeDistance: any;
            skinLightingMix: any;
            skinMaxBrightness: any;
            skinMinBrightness: any;
            skinTintColor: any;
            skinWidth: any;
            transparentOverlayWidth: any;
            widthScale: any;
        };
        preset: any;
        presetDescription: string;
        presetLabel: any;
        rimLight: {
            blockByShadow: any;
            defaultIntensity: any;
            defaultTintColor: any;
            depthCloseWidthReduce: any;
            depthDottedLineFix: boolean;
            depthFadeEndDistance: any;
            depthFadeRange: any;
            depthFadeStartDistance: any;
            depthMask3D: boolean;
            depthSafeDistance: any;
            depthThresholdOffset: any;
            depthWidth: any;
            enabled: boolean;
            eyeIntensity: any;
            faceIntensity: any;
            hairIntensity: any;
            midPoint: any;
            mixWithBaseMapColor: any;
            mode: any;
            skinIntensity: any;
            softness: any;
        };
        sceneShadow: {
            defaultMinLight: any;
            defaultStrength: any;
            enabled: boolean;
            eyeMinLight: any;
            eyeStrength: any;
            faceMinLight: any;
            faceStrength: any;
            shadowAreaStrength: any;
            skinMinLight: any;
            skinStrength: any;
        };
        selfShadow: {
            defaultMinLight: any;
            defaultStrength: any;
            enabled: boolean;
            eyeMinLight: any;
            eyeStrength: any;
            faceMinLight: any;
            faceStrength: any;
            hairMinLight: any;
            hairStrength: any;
            shadowAreaStrength: any;
            skinMinLight: any;
            skinStrength: any;
            sourceMode: 0 | 1 | 2;
        };
        shadowColor: {
            enabled: boolean;
            lowSaturationFallbackColor: any;
            selfShadowAlbedoMulStrength: any;
            selfShadowAreaHSVStrength: any;
            selfShadowAreaHueOffset: any;
            selfShadowAreaSaturationBoost: any;
            selfShadowAreaValueMul: any;
            selfShadowTintColor: any;
            transitionAreaHueOffset: any;
            transitionAreaIntensity: any;
            transitionAreaSaturationBoost: any;
            transitionAreaTintColor: any;
            transitionAreaValueMul: any;
        };
        skinTone: {
            enabled: boolean;
            faceMaxDirectLight: any;
            faceMinimumIndirectLight: any;
            faceShadowBrightness: any;
            faceShadowSaturation: any;
            faceShadowTint: any;
            faceShadowTintStrength: any;
            skinMaxDirectLight: any;
            skinMinimumIndirectLight: any;
            skinShadowBrightness: any;
            skinShadowSaturation: any;
            skinShadowTint: any;
            skinShadowTintStrength: any;
        };
        specular: {
            defaultColor: any;
            defaultIntensity: any;
            defaultMidPoint: any;
            defaultPower: any;
            defaultRange: any;
            defaultShowInShadowArea: any;
            directionMode: "light" | "view";
            enabled: boolean;
            eyeIntensity: any;
            eyeMidPoint: any;
            eyePower: any;
            eyeRange: any;
            eyeShowInShadowArea: any;
            faceIntensity: any;
            hairIntensity: any;
            hairPower: any;
            maskChannel: any;
            maskMap: any;
            maskStrength: any;
            metalIntensity: any;
            skinIntensity: any;
            sourceMaskMode: "off" | "source";
        };
    };
    updatedMaterialCount: number;
};
export function findPrimarySkinnedMesh(root: any): any;
export function applyToonShader(root: any, { alpha, averageShadow, baseTexture, celShade, contactShadow, debugOutputMode, eyeHighlight, faceLighting, fur, glitter, hairHighlight, indirectLight, localLights, materialMaps, materialRoles, outline, perspectiveRemoval, preset, rimLight, sceneShadow, selfShadow, settings, shadowColor, shaderMode, specular, skinTone, sticker, }?: {
    alpha?: any;
    averageShadow?: any;
    baseTexture?: any;
    celShade?: any;
    contactShadow?: any;
    debugOutputMode?: string;
    eyeHighlight?: any;
    faceLighting?: any;
    fur?: any;
    glitter?: any;
    hairHighlight?: any;
    indirectLight?: any;
    localLights?: any;
    materialMaps?: any;
    materialRoles?: any;
    outline?: any;
    perspectiveRemoval?: any;
    preset?: any;
    rimLight?: any;
    sceneShadow?: any;
    selfShadow?: any;
    settings?: any;
    shadowColor?: any;
    shaderMode?: string;
    specular?: any;
    skinTone?: any;
    sticker?: any;
}): {
    convertedMeshCount: number;
    debugOutputMode: {
        label: any;
        name: any;
        value: any;
    };
    materialRoleSummary: {
        counts: {};
        materials: any[];
        total: number;
    };
    primarySkinnedMesh: any;
    settings: {
        alpha: {
            blendCutoff: any;
            costumeCutout: boolean;
            cutoutCutoff: any;
            ditherOpacity: any;
            enabled: boolean;
            expressionTokenCutout: boolean;
            eyeHighlightOrder: any;
            eyeOrder: any;
            faceCutout: boolean;
            hairCutout: boolean;
            mapTransparentCutout: boolean;
            overlayDepthWrite: boolean;
            overlayOrder: any;
            preserveSourceAlphaTest: boolean;
            scleraOrder: any;
            skinCutout: boolean;
            sortOverlays: boolean;
            sourceAlphaMapCutout: boolean;
            sourceTransparentCutout: boolean;
            transparentOverlayBlend: boolean;
            transparentOpacityThreshold: any;
        };
        averageShadow: {
            defaultMinLight: any;
            defaultStrength: any;
            enabled: boolean;
            measuredBlend: any;
            eyeMinLight: any;
            eyeStrength: any;
            faceMinLight: any;
            faceStrength: any;
            hairMinLight: any;
            hairStrength: any;
            skinMinLight: any;
            skinStrength: any;
            softness: any;
        };
        baseTexture: Readonly<{
            customSaturation: 1;
            materialColorMode: "legacy";
            saturationMode: "legacy";
        }> | {
            customSaturation: any;
            materialColorMode: any;
            saturationMode: any;
        };
        celShade: {
            bodyCelMidPoint: any;
            bodyCelSoftness: any;
            bodyMainLightIgnoreCelShade: any;
            edgeAntiAliasStrength: any;
            enabled: boolean;
        };
        contactShadow: {
            enabled: boolean;
            faceHeadUpBlend: any;
            faceStrength: any;
            fadeRange: any;
            strength: any;
            thresholdOffset: any;
            width: any;
        };
        eyeHighlight: {
            color: any;
            enabled: boolean;
            intensity: any;
            maskChannel: any;
            maskMap: any;
            maskStrength: any;
            power: any;
            showInShadowArea: any;
            sourceMaskMode: "off" | "source";
        };
        faceLighting: {
            enabled: boolean;
            faceCelMidPoint: any;
            faceCelSoftness: any;
            faceLocalLightLift: any;
            faceMainLightIgnoreCelShade: any;
            faceNormalProxyBlend: any;
            faceProxyNormal: any[];
            faceSceneShadowStrength: any;
            faceSphereBlend: any;
            headSpaceMode: any;
        };
        fur: {
            density: any;
            enabled: boolean;
            gravity: any;
            length: any;
            materials: any[];
            roles: string[];
            rootOffset: any;
            rootShade: any;
            shellCount: number;
        };
        glitter: {
            enabled: boolean;
            intensity: any;
            density: any;
            size: any;
            randomNormalStrength: any;
            showInShadowArea: any;
            uvChannel: number;
            defaultIntensity: any;
            eyeIntensity: any;
            faceIntensity: any;
            hairIntensity: any;
            skinIntensity: any;
        };
        hairHighlight: {
            materialPresets: {
                byName: any;
                byUuid: any;
                patterns: any;
            };
            direction: any[];
            enabled: boolean;
            maskChannel: any;
            maskMap: any;
            maskStrength: any;
            mode: "legacy" | "anisotropic";
            intensity: any;
            shadowFloor: any;
            sideBandPower: any;
            sourceMaskMode: "off" | "source";
            strandPower: any;
            uvBandAxis: number;
            uvBandCenter: any;
            uvBandHalfWidth: any;
            uvPreset: string;
        };
        perspectiveRemoval: {
            amount: any;
            enabled: boolean;
            endHeight: any;
            radius: any;
            startHeight: any;
        };
        sticker: {
            blendMode: any;
            enabled: boolean;
            map: any;
            offset: any[];
            repeat: any[];
            strength: any;
            uvChannel: number;
        };
        indirectLight: {
            ambientTint: any;
            defaultIntensity: any;
            defaultMinimumIndirectLight: any;
            enabled: boolean;
            environmentIndirectLight: any;
            eyeIntensity: any;
            eyeMinimumIndirectLight: any;
            faceIntensity: any;
            faceMinimumIndirectLight: any;
            hairIntensity: any;
            hairMinimumIndirectLight: any;
            hemisphereLightIntensity: any;
            skinIntensity: any;
            skinMinimumIndirectLight: any;
        };
        localLights: {
            defaultIntensity: any;
            defaultMaxContribution: any;
            defaultShadowLift: any;
            enabled: boolean;
            eyeIntensity: any;
            eyeMaxContribution: any;
            eyeShadowLift: any;
            faceIntensity: any;
            faceMaxContribution: any;
            faceShadowLift: any;
            hairIntensity: any;
            hairMaxContribution: any;
            hairShadowLift: any;
            skinIntensity: any;
            skinMaxContribution: any;
            skinShadowLift: any;
        };
        materialMaps: {
            aoMap: any;
            aoStrength: any;
            detailMap: any;
            detailRepeat: any;
            detailStrength: any;
            emissiveColor: any;
            emissiveMap: any;
            emissiveStrength: any;
            enabled: boolean;
            matcapMap: any;
            matcapStrength: any;
            metalnessMap: any;
            metalnessStrength: any;
            normalMap: any;
            normalScale: any;
            normalStrength: any;
            rampMap: any;
            rampStrength: any;
            roughnessMap: any;
            roughnessStrength: any;
            sourceMode: "off" | "source";
            specularColorMap: any;
            specularColorStrength: any;
        };
        materialRoles: any;
        outline: {
            defaultLightingMix: any;
            defaultMaxBrightness: any;
            defaultMinBrightness: any;
            defaultTintColor: any;
            defaultWidth: any;
            depthOffset: any;
            depthTest: boolean;
            depthWrite: boolean;
            enabled: boolean;
            eyeLightingMix: any;
            eyeMaxBrightness: any;
            eyeMinBrightness: any;
            eyeTintColor: any;
            eyeWidth: any;
            faceLightingMix: any;
            faceMaxBrightness: any;
            faceMinBrightness: any;
            faceTintColor: any;
            faceWidth: any;
            hairCutoutWidth: any;
            hairLightingMix: any;
            hairMaxBrightness: any;
            hairMinBrightness: any;
            hairTintColor: any;
            hairWidth: any;
            maxWidth: any;
            metalLightingMix: any;
            metalMaxBrightness: any;
            metalMinBrightness: any;
            metalTintColor: any;
            metalWidth: any;
            polygonOffset: boolean;
            polygonOffsetFactor: any;
            polygonOffsetUnits: any;
            referenceDistance: any;
            referenceFov: any;
            screenSpaceWidth: any;
            smoothNormals: boolean;
            widthFadeDistance: any;
            skinLightingMix: any;
            skinMaxBrightness: any;
            skinMinBrightness: any;
            skinTintColor: any;
            skinWidth: any;
            transparentOverlayWidth: any;
            widthScale: any;
        };
        preset: any;
        presetDescription: string;
        presetLabel: any;
        rimLight: {
            blockByShadow: any;
            defaultIntensity: any;
            defaultTintColor: any;
            depthCloseWidthReduce: any;
            depthDottedLineFix: boolean;
            depthFadeEndDistance: any;
            depthFadeRange: any;
            depthFadeStartDistance: any;
            depthMask3D: boolean;
            depthSafeDistance: any;
            depthThresholdOffset: any;
            depthWidth: any;
            enabled: boolean;
            eyeIntensity: any;
            faceIntensity: any;
            hairIntensity: any;
            midPoint: any;
            mixWithBaseMapColor: any;
            mode: any;
            skinIntensity: any;
            softness: any;
        };
        sceneShadow: {
            defaultMinLight: any;
            defaultStrength: any;
            enabled: boolean;
            eyeMinLight: any;
            eyeStrength: any;
            faceMinLight: any;
            faceStrength: any;
            shadowAreaStrength: any;
            skinMinLight: any;
            skinStrength: any;
        };
        selfShadow: {
            defaultMinLight: any;
            defaultStrength: any;
            enabled: boolean;
            eyeMinLight: any;
            eyeStrength: any;
            faceMinLight: any;
            faceStrength: any;
            hairMinLight: any;
            hairStrength: any;
            shadowAreaStrength: any;
            skinMinLight: any;
            skinStrength: any;
            sourceMode: 0 | 1 | 2;
        };
        shadowColor: {
            enabled: boolean;
            lowSaturationFallbackColor: any;
            selfShadowAlbedoMulStrength: any;
            selfShadowAreaHSVStrength: any;
            selfShadowAreaHueOffset: any;
            selfShadowAreaSaturationBoost: any;
            selfShadowAreaValueMul: any;
            selfShadowTintColor: any;
            transitionAreaHueOffset: any;
            transitionAreaIntensity: any;
            transitionAreaSaturationBoost: any;
            transitionAreaTintColor: any;
            transitionAreaValueMul: any;
        };
        skinTone: {
            enabled: boolean;
            faceMaxDirectLight: any;
            faceMinimumIndirectLight: any;
            faceShadowBrightness: any;
            faceShadowSaturation: any;
            faceShadowTint: any;
            faceShadowTintStrength: any;
            skinMaxDirectLight: any;
            skinMinimumIndirectLight: any;
            skinShadowBrightness: any;
            skinShadowSaturation: any;
            skinShadowTint: any;
            skinShadowTintStrength: any;
        };
        specular: {
            defaultColor: any;
            defaultIntensity: any;
            defaultMidPoint: any;
            defaultPower: any;
            defaultRange: any;
            defaultShowInShadowArea: any;
            directionMode: "light" | "view";
            enabled: boolean;
            eyeIntensity: any;
            eyeMidPoint: any;
            eyePower: any;
            eyeRange: any;
            eyeShowInShadowArea: any;
            faceIntensity: any;
            hairIntensity: any;
            hairPower: any;
            maskChannel: any;
            maskMap: any;
            maskStrength: any;
            metalIntensity: any;
            skinIntensity: any;
            sourceMaskMode: "off" | "source";
        };
    };
    shaderMode: string;
    toonPreset: any;
};
export const TOON_DEBUG_OUTPUT_MODES: Readonly<{
    off: 0;
    final: 0;
    albedo: 1;
    sourceAlbedo: 8;
    rawAlbedo: 8;
    source: 8;
    raw: 8;
    band: 2;
    cel: 2;
    shadow: 3;
    sceneShadow: 3;
    selfShadow: 9;
    directVisibility: 10;
    averageShadow: 10;
    rim: 11;
    rimLight: 11;
    depthRim: 23;
    contactShadow: 24;
    specular: 12;
    specularArea: 12;
    specularMask: 12;
    hairHighlight: 13;
    eyeHighlight: 14;
    normalMap: 15;
    aoMap: 16;
    emissiveMap: 17;
    matcap: 18;
    ramp: 19;
    detailMap: 20;
    roughnessMap: 21;
    metalnessMap: 22;
    shadowColor: 4;
    lit: 5;
    lighting: 5;
    role: 6;
    alpha: 7;
}>;
export const TOON_DEBUG_OUTPUT_LABELS: Readonly<{
    off: "Off";
    albedo: "Albedo";
    sourceAlbedo: "Source Albedo";
    band: "Cel Band";
    shadow: "Scene Shadow";
    selfShadow: "Self Shadow";
    directVisibility: "Direct Visibility";
    rim: "Rim Light";
    depthRim: "Depth Rim";
    contactShadow: "Contact Shadow";
    specular: "Specular";
    hairHighlight: "Hair Highlight";
    eyeHighlight: "Eye Highlight";
    normalMap: "Normal Map";
    aoMap: "AO Map";
    emissiveMap: "Emissive Map";
    matcap: "MatCap";
    ramp: "Ramp";
    detailMap: "Detail Map";
    roughnessMap: "Roughness Map";
    metalnessMap: "Metalness Map";
    shadowColor: "Shadow Color";
    lit: "Lighting";
    role: "Material Role";
    alpha: "Alpha";
}>;
export { alphaTestForMaterial, createAlphaSettings, DEFAULT_ALPHA_SETTINGS, resolveAlphaForMaterial, sourceOpacity, usesAlphaBlend, usesAlphaCutout } from "./settings/alphaSettings.js";
export { createAverageShadowSettings, DEFAULT_AVERAGE_SHADOW_SETTINGS, resolveAverageShadowForMaterial } from "./settings/averageShadowSettings.js";
export { BASE_TEXTURE_MATERIAL_COLOR_MODES, BASE_TEXTURE_SATURATION_MODES, createBaseTextureSettings, DEFAULT_BASE_TEXTURE_SETTINGS } from "./settings/baseTextureSettings.js";
export { CEL_SHADE_PRESETS, createCelShadeSettings, DEFAULT_CEL_SHADE_SETTINGS, REFERENCE_CEL_SHADE_SETTINGS } from "./settings/celShadeSettings.js";
export { createContactShadowSettings, DEFAULT_CONTACT_SHADOW_SETTINGS, resolveContactShadowForMaterial } from "./settings/contactShadowSettings.js";
export { createFaceLightingSettings, DEFAULT_FACE_LIGHTING_SETTINGS, FACE_HEAD_SPACE_MODES } from "./settings/faceLightingSettings.js";
export { createFurSettings, DEFAULT_FUR_SETTINGS, materialUsesFur } from "./settings/furSettings.js";
export { createGlitterSettings, DEFAULT_GLITTER_SETTINGS, resolveGlitterForMaterial } from "./settings/glitterSettings.js";
export { createPerspectiveRemovalSettings, DEFAULT_PERSPECTIVE_REMOVAL_SETTINGS } from "./settings/perspectiveRemovalSettings.js";
export { createStickerSettings, DEFAULT_STICKER_SETTINGS, resolveStickerForMaterial, STICKER_BLEND_MODES } from "./settings/stickerSettings.js";
export { createEyeHighlightSettings, DEFAULT_EYE_HIGHLIGHT_SETTINGS, EYE_HIGHLIGHT_MASK_CHANNELS, EYE_HIGHLIGHT_SOURCE_MASK_MODES, resolveEyeHighlightForMaterial } from "./settings/eyeHighlightSettings.js";
export { createIndirectLightSettings, DEFAULT_INDIRECT_LIGHT_SETTINGS, resolveIndirectLightForMaterial } from "./settings/indirectLightSettings.js";
export { createHairHighlightSettings, DEFAULT_HAIR_HIGHLIGHT_SETTINGS, HAIR_HIGHLIGHT_MASK_CHANNELS, HAIR_HIGHLIGHT_MODES, HAIR_HIGHLIGHT_MODE_VALUES, HAIR_HIGHLIGHT_SOURCE_MASK_MODES, resolveHairHighlightForMaterial } from "./settings/hairHighlightSettings.js";
export { createLocalLightSettings, DEFAULT_LOCAL_LIGHT_SETTINGS, resolveLocalLightForMaterial } from "./settings/localLightSettings.js";
export { createMaterialMapSettings, DEFAULT_MATERIAL_MAP_SETTINGS } from "./settings/materialMapSettings.js";
export { createOutlineSettings, DEFAULT_OUTLINE_SETTINGS, resolveOutlineForMaterial } from "./settings/outlineSettings.js";
export { createRimLightSettings, DEFAULT_RIM_LIGHT_SETTINGS, resolveRimLightForMaterial, RIM_LIGHT_MODES } from "./settings/rimLightSettings.js";
export { createSpecularSettings, DEFAULT_SPECULAR_SETTINGS, resolveSpecularForMaterial, SPECULAR_DIRECTION_MODES, SPECULAR_MASK_CHANNELS, SPECULAR_SOURCE_MASK_MODES } from "./settings/specularSettings.js";
export { createSkinToneSettings, DEFAULT_SKIN_TONE_SETTINGS } from "./settings/skinToneSettings.js";
export { createShadowColorSettings, DEFAULT_SHADOW_COLOR_SETTINGS, REFERENCE_SHADOW_COLOR_SETTINGS, SHADOW_COLOR_PRESETS } from "./settings/shadowColorSettings.js";
export { createSceneShadowSettings, DEFAULT_SCENE_SHADOW_SETTINGS, resolveSceneShadowForMaterial } from "./settings/sceneShadowSettings.js";
export { createSelfShadowSettings, DEFAULT_SELF_SHADOW_SETTINGS, resolveSelfShadowForMaterial, SELF_SHADOW_SOURCE_MODES } from "./settings/selfShadowSettings.js";
export { createToonPresetDocument, createToonSettings, getToonPresetDefinition, getToonPresetIds, getToonPresetMetadata, getToonPresetOptions, getToonSettingFieldSchema, getToonSettingGroupMetadata, normalizeToonPresetName, parseToonPresetDocument, registerToonPreset, registerSerializedToonPreset, sanitizeToonPresetSettings, serializeToonPreset, TOON_PRESET_DOCUMENT_TYPE, TOON_PRESET_IDS, TOON_PRESET_SCHEMA_VERSION, TOON_SETTING_DEFAULTS, TOON_SETTING_FIELD_SCHEMA, TOON_SETTING_GROUP_METADATA, TOON_SETTING_GROUPS, validateToonPresetDocument } from "./toonSettings.js";
export { classifyMaterialRole, materialRoleName, materialRoleValue, MATERIAL_ROLE_LABELS, MATERIAL_ROLE_NAMES_BY_VALUE, MATERIAL_ROLES, normalizeMaterialRole, normalizeMaterialRoleOverrides, roleIsCatchlight, roleIsEye, roleIsEyeHighlight, roleIsIris, roleIsPupil, roleIsSclera } from "../core/materialRoles.js";
